### ISSUE TITLE
Application does not filter by groupId

### ISSUE THREAD

**Issue by SParaparan** [wso2/product-apim#4209] opened 2019-01-24 11:10 UTC
**Description:**
When we give groupId as a parameter in the application search rest API it drops in the process of the request. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rmsamitha** [comment] 2022-01-27 13:25
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-27 13:25 UTC
