### ISSUE TITLE
Unwanted UI validation for Group field in the Application sharing feature

### ISSUE THREAD

**Issue by dinusha-dilrukshi** [wso2/product-apim#3176] opened 2018-04-05 14:05 UTC
**Description:**
- Try to give the group name as "test/API_manager_WSO2_test_subscriber"
- This gives a validation error for symbol '/' and length greater than 30.
- But when you are editing the app. it can assign the same group without validation error.
- By looking at the code where validation happens (store/site/themes/wso2/templates/application/application-add/js/application-add.js ). This validation seems not correct. We should be able to remove it.

-----------------
 if(/([~!@#;%^&*+=\|\\<>\"\'\/,])/.test(tagName)){
                $tag.val( $tag.val().replace(/[^a-zA-Z0-9_ -]/g, function(str) {
                    $('.tags-error').show();
                    $('.add-tags-error').hide();
                    $('.add-tags-error').html('');
                    $('.tags-error').html('Group Id contains one or more illegal characters  (~ ! @ #  ; % ^ & *' +
                        ' + = { } | &lt; &gt;, \' " \\ \/ ) .');
                    return '';
                }));
            }

            if(tagName.length > 30){
                $tag.val(tagName.substring(0, 30));
                $('.tags-error').html(i18n.t('A Group Id can only have a maximum of 30 characters.'));
            }
--------------------------

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.1.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by kavishkafernando** [comment] 2020-11-27 09:21
Similar issue : https://github.com/wso2/product-apim/issues/3213

**Comment by rmsamitha** [comment] 2022-01-28 04:18
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:18 UTC
Labels: Affected/2.1.0
