### ISSUE TITLE
When password grant type fails due to invalid credentials it returns HTTP status 400 bad request, instead of 401.

### ISSUE THREAD

**Issue by Sewmi** [wso2/product-apim#3377] opened 2018-06-09 10:44 UTC
**Description:**

When trying to generate a user token using password grant type given invalid username and password the response returns HTTP status code 400 bad request instead of 401.

Furthermore, if the user uses invalid application credentials the request will return 401.

**Suggested Labels:**
Bug

**Affected Product Version:**
wso2am-2.2.0.1528222222291.zip

**OS, DB, other environment details and versions:**   
Mac OS 

**Steps to reproduce:**

Replace the base64Endoces(client_key:client_secret) from a valid application and try out password grant type with invalid username/password.

curl -k -d "grant_type=password&username=admin1&password=admin" -H "Authorization: Basic b1I0T3k3RE1vYmY2V0xBYWJnYlRvVVNfVUkwYTpORTNhblNxZjFhckdUVTU4TVl5WEU5YTBCVEFh" https://192.168.1.102:8243/token -v

**Work Around**
https://stackoverflow.com/questions/42901690/wso2-api-manager-error-code-for-grant-type-password-invalid

**Comment by rmsamitha** [comment] 2022-01-28 04:12
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:12 UTC
Labels: Affected/2.2.0
