### ISSUE TITLE
[UX] Publisher should be able to enforce grace period notifications from publisher app

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2991] opened 2018-03-12 04:13 UTC
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Visibility of system status -Is the user informed about what's going on
Consistency and standards - Is flow maintain the same patterns and consistency
Recognition rather than recall - Is the objects, actions, and options clearly visible

***Related task:***
Enforce grace period to upgrade

***Issue and proposed solution:***
Without going to the carbon console Main > Resource > Browse and editing tenant-conf.json, publisher should be able to enter grace period, enable notification and edit email options(title, content body etc) to notify subscribers about API depreciation. When the time is up the publisher should be notified to depreciate the old API when login to publisher.  

***Related Doc Link:***
[1] https://docs.wso2.com/display/AM210/Enabling+Notifications	
[2] https://docs.wso2.com/display/AM2xx/API+Versioning

**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.1.0

**Comment by rmsamitha** [comment] 2022-01-28 04:32
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:32 UTC
Labels: Priority/Low, Affected/2.1.0
