### ISSUE TITLE
API Store unable to open API Console for a specific API resource

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/product-apim#3846] opened 2018-10-13 16:34 UTC
**Description:**
Try it window fails to load for specific API resources.
Observed in the 2.2.0. Can not be observed in the 2.5.0

**Affected Product Version:**
2.2.0

**Comment by HiranyaKavishani** [comment] 2018-11-13 09:31
Duplicate of  (https://github.com/wso2/product-apim/issues/3793)

**Closed** 2018-11-13 09:33 UTC
