### ISSUE TITLE
PizzaShackAPI's backend responses are not align with the default swagger definition which makes downloaded SDKs unusable

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#1607] opened 2017-09-22 06:37 UTC
Eg:
Definition:

```
  Order:
    title: Pizza Order
    properties:
      customerName:
        type: string
      delivered:
        type: boolean
      address:
        type: string
      pizzaType:
        type: string
      creditCardNumber:
        type: string
      quantity:
        type: number
      orderId:
        type: integer
    required:
      - orderId
```

Actual Response:
`{
  "orderId": "67f50853-c037-48d5-989a-791306460aa1",
  "pizzaType": "string",
  "quantity": 0,
  "customerName": "string",
  "creditCardNumber": "string",
  "address": "string",
  "delivered": true
}`

orderId's type should be "string".

The below code which uses the SDK will give below error:
```
        DefaultApi defaultApi = new DefaultApi();
        ApiClient apiClient = defaultApi.getApiClient();
        String accessToken = "a2066459-4245-3a04-9124-065f47442c7d";
        apiClient.addDefaultHeader("Authorization", "Bearer " + accessToken);
        apiClient.setBasePath("http://172.17.42.1:8280/pizzashack/1.0.0");
        Order order = new Order();
        order.address("address");
        order.creditCardNumber("1212-321213-313");
        order.customerName("cust");
        defaultApi.orderPost(order);
```

```
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "aa837987-e534-4f9c-aa9f-1feb7fefadbd"
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:249)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:239)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
	at com.google.gson.Gson.fromJson(Gson.java:879)
	at com.google.gson.Gson.fromJson(Gson.java:844)
	at com.google.gson.Gson.fromJson(Gson.java:793)
	at org.wso2.client.api.JSON.deserialize(JSON.java:115)
	at org.wso2.client.api.ApiClient.deserialize(ApiClient.java:851)
	at org.wso2.client.api.ApiClient.handleResponse(ApiClient.java:1047)
	at org.wso2.client.api.ApiClient.execute(ApiClient.java:981)
	at org.wso2.client.api.PizzaShackAPI.DefaultApi.orderPostWithHttpInfo(DefaultApi.java:563)
	at org.wso2.client.api.PizzaShackAPI.DefaultApi.orderPost(DefaultApi.java:549)
	at Main.main(Main.java:18)
Caused by: java.lang.NumberFormatException: For input string: "aa837987-e534-4f9c-aa9f-1feb7fefadbd"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1198)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:247)
	... 13 more
```
There are same type of issues in Menu definition as well.

**Comment by irham0019** [comment] 2018-01-11 08:30
The issue is fixed by the above commit

**Closed** 2018-01-11 08:30 UTC
Labels: 2.1.0, Severity/Major, Type/Bug
