### ISSUE TITLE
API Store Sharing new API details via Facebook gives a error as this feature is not supported

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2607] opened 2018-01-25 05:54 UTC
**Suggested Labels:**
APIM 2.2.0
Type/Bug
Priority/High
Severity/Major

**Affected Product Version:**
APIM 2.1.0 Update7 pack

**OS, DB, other environment details and versions:**
MYSQL 5.7
jdk - 1.8.0_121
ubuntu 16.04

**Steps to Reproduce:**

1.Run the APIM 2.1.0 update 7 pack
2.Create and Publish a REST API from API Publisher as admin
3.Access API Store as admin
4.Select the Particular API from API Store. Go to Overview Section
5.Click on facebook icon
6. Provide Facebook login details

**Observation**
An error message will be displayed as error processing the request and this feature is not supported [1]

[1]. fb-error.png
![fb-error](https://user-images.githubusercontent.com/31848014/35372836-efa7c4e2-01c1-11e8-89ca-9b063fabd314.png)

**Comment by rmsamitha** [comment] 2022-01-28 04:53
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:53 UTC
Labels: Priority/Normal
