### ISSUE TITLE
wso2apim-3.0.0-m10: pack takes 40+ seconds to start 

### ISSUE THREAD

**Issue by samisawso2** [wso2/product-apim#2007] opened 2017-12-16 07:54 UTC
**Description:**
[2017-12-16 07:48:10,786]  INFO {org.wso2.carbon.kernel.internal.CarbonStartupHandler} - WSO2 Carbon Kernel started in 41.250 sec

I thought this would start up much faster. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
Mac OS
Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

**Steps to reproduce:**

**Related Issues:**

**Comment by malinthaprasan** [comment] 2017-12-18 11:21
Hi @samisawso2,

We can normally start the server within 4 to 7 seconds so taking 41 seconds is probably due to some issue.

We checked this with multiple linux/mac machines with above java version from the team (the closest
version we had was Darwin Kernel Version 16.6.0). This was only reproducible on one mac machine. there, the issue was narrowed down to [1] where hostname to my /etc/hosts hostname was missing in /etc/hosts file. After adding it, the issue was resolved in that machine too. Can you please check that?

[1] http://shammijayasinghe.blogspot.com/2017/04/wso2-server-startup-taking-lot-of-time.html

Thanks

**Comment by samisawso2** [comment] 2017-12-19 13:47
My /etc/hosts read

127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost 
fe80::1%lo0     localhost

**Comment by samisawso2** [comment] 2017-12-19 13:56
I fixed only the line 
::1             localhost       Samisas-MacBook-Pro.local

and it got fixed 
[2017-12-19 19:24:29,269]  INFO {org.wso2.carbon.kernel.internal.CarbonStartupHandler} - WSO2 Carbon Kernel started in 5.062 sec

I think we need to document this somewhere.

**Comment by malinthaprasan** [comment] 2017-12-20 04:45
Hi @samisawso2,

Noted. We will document this before closing the issue.

**Comment by malinthaprasan** [comment] 2017-12-21 12:06
Documents updated https://docs.wso2.com/display/AM300/Installation+Guide. Thanks @taniamahanama 

Thanks @prasa7 for identifying this issue related to Mac.

**Closed by malinthaprasan** 2017-12-21 12:06 UTC
Labels: 3.0.0, documentation-required
