### ISSUE TITLE
A DataTable error message appears in Store UI as an alert box

### ISSUE THREAD

**Issue by sajhak** [wso2/product-apim#1648] opened 2017-10-11 13:10 UTC
**Description:**
Refer the attached image contains the error message

**Affected Product Version:**
APIM 2.1.0

**Steps to reproduce:**
- create an API and publish as a publisher user
- create 2 Store users ( store1, store2), and with both the users, subscribe to that API
- create a new role (role1) in mgt console and assign that role to "store2"
- as the publisher, edit the API's visibility level to restricted by role, and restrict to role, "role1", and republish the API
- Login to the store and go to applications -> and click on the application which used to subscribed to the api. For "store1" user there won't be any issue, but for "store2" user, this exception appears in the store UI.

error log : [error-log.txt](https://github.com/wso2/product-apim/files/1375673/error-log.txt)

![error](https://user-images.githubusercontent.com/2729165/31441932-0407ffae-ae95-11e7-8f19-82e0dc96cb03.png)

**Comment by ryskulduishonkul** [comment] 2019-06-19 16:10
Hi Sajhak, did you able to resolve this, I hame same issue here.

**Comment by dushaniw** [comment] 2020-11-10 06:58
Cannot reproduce this in the latest 3.x releases. Hence closing the issue.

**Closed by dushaniw** 2020-11-10 06:58 UTC
Labels: 2.1.0, Type/Bug
