### ISSUE TITLE
[UX] No clear difference between read only and editable fields

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#2917] opened 2018-03-07 12:09 UTC
**Description:**
$subject
![readonly](https://user-images.githubusercontent.com/6497326/37091482-571a0f68-222e-11e8-8c9a-4dd4b63ed8c9.png)

**Suggested Labels:**
improvement 

**Affected Product Version:**
2.1.0

**Steps to reproduce:**
1. log into carbon console
2. goto configure-> Multitenancy->view tenants-> click on edit
3. there are non-editable (read-only) fields as well as editable fields but its hard to recognize the difference

Suggestion
![readonly2](https://user-images.githubusercontent.com/6497326/37091526-811f9792-222e-11e8-9642-9cb6e040474f.png)

**Comment by rmsamitha** [comment] 2022-01-28 04:35
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:35 UTC
Labels: Priority/Low, Affected/2.1.0
