### ISSUE TITLE
Observed error logs after creating tenants using admin services.

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2379] opened 2018-01-12 08:47 UTC
OS: Ubuntu 16.04
JDK: 1.8.0_144

Steps
1. Create a jmeter script that creates three tenants consecutively using the admin service. 

After the tenant creation following logs are observed in the console even though the tenant creation is successful. These errors signify a 401. It would be great if an explanation is provided for this

```
[2018-01-12 12:41:40,052]  INFO - CarbonAuthenticationUtil 'jane@finance.abc.com [2]' logged in at [2018-01-12 12:41:40,052+0530]
[2018-01-12 12:41:40,095]  INFO - TenantAxisConfigurator Creating tenant AxisConfiguration for tenant: finance.abc.com[2]
[2018-01-12 12:41:40,134]  INFO - UserStoreConfigurationDeployer User Store Configuration Deployer initiated.
[2018-01-12 12:41:40,135]  INFO - UserStoreConfigurationDeployer User Store Configuration Deployer initiated.
[2018-01-12 12:41:40,288]  INFO - PermissionUpdater Permission cache updated for tenant 2
[2018-01-12 12:41:40,289]  INFO - TenantServiceCreator Initializing APIM TenantServiceCreator for the tenant domain : finance.abc.com
[2018-01-12 12:41:40,309]  INFO - CarbonAuthenticationUtil 'jane@core.abc.com [3]' logged in at [2018-01-12 12:41:40,309+0530]
[2018-01-12 12:41:40,322]  INFO - TenantAxisConfigurator Creating tenant AxisConfiguration for tenant: core.abc.com[3]
[2018-01-12 12:41:40,363]  INFO - UserStoreConfigurationDeployer User Store Configuration Deployer initiated.
[2018-01-12 12:41:40,364]  INFO - UserStoreConfigurationDeployer User Store Configuration Deployer initiated.
[2018-01-12 12:41:40,568]  INFO - CarbonAuthenticationUtil 'jane@operations.abc.com [4]' logged in at [2018-01-12 12:41:40,568+0530]
[2018-01-12 12:41:40,570]  INFO - PermissionUpdater Permission cache updated for tenant 3
[2018-01-12 12:41:40,570]  INFO - TenantServiceCreator Initializing APIM TenantServiceCreator for the tenant domain : core.abc.com
[2018-01-12 12:41:40,582]  INFO - TenantAxisConfigurator Creating tenant AxisConfiguration for tenant: operations.abc.com[4]
[2018-01-12 12:41:40,660]  INFO - UserStoreConfigurationDeployer User Store Configuration Deployer initiated.
[2018-01-12 12:41:40,661]  INFO - UserStoreConfigurationDeployer User Store Configuration Deployer initiated.
[2018-01-12 12:41:40,843]  INFO - CarbonAuthenticationUtil 'Administrator@carbon.super [-1234]' logged in at [2018-01-12 12:41:40,843+0530]
[2018-01-12 12:41:40,883]  INFO - CarbonAuthenticationUtil 'Administrator@carbon.super [-1234]' logged in at [2018-01-12 12:41:40,883+0530]
[2018-01-12 12:41:41,019]  INFO - PermissionUpdater Permission cache updated for tenant 4
[2018-01-12 12:41:41,019]  INFO - TenantServiceCreator Initializing APIM TenantServiceCreator for the tenant domain : operations.abc.com
[2018-01-12 12:41:41,065]  INFO - CarbonPolicyFinder Initializing of policy store is started at :  Fri Jan 12 12:41:41 IST 2018
[2018-01-12 12:41:41,069]  INFO - DefaultPolicyDataStore Using Global policy combining algorithm that is defined in configuration file.
[2018-01-12 12:41:41,069]  INFO - CarbonPolicyFinder Start retrieving policies from org.wso2.carbon.identity.entitlement.policy.store.RegistryPolicyStoreManageModule@15161998 at : Fri Jan 12 12:41:41 IST 2018
[2018-01-12 12:41:41,070]  INFO - CarbonPolicyFinder Finish retrieving policies from org.wso2.carbon.identity.entitlement.policy.store.RegistryPolicyStoreManageModule@15161998 at : Fri Jan 12 12:41:41 IST 2018
[2018-01-12 12:41:41,070]  INFO - CarbonPolicyFinder Initializing of policy store is finished at :  Fri Jan 12 12:41:41 IST 2018
[2018-01-12 12:41:41,075]  INFO - CarbonPolicyFinder Initializing of policy store is started at :  Fri Jan 12 12:41:41 IST 2018
[2018-01-12 12:41:41,090]  INFO - DefaultPolicyDataStore Using Global policy combining algorithm that is defined in configuration file.
[2018-01-12 12:41:41,091]  INFO - CarbonPolicyFinder Start retrieving policies from org.wso2.carbon.identity.entitlement.policy.store.RegistryPolicyStoreManageModule@15161998 at : Fri Jan 12 12:41:41 IST 2018
[2018-01-12 12:41:41,093]  INFO - CarbonPolicyFinder Finish retrieving policies from org.wso2.carbon.identity.entitlement.policy.store.RegistryPolicyStoreManageModule@15161998 at : Fri Jan 12 12:41:41 IST 2018
[2018-01-12 12:41:41,095]  INFO - CarbonPolicyFinder Initializing of policy store is finished at :  Fri Jan 12 12:41:41 IST 2018
[2018-01-12 12:41:42,362]  INFO - CarbonAuthenticationUtil 'Administrator@carbon.super [-1234]' logged in at [2018-01-12 12:41:42,362+0530]
[2018-01-12 12:41:42,363]  INFO - CarbonAuthenticationUtil 'Administrator@carbon.super [-1234]' logged in at [2018-01-12 12:41:42,363+0530]
[2018-01-12 12:41:42,426]  INFO - CarbonAuthenticationUtil 'Administrator@carbon.super [-1234]' logged in at [2018-01-12 12:41:42,426+0530]
[2018-01-12 12:41:42,561]  WARN - AuthenticationHandler Illegal access attempt at [2018-01-12 12:41:42,0561] from IP address 127.0.0.1 while trying to authenticate access to service EventProcessorAdminService
[2018-01-12 12:41:42,570]  INFO - HTTPSender Unable to sendViaPost to url[https://localhost:9443/services/EventProcessorAdminService]
org.apache.axis2.AxisFault: Transport error: 401 Error: Unauthorized
	at org.apache.axis2.transport.http.HTTPSender.handleResponse(HTTPSender.java:328)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:196)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:77)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:451)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:278)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:430)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.wso2.carbon.event.processor.stub.EventProcessorAdminServiceStub.deployExecutionPlan(EventProcessorAdminServiceStub.java:2646)
	at org.wso2.carbon.apimgt.impl.throttling.GlobalThrottleEngineClient.deploy(GlobalThrottleEngineClient.java:130)
	at org.wso2.carbon.apimgt.impl.throttling.GlobalThrottleEngineClient.deployExecutionPlan(GlobalThrottleEngineClient.java:169)
	at org.wso2.carbon.apimgt.impl.ThrottlePolicyDeploymentManager.deployPolicyToGlobalCEP(ThrottlePolicyDeploymentManager.java:66)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.addDefaultTenantAdvancedThrottlePolicies(APIUtil.java:6201)
	at org.wso2.carbon.apimgt.impl.observers.CommonConfigDeployer$1.run(CommonConfigDeployer.java:65)
	at java.lang.Thread.run(Thread.java:748)
[2018-01-12 12:41:42,584]  WARN - AuthenticationHandler Illegal access attempt at [2018-01-12 12:41:42,0584] from IP address 127.0.0.1 while trying to authenticate access to service EventProcessorAdminService
[2018-01-12 12:41:42,601]  INFO - EventProcessorConfigurationFilesystemInvoker Execution plan: operations.abc.com_app_50PerMin saved in the filesystem
[2018-01-12 12:41:42,597]  INFO - HTTPSender Unable to sendViaPost to url[https://localhost:9443/services/EventProcessorAdminService]
org.apache.axis2.AxisFault: Transport error: 401 Error: Unauthorized
	at org.apache.axis2.transport.http.HTTPSender.handleResponse(HTTPSender.java:328)
	at org.apache.axis2.transport.http.HTTPSender.sendViaPost(HTTPSender.java:196)
	at org.apache.axis2.transport.http.HTTPSender.send(HTTPSender.java:77)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.writeMessageWithCommons(CommonsHTTPTransportSender.java:451)
	at org.apache.axis2.transport.http.CommonsHTTPTransportSender.invoke(CommonsHTTPTransportSender.java:278)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:430)
	at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225)
	at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149)
	at org.wso2.carbon.event.processor.stub.EventProcessorAdminServiceStub.deployExecutionPlan(EventProcessorAdminServiceStub.java:2646)
	at org.wso2.carbon.apimgt.impl.throttling.GlobalThrottleEngineClient.deploy(GlobalThrottleEngineClient.java:130)
	at org.wso2.carbon.apimgt.impl.throttling.GlobalThrottleEngineClient.deployExecutionPlan(GlobalThrottleEngineClient.java:169)
	at org.wso2.carbon.apimgt.impl.ThrottlePolicyDeploymentManager.deployPolicyToGlobalCEP(ThrottlePolicyDeploymentManager.java:66)
	at org.wso2.carbon.apimgt.impl.utils.APIUtil.addDefaultTenantAdvancedThrottlePolicies(APIUtil.java:6201)
	at org.wso2.carbon.apimgt.impl.observers.CommonConfigDeployer$1.run(CommonConfigDeployer.java:65)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by chamindias** [comment] 2018-02-23 12:16
According to the logs, you are creating multiple tenants within 1 second right? Are you trying to login using super tenant admin? Please do provide the exact scenario in detail (or the jmeter script) to reproduce the issue. Eg - Who is trying to log into which domain etc.
Reducing the priority due to insufficient details.

**Comment by kavishkafernando** [comment] 2020-11-26 04:05
@erandidesilva any feedback on this?

**Comment by kavishkafernando** [comment] 2020-11-26 04:07
Closing the issue for now due to insufficient information. Please re-open the issue with more information.

**Closed by kavishkafernando** 2020-11-26 04:07 UTC
Labels: 2.2.0, Priority/Normal, Type/Bug, Type/Question
