### ISSUE TITLE
No message termination in Sending requests more than the application quota

### ISSUE THREAD

**Issue by amir-dh** [wso2/product-apim#7950] opened 2020-04-25 05:08 UTC
### Description:
I am using the APIM version 3.0.0
when testing the rate limit, reached the problem for application quota:
I created the application tier with 100 requests per minute and set in the API and set the credentials of API.
but when tested the API with the Vegeta tool. I could send 200 requests with the same application And there was no limit controlling at 100 per minute rate. How can we fix this issue?

### Affected Product Version:
API Manager v3.0.0

### Environment details (with versions):
- OS: Ubuntu 19.10
- Client: Ubuntu 19.10
- Env (Docker/K8s):

---

**Comment by Sarangan0219** [comment] 2020-05-04 05:45
This is not reproducible in APIM 3.0.0

Created an application tier with 5PerMin and assigned it to an application. It throws  the below given error and blocks the subsequent requests.
```
<amt:fault xmlns:amt="http://wso2.org/apimanager/throttling">
    <amt:code>900803</amt:code>
    <amt:message>Message throttled out</amt:message>
    <amt:description>You have exceeded your quota</amt:description>
    <amt:nextAccessTime>2020-May-04 05:43:00+0000 UTC</amt:nextAccessTime>
</amt:fault>
```

**Comment by tmkasun** [comment] 2020-08-28 16:17
Closing the issue since we couldn't reproduce the issue. Feel free to reopen the issue if you need further clarification.

**Closed by tmkasun** 2020-08-28 16:17 UTC
Labels: Priority/Normal, Resolution/Cannot Reproduce, Type/Bug
