### ISSUE TITLE
Better if API Throttled Out Requests Report on publisher provide to filter by version

### ISSUE THREAD

**Issue by shavantha** [wso2/product-apim#2803] opened 2018-02-26 08:22 UTC
**Description:**
Better if users can view API Throttled Out Requests by version of API. Multiple versions of the same API may have different throttler counts the API designer may want to view

api throttled out requests
![throttleout](https://user-images.githubusercontent.com/6552100/36660536-79dc3fd0-1afe-11e8-8658-96267dceb768.png)

**Affected Product Version:**
1.APIM-2.10

**OS, DB, other environment details and versions:**    
1.Frehspack with data

**Steps to reproduce:**
1.Check the  API Throttled Out Requests Report. Note: there can be multiple versions of the API so would be useful to view throttle out based on verion

**Related Issues:**

**Comment by rmsamitha** [comment] 2022-01-28 04:50
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:50 UTC
Labels: Affected/2.1.0
