### ISSUE TITLE
[UX] Maintain same consistency for the execution policy as default limits

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3150] opened 2018-04-02 00:16 UTC
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Consistency and standard -Is flow maintain the same patterns and consistency?

***Related task:***
Add advanced throttling policy

***Issue:***
As the execution policy and default limits have the same structure need to maintain consistency in both sections. 
Need to remove the request count label and change the dropdown to radio buttons

**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.2.0

**Comment by rmsamitha** [comment] 2022-01-28 04:20
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:20 UTC
Labels: Priority/Low, Affected/2.1.0, Affected/2.2.0
