### ISSUE TITLE
Special characters in username and password

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/product-apim#7171] opened 2019-12-19 08:46 UTC
**version**
3.0.0

**Steps to reproduce**
1. Setup username "<name" as super_admin username as below [1].

```
[super_admin]
username = "<![CDATA[<name]]>"
password = "password"
create_admin_account = true

[apim.throttling.jms]
username = "%3Cname"
password = "password"
```
2. login to publisher with above credentials.
3. Error - `The server could not verify that you are authorized to access the requested resource.`.

**Query**
Provide restricted character list and expected formats for username and password.

[1] https://apim.docs.wso2.com/en/latest/Administer/ProductSecurity/LoginsAndPasswords/maintaining-logins-and-passwords/#changing-the-super-admin-credentials

**Comment by Krishanx92** [comment] 2020-01-09 12:41
tagging: https://github.com/wso2/product-apim/issues/7228

**Comment by Meruja** [comment] 2020-06-16 08:51
The given configuration has been applied in 3.2.0-alpha and try to login to the publisher.
The error does not exist in 3.2.0-alpha and I could able to log in.

**Comment by Arshardh** [comment] 2020-06-23 06:27
Closing this issue since this cannot be reproduced in the latest pack

**Closed by Arshardh** 2020-06-23 06:27 UTC
Labels: Affected/3.0.0, Priority/Highest, Type/Improvement
