### ISSUE TITLE
Error displayed while reloading Publisher

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10840] opened 2021-04-08 05:53 UTC
### Description:
An error message _"Error while loading the APIs_" is displayed if the user doesn't use the publisher for while and then tries to reload the page.

<img width="1680" alt="Screen Shot 2021-04-08 at 11 14 59 AM" src="https://user-images.githubusercontent.com/32265029/113974790-2039bc80-985c-11eb-85ab-1f930a962a16.png">

### Steps to reproduce:

- Log in to the publisher
- Wait 5 minutes
- Click on API Manager Publisher Banner

### Affected Product Version:
API-M 4.0.0-beta

### Environment details (with versions):
- OS: ios
- Browser: Chrome
- 
---
#### Suggested Labels:
API-M 4.0.0

**Comment by malinthaprasan** [comment] 2021-04-10 08:31
What is the username used to login?

**Comment by TheRasanjana** [comment] 2021-04-10 11:03
Observed in our beta distributed setup.

**Comment by npamudika** [comment] 2021-04-11 08:12
Tried in the distributed setup and locally, but couldn't reproduce the issue. Hence closing this.

**Closed by npamudika** 2021-04-11 08:12 UTC
Labels: API-M 4.0.0, Priority/Normal, React-UI, Type/Bug
