### ISSUE TITLE
[UX] [APIM] API create Upload error message not clearly positioned

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#3094] opened 2018-03-16 09:21 UTC
**Description:**
$subject
![screenshot-2018-3-16 api publisher - add rest api](https://user-images.githubusercontent.com/6497326/37512941-7bc45312-2929-11e8-8041-ac485cd9d480.png)

**Suggested Labels:**
bug

**Affected Product Version:**
2.1.0 update 14

**OS, DB, other environment details and versions:**    
MacOS High sierra/ Chrome 64

**Comment by rmsamitha** [comment] 2022-01-28 04:25
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:25 UTC
Labels: Affected/2.1.0
