### ISSUE TITLE
Delay in loading custom application attribute in application edit view

### ISSUE THREAD

**Issue by msm1992** [wso2/product-apim#6675] opened 2019-10-25 06:12 UTC
![WSO2-APIM-Developer-Portal](https://user-images.githubusercontent.com/28379317/67547290-504ed780-f71c-11e9-9d71-d2d85f0ef74d.gif)

**Comment by Krishanx92** [comment] 2020-01-13 04:40
Duplicate of https://github.com/wso2/product-apim/issues/6675 hence closing the issue

**Closed by Krishanx92** 2020-01-13 04:40 UTC
Labels: 3.0.0, 3.1.0, Priority/Low, Severity/Minor, Store, Type/React-UI, UI-Performance
