### ISSUE TITLE
API Manager 3.0.0 - Changing scope for resource works only after server restart

### ISSUE THREAD

**Issue by igkononov** [wso2/product-apim#6943] opened 2019-11-25 14:45 UTC
Hi,

Please, help me with this problem.

On previous steps I published new API in Publisher, created new application in DevPortal and made subscription for created API.

Description of problem:
After this, I changed scope for one resource in my API. But after saving changes I keep have possibility to get access for my resource without any restrictions. Re-subscription for API in application doesn't help.
New scope begins his work only after restarting API Manager.

There is the same problem in flow when I try to remove scope.

Please, can you explain, is it a bug?
I'm not sure that I need to restart API Manager every time, when I need to change scope.

Thanks in advance.

**Comment by tmkasun** [comment] 2019-11-26 16:28
Hi @igkononov ,

I tried to reproduce this issue in APIM 3.0.0, But couldn't reproduce the issue.
What I did was,

- Create roles named `role1` and `role2`
- Create API and subscribe to it from devportal
- change resource scope from the publisher and assign a scope which is allowed to `role1`
![image](https://user-images.githubusercontent.com/3313885/69652280-6c38f680-1097-11ea-86e9-0a0416636e7b.png)

- Generate a JWT access token from dev portal api credentials page
- Used that JWT token in swagger try out console
- I got the token error when trying to access the API with a JWT token that doesn't have required scopes
![image](https://user-images.githubusercontent.com/3313885/69652355-8a065b80-1097-11ea-97ac-6757cd19e1ee.png)


Could you please provide more information to reproduce your issue? Or is there any difference in my steps with yours ?

**Comment by igkononov** [comment] 2019-11-26 16:31
I created scope after I'd published API

**Comment by igkononov** [comment] 2019-12-09 10:55
Are there any updates on this question?

**Comment by tmkasun** [comment] 2020-01-17 10:05
Hi @igkononov,

Sorry about the delay in reply, Yes this is expected behavior due to caching in key manager (OAuth cache). You need to wait till the cache invalidate(default max: 15mins) or restart the gateway nodes to make this changes effected.

**Comment by tmkasun** [comment] 2020-01-17 10:06
Hope the above comment provides the answer to your concern, Closing this issue, for now, Feel free to reopen the issue if you need further clarification.

**Closed by tmkasun** 2020-01-17 10:06 UTC
Labels: 3.0.0, Type/Question
