### ISSUE TITLE
GraphQL API execution with Try out failed

### ISSUE THREAD

**Issue by Shehanir** [wso2/product-apim#7503] opened 2020-02-18 15:53 UTC
### Description:
API execution returns error response when try out with tryout editor and when execute the same with curl command appears in the editor. 
The same query works with direct endpoint [https://api.graph.cool/simple/v1/swapi](url)

Erro logr:
GraphQLAPIHandler Invalid Syntax : offending token 'string' at line 1 column 1

When try to execute the API with tryout editor it gives error response as follows:
<img width="1440" alt="test1" src="https://user-images.githubusercontent.com/47380804/74751901-ed1d1e00-5293-11ea-990f-09cc59c445cf.png">

When trying to execute with the curl the same error response received. 
<img width="1440" alt="test3" src="https://user-images.githubusercontent.com/47380804/74751948-fc9c6700-5293-11ea-9c9f-b2829529dde5.png">

When inspecting the curl it seems that the payload is not updated according to the payload we entered in the payload body. It keeps the sample payload provided in the payload body.

The sample payload provided in the payload body : 
<img width="1440" alt="test4" src="https://user-images.githubusercontent.com/47380804/74752001-0cb44680-5294-11ea-9dc1-d000e3c65234.png">

The curl command after changing the payload body:
<img width="1440" alt="test2" src="https://user-images.githubusercontent.com/47380804/74752030-19389f00-5294-11ea-9ae1-259b4b4acb61.png">

As shown in above screenshot, the API execution fails since the payload did not update as we updates it in the UI. Hence the API execution fails with "invalid query" error. 

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by menakaj** [comment] 2020-02-25 07:03
Duplicate of https://github.com/wso2/product-apim/issues/7336

**Closed by menakaj** 2020-02-25 07:03 UTC
Labels: Priority/Highest, Type/Bug
