### ISSUE TITLE
[UX][publisher] API rating can  be added by the user who doesn't have subscription permission to that API

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#3092] opened 2018-03-16 09:03 UTC
**Description:**
$subject. 

**Suggested Labels:**
Bug

**Affected Product Version:**
2.1.0 update 14

**OS, DB, other environment details and versions:**    
MacOS High sierra

**Comment by rmsamitha** [comment] 2022-01-28 04:26
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:26 UTC
Labels: Affected/2.1.0
