### ISSUE TITLE
Editing subscription rate limit is giving empty fields in admin portal

### ISSUE THREAD

**Issue by chanikag** [wso2/product-apim#10095] opened 2021-03-03 07:05 UTC
### Description:
The edit function of subscription rate limit is not working. All the existing fields are empty. 

### Steps to reproduce:

1. Login to the admin portal
2. Edit an existing subscription policy.

<img width="1281" alt="Screen Shot 2021-03-03 at 12 16 35 PM" src="https://user-images.githubusercontent.com/6702569/109765220-91150580-7c1a-11eb-89ed-5eb7937cee65.png">

3. The fields are empty.
<img width="1340" alt="Screen Shot 2021-03-03 at 12 17 01 PM" src="https://user-images.githubusercontent.com/6702569/109765221-91150580-7c1a-11eb-9d90-38b808d59baa.png">

### Affected Product Version:
APIM 4.0.0 Alpha
### Environment details (with versions):
- OS: Mac

**Comment by sachithKay** [comment] 2021-03-08 07:13
This issue seems to be caused by some inconsistent state during setting roles.
AddEdit.jsx?4801:239 Uncaught (in promise) TypeError: Cannot read property 'roles' of null.
This has been introduced in https://github.com/sachithKay/carbon-apimgt/commit/c6f62e8fc74b7ee27f3c26f7d78158e3b2e0ce81.

**Comment by kavishkafernando** [comment] 2021-03-19 08:02
Has been fixed with https://github.com/chanaka3d/carbon-apimgt/commit/98189502cdd82fcb5eea953580ea232ded6f1c22

**Closed by kavishkafernando** 2021-03-19 08:02 UTC
Labels: API-M 4.0.0, Priority/High, Severity/Critical, Type/Bug, Type/React-UI
