### ISSUE TITLE
Cant publish API from tenant user

### ISSUE THREAD

**Issue by praminda** [wso2/product-apim#8247] opened 2020-06-04 07:25 UTC
### Description:

Newly created tenant user can't create an API till tenant admin logs in or a server restart. When trying to deploy the API following error gets thrown.
```
[2020-05-21 19:51:47,028] ERROR - ApisApiServiceImpl Error while adding new API : null-PizzaShackAPI-1.0.0 - Error while performing registry transaction operation
org.wso2.carbon.apimgt.api.APIManagementException: Error while performing registry transaction operation
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.handleException_aroundBody124(AbstractAPIManager.java:1835) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.handleException(AbstractAPIManager.java:1833) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.createAPI_aroundBody154(APIProviderImpl.java:3573) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.createAPI(APIProviderImpl.java:3485) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPI_aroundBody46(APIProviderImpl.java:814) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPI(APIProviderImpl.java:782) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addAPI_aroundBody0(UserAwareAPIProvider.java:64) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addAPI(UserAwareAPIProvider.java:62) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.apisPost(ApisApiServiceImpl.java:270) [classes/:?]
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.apisPost(ApisApi.java:904) [classes/:?]
...
...
...
Caused by: org.wso2.carbon.registry.core.exceptions.RegistryException: Unable to put resource Failed to add new resource. User pub does not have authorization to update the collection /_system/governance/apimgt/applicationdata.
	at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:299) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2505) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.put(UserDefinedHandlerManager.java:204) ~[org.wso2.carbon.registry.core_4.6.0.jar:?]
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:950) 
	at org.wso2.carbon.governance.api.generic.GenericArtifactManager.addGenericArtifact(GenericArtifactManager.java:208) ~[org.wso2.carbon.governance.api_4.8.14.jar:?]
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.createAPI_aroundBody154(APIProviderImpl.java:3515) ~[org.wso2.carbon.apimgt.impl_6.6.163.jar:?]
	... 59 m
```

### Steps to reproduce:
1. Create a tenant user with creator/publisher roles.
1. Login to publisher using new tenant user.
1. Try to deploy sample API.
1. There will be an error

### Affected Product Version:

3.1.0

### Environment details (with versions):
- OS: Mac
- Client:
- Env (Docker/K8s):

**Comment by CrowleyRajapakse** [comment] 2020-06-16 05:56
Can't reproduce

**Comment by praminda** [comment] 2020-06-16 06:06
Didn't try on master. I guess then this is only reproducible in 310

**Comment by CrowleyRajapakse** [comment] 2020-06-16 06:09
Ack, thanks

**Comment by uvindra** [comment] 2020-07-01 05:39
This is reproduced in master branch as well

```
ApisApiServiceImpl  Error while adding new API : null-one-1.0.0 - Error while performing registry transaction operation
org.wso2.carbon.apimgt.api.APIManagementException: Error while performing registry transaction operation
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.handleException_aroundBody132(AbstractAPIManager.java:1869)
	at org.wso2.carbon.apimgt.impl.AbstractAPIManager.handleException(AbstractAPIManager.java:1868)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.createAPI_aroundBody172(APIProviderImpl.java:3884)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.createAPI(APIProviderImpl.java:3797)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPI_aroundBody46(APIProviderImpl.java:832)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.addAPI(APIProviderImpl.java:800)
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addAPI_aroundBody0(UserAwareAPIProvider.java:83)
	at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.addAPI(UserAwareAPIProvider.java:81)
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.ApisApiServiceImpl.apisPost(ApisApiServiceImpl.java:288)
	at org.wso2.carbon.apimgt.rest.api.publisher.v1.ApisApi.apisPost(ApisApi.java:962)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:75)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:119)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.governance.api.exception.GovernanceException: Failed to add artifact: artifact id: 1c6f2225-383d-4051-bd67-40e55e82516b. Unable to put resource Failed to add new resource. User creator does not have authorization to update the collection /_system/governance/apimgt/applicationdata/provider/creator-AT-test.com.
	at org.wso2.carbon.governance.api.common.GovernanceArtifactManager.addGovernanceArtifact(GovernanceArtifactManager.java:252)
	at org.wso2.carbon.governance.api.generic.GenericArtifactManager.addGenericArtifact(GenericArtifactManager.java:208)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.createAPI_aroundBody172(APIProviderImpl.java:3826)
	... 59 more
Caused by: org.wso2.carbon.registry.core.exceptions.RegistryException: Unable to put resource Failed to add new resource. User creator does not have authorization to update the collection /_system/governance/apimgt/applicationdata/provider/creator-AT-test.com.
	at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:299)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2505)
	at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.put(UserDefinedHandlerManager.java:204)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:950)
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:705)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.put(CacheBackedRegistry.java:591)
	at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840)
	at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:73)
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:816)
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:813)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:813)
	at org.wso2.carbon.governance.api.common.GovernanceArtifactManager.addGovernanceArtifact(GovernanceArtifactManager.java:221)
	at org.wso2.carbon.governance.api.generic.GenericArtifactManager.addGenericArtifact(GenericArtifactManager.java:208)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.createAPI_aroundBody172(APIProviderImpl.java:3826)
	... 59 more
Caused by: org.wso2.carbon.registry.core.exceptions.RegistryException: Failed to add new resource. User creator does not have authorization to update the collection /_system/governance/apimgt/applicationdata/provider/creator-AT-test.com.
	at org.wso2.carbon.registry.core.jdbc.Repository.addEmptyCollection(Repository.java:1167)
	at org.wso2.carbon.registry.core.jdbc.Repository.addEmptyCollection(Repository.java:1156)
	at org.wso2.carbon.registry.core.jdbc.Repository.add(Repository.java:1013)
	at org.wso2.carbon.registry.core.jdbc.Repository.put(Repository.java:305)
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:717)
	at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840)
	at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:73)
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:816)
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:813)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:813)
	at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.put(MountHandler.java:292)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.put(HandlerManager.java:2505)
	at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.put(UserDefinedHandlerManager.java:204)
	at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.put(HandlerLifecycleManager.java:950)
	at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.put(EmbeddedRegistry.java:705)
	at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.put(CacheBackedRegistry.java:591)
	at org.wso2.carbon.registry.core.session.UserRegistry.putInternal(UserRegistry.java:840)
	at org.wso2.carbon.registry.core.session.UserRegistry.access$1000(UserRegistry.java:73)
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:816)
	at org.wso2.carbon.registry.core.session.UserRegistry$11.run(UserRegistry.java:813)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wso2.carbon.registry.core.session.UserRegistry.put(UserRegistry.java:813)
	at org.wso2.carbon.governance.api.common.GovernanceArtifactManager.addGovernanceArtifact(GovernanceArtifactManager.java:221)
	at org.wso2.carbon.governance.api.generic.GenericArtifactManager.addGenericArtifact(GenericArtifactManager.java:208)
	at org.wso2.carbon.apimgt.impl.APIProviderImpl.createAPI_aroundBody172(APIProviderImpl.java:3826)
	... 59 more
```

**Comment by uvindra** [comment] 2020-07-01 05:51
This seems to happen intermittently from time to time. Not sure of the cause.

**Comment by uvindra** [comment] 2020-07-01 06:05
This seems to be related to https://github.com/wso2/product-apim/issues/7816

**Comment by HiranyaKavishani** [comment] 2020-10-19 06:52
Close the issue as per the above commit

**Closed by HiranyaKavishani** 2020-10-19 06:52 UTC
Labels: Affected/3.1.0, Priority/High, Type/Bug
