### ISSUE TITLE
Error occurred while uploading .pdf files through the publisher portal

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-apim#9155] opened 2020-08-21 04:28 UTC
### Description:
The file is uploaded successfully but showing error 'Error uploading the file' in the UI.

### Steps to reproduce:
1. Create API.
2. try to upload docs (.pdf) through the publisher.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by tmkasun** [comment] 2020-09-25 17:43
Can't reproduce this issue in the latest master branch, I was able to upload and attach a PDF file to an API without any error 

![image](https://user-images.githubusercontent.com/3313885/94299026-b2dfd180-ff84-11ea-81c8-df89566a095a.png)

hence closing the issue

**Closed by tmkasun** 2020-09-25 17:43 UTC
Labels: Priority/Normal, Type/Bug
