### ISSUE TITLE
[Publisher] API calls fails due to invalid token parts mix-up during token refresh 

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#3231] opened 2018-04-19 14:17 UTC
**Description:**
- When working with Publisher app, If the access token is about to expire, We perform a [refreshTokenOnExpire](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/AuthManager.js#L40) call when a token expirery time drops below a predefined time difference, The token refresh call is made throgh the SwaggerJS interceptors ([APIClient.js#L131](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/source/src/app/data/APIClient.js#L131)), Until the SwaggerJS [Swagger-Client 3.6.0](https://github.com/swagger-api/swagger-js/releases/tag/v3.6.0) , Interceptors doson't accept asynchronus method calls hence SwaggerJS didn't wait for the Token Refresh call to be completed.
- Because of the asynchronus call to refresh the acess token , Intermitently API calls fails with invalid access token error , when the API calls made just after invoking the token refresh call in the interceptor.
- As of SwaggerJS [Swagger-Client 3.6.0](https://github.com/swagger-api/swagger-js/releases/tag/v3.6.0) , It supports promise as the return value from an interceptor so that it will wait for the Token refresh call to be resolved.
- To fix the issue we could update[package.json#L43](https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/package.json#L43) the SwaggerJs version and return a promise in the token refresh on expire method

**Affected Product Version:**
- APIM 3.0.0-m27

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
-  Reduce the access token validity perdiod to below 60 seconds
- Login to the publisher app and perform some actions which cause REST API calls
- Eventually you will get an 401 network error due to invalid acess token

**Related Issues:**
- N/A

**Comment by ruks** [comment] 2019-10-16 03:49
this is already fixed and cannot reproduce. Hence closing.

**Closed by ruks** 2019-10-16 03:49 UTC
Labels: 3.0.0, Type/Bug, Type/UX
