### ISSUE TITLE
Abnormal API Usage Alert template config name is confusing

### ISSUE THREAD

**Issue by tharikaGitHub** [wso2/product-apim#2685] opened 2018-02-06 04:12 UTC
**Description:**

For AbnormalTierUsageAlert we have used the term Abnormal API Usage in documentation as well as at some places of the code level. This should be changed to Abnormal Tier Usage in order to reduce the confusion.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.0.0, 2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rmsamitha** [comment] 2022-01-28 04:52
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:52 UTC
Labels: Priority/Normal
