### ISSUE TITLE
[APIM3]  Can't get an access token using refresh grant type

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#3634] opened 2018-08-27 12:59 UTC
**Description:**
Can't generate an access token using refresh grant type , following curl
```curl
curl -vk 'https://localhost:9443/login/token/publisher' -H 'Origin: https://localhost:9443' -H 'Authorization: Bearer i_awS8PzXqkeMSrOFtaGJ' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: application/json' -H 'Referer: https://localhost:9443/publisher/apis' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36' -H 'X-Alt-Referer: null' -H 'DNT: 1' --data 'grant_type=refresh_token&validity_period=-1&scopes=apim%3Aapi_view%20apim%3Aapi_create%20apim%3Aapi_publish%20apim%3Atier_view%20apim%3Atier_manage%20apim%3Asubscription_view%20apim%3Asubscription_block%20apim%3Asubscribe%20apim%3Aexternal_services_discover' --compressed
```

fails with error `ERROR {org.wso2.carbon.auth.oauth.impl.RefreshGrantHandler} - Refresh token is expired.`
- Resopnse contains 
```javascript
{"status":"INTERNAL_SERVER_ERROR"}
```

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Get access token using password grant
- Use its refresh token with refresh grant to generate access toke
- refresh_grant token request will fail with the error `ERROR {org.wso2.carbon.auth.oauth.impl.RefreshGrantHandler} - Refresh token is expired.`
- Resopnse contains 
```javascript
{"status":"INTERNAL_SERVER_ERROR"}
```

**Related Issues:**

**Comment by CrowleyRajapakse** [comment] 2019-01-24 11:31
This issue doesn't seem to exist in the carbon.apimgt.version 7.0.242, carbon.auth.version 1.0.58 and product.apim 3.0-Master 

The curl command which I have used to get the access token from refresh token,

`curl -k -v -d "refresh_token=ofHaGoE3NoztWUk0e8vxu5zkI77BBUW-WI0s0i0cQCk&grant_type=refresh_token&validity_period=3600&scope=apim:api_view" -H "Authorization: Basic OWI1OGUzOWEtN2I3Ny00NWY0LTgxYTMtZTE5NDk0YzI1NTI0OmEzNjg5OWQxLTYwOGYtNDU2Zi05OWY5LTdjZTBlMDgyMDUzMg==" https://10.100.7.106:9443/api/auth/oauth2/v1.0/token`

And, with the response of,

`
{"access_token":"M7C0wlscAEszZZH58eca2vcyPxmDv0v_mbK9QOfBKTI","token_type":"Bearer","expires_in":3600,"refresh_token":"xZGlzzWl6tJqU6Wp_c4m0uCTu2cVkhRO3Gp5RDfqheQ","scope":"default"}
`

**Comment by ruks** [comment] 2019-10-16 03:48
this is already fixed and cannot reproduce. Hence closing.

**Closed by ruks** 2019-10-16 03:48 UTC
Labels: 3.0.0, Type/Bug
