### ISSUE TITLE
Order of the json attributes gets altered when swagger is updated

### ISSUE THREAD

**Issue by mmmAlthaf** [wso2/product-apim#11084] opened 2021-04-20 10:28 UTC
### Description:
After updating the swagger definition via the REST API the resources defined in the swagger become out of order.

### Steps to reproduce:
- Create API with ordered resources through the UI (the swagger definition 'orig.json' attached was used to create)
- Get swagger definition of created API via the REST API to verify that everything is fine so far
- Send request to update the swagger definition by changing something trivial (I changed API title and spelling change to one path to resource. ./acounts -> /accounts)
- Compare the request definition and response definition in the Swagger Editor preview (see attached UpdateRequestPayload.pdf and AfterUpdateResponse.pdf)

### Affected Product Version:
2.6.0

[orig.txt](https://github.com/wso2/product-apim/files/6342717/orig.txt)

**Comment by mmmAlthaf** [comment] 2021-04-20 11:20
[AfterUpdateResponse.pdf](https://github.com/wso2/product-apim/files/6343066/AfterUpdateResponse.pdf)
[UpdateRequestPayload.pdf](https://github.com/wso2/product-apim/files/6343070/UpdateRequestPayload.pdf)

**Comment by npamudika** [comment] 2021-07-06 14:18
Resolving this as the issue is not reproducible in the public branch.

**Closed by npamudika** 2021-07-06 14:18 UTC
Labels: Priority/Normal, Type/Bug
