### ISSUE TITLE
Error Log getting printed when API invocation

### ISSUE THREAD

**Issue by ChamNDeSilva** [wso2/product-apim#2795] opened 2018-02-23 04:21 UTC
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
AP Manager 2.1.0-update11

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
This is reproducible after synapse version upgrade.
1. Create an API
2. Publish it
3. generate keys
4. Invoke the API.

The expected response getting passed to the REST Client properly.
But following error log getting printed in the server logs.
**ERROR - ServerWorker Error while building message for REST_URL request**

Need to aviod this.

**Related Issues:**

**Comment by bhathiya** [comment] 2018-02-26 08:37
Duplicate of https://github.com/wso2/product-apim/issues/2762

**Closed by bhathiya** 2018-02-26 08:37 UTC
Labels: 2.2.0, Priority/Highest, Type/Bug
