### ISSUE TITLE
API related details are not filled automatically when creating new API using a swagger file

### ISSUE THREAD

**Issue by dimuthnc** [wso2/product-apim#3596] opened 2018-08-09 08:14 UTC
**Description:**
When an APIM publisher user tries to create a new API using a swagger file, set of fields such as Name, context, version etc are automatically filled to those text boxes. This feature is not working now.

**Suggested Labels:**
2.6.0
**Suggested Assignees:**

**Affected Product Version:**
2.6.0-M1
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Start WSO2 APIM 2.6.0-M1 
2. Log into [API Publisher](https://localhost:9443/publisher)
3. Click ADD NEW API -> expand "I have an existing API" and select Swagger file to upload and click on start creating button.
4. You may notice that Name, version etc fields are not filled.

**Related Issues:**

**Comment by praminda** [comment] 2018-08-09 08:20
Duplicate of wso2/product-apim#3594

**Closed by praminda** 2018-08-09 08:20 UTC
Labels: Resolution/Duplicate
