### ISSUE TITLE
[UX][APIM] Need to add client side validation on API Create page

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#3098] opened 2018-03-16 10:55 UTC
**Description:**
1. Current error messages are generic. IMO better to have specific ones. instead of saying "This field is required." better to say "API name cannot be empty" 

2. Need to add client-side validation for API version 
This error is backend error, we need to add client-side one before the submit:  | API Version contains one or more illegal characters  ( [~!@#;%^*()+={}\|<>"',\[\]&/$\\] )

**Suggested Labels:**
improvement 

**Suggested Labels:**
bug

**Affected Product Version:**
2.1.0 update 14

**OS, DB, other environment details and versions:**    
MacOS High sierra/ Chrome 64

**Comment by rmsamitha** [comment] 2022-01-28 04:22
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:22 UTC
Labels: Priority/Low, Affected/2.1.0
