### ISSUE TITLE
[Devportal][Store Visibility] Store visibility restriction isn't properly enforced

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/product-apim#10879] opened 2021-04-08 07:37 UTC
### Description:
When store visibility is configured for an API, the API doesn't get listed in the public/anonymous view but is listed for both allowed and restricted users. 

### Steps to reproduce:
1. Create 2 user `a_ruw_sub` and `a_ruw_sub2` and create and assign roles `a_ruw_sub` and `a_ruw_sub2` to them respectively.
<img width="645" alt="Screenshot 2021-04-08 at 12 54 08" src="https://user-images.githubusercontent.com/20040505/113986777-3c912580-986b-11eb-8701-055fa8a1cc1d.png">

2. Add scope mappings to `internal/subscriber` for both roles

3. Create and publish an API 

4. Set store visibility to `a_ruw_sub` and deploy a new revision.
<img width="1680" alt="Screenshot 2021-04-08 at 12 56 14" src="https://user-images.githubusercontent.com/20040505/113986507-f045e580-986a-11eb-8a7f-09ba470503be.png">

5. Open the devportal in anonymous view, the API will not be listed
<img width="1680" alt="Screenshot 2021-04-08 at 12 55 08" src="https://user-images.githubusercontent.com/20040505/113986515-f20fa900-986a-11eb-9237-7391aad6f7a2.png">

6. Login as either `a_ruw_sub` and `a_ruw_sub2` and the API will be listed for both.
<img width="1679" alt="Screenshot 2021-04-08 at 12 54 15" src="https://user-images.githubusercontent.com/20040505/113986494-eb813180-986a-11eb-8958-c4d37cb8ede5.png">
<img width="1680" alt="Screenshot 2021-04-08 at 12 56 47" src="https://user-images.githubusercontent.com/20040505/113986511-f1771280-986a-11eb-901e-301d1edb5e93.png">

Note: This behaviour was observed in super tenant users.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by rmsamitha** [comment] 2021-04-09 06:20
Issue is not reproduced in 4.0.0-beta pack.

**Comment by rmsamitha** [comment] 2021-04-09 08:28
This is also not reproducible in the distributed setup when tested with newly created roles, users and an API. The issue @ruwiniwj has encountered in the distributed setup is only an indexing issue. Eventhough the "A_RUW_SUB2" user or any other use who doesn't have "a_ruw_sub" role, can see the "a_ruw" API in the listing, he cannot go into that API. Below page is displayed once clicked the API.

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/2484781/114151210-86950c80-993a-11eb-90f0-db3a2b68eeb0.png">

So visibility in the store features is preserved corresponding to the "restricted by roles" aspect. 
So this could be an indexing issue and closing since cannot be reproduced with new roles/apis/users.

**Closed by rmsamitha** 2021-04-09 08:28 UTC
Labels: API-M 4.0.0, Feature/StoreVisibility, Priority/High, Type/Bug
