### ISSUE TITLE
Email Templates are not rendering as HTML

### ISSUE THREAD

**Issue by abhishekdesilva** [wso2/product-apim#4178] opened 2019-01-17 09:02 UTC
**Description:**
The current implementation for sending notifications via email is handled by the [1] for the WSO2 IS products. More specifically, through the publishToStream method of the [2] class. This feature provides the facility to send emails with the content-type of text/html or as the content-type of text/plain. 

However, the WSO2 APIM product is using the previous implementation of sending notifications via email. More specifically, the sendEmail method of the [3] class of the [4] repository. This implementation doesn't facilitate rendering the HTML contents and only supports only the text/plain content-type.

Therefore, please invoke the recovery REST API [5] instead of the User Information recovery SOAP Service [6] for the sending notifications via email.

**Suggested Labels:**
N/A

**Suggested Assignees:**
N/A

**Affected Product Version:**
wso2am-2.2.0 onwards

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

[1] https://github.com/wso2-extensions/identity-event-handler-notification
[2] https://github.com/wso2-extensions/identity-event-handler-notification/blob/master/components/event-handler-notification/org.wso2.carbon.identity.event.handler.notification/src/main/java/org/wso2/carbon/identity/event/handler/notification/NotificationHandler.java#L114
[3] https://github.com/wso2/carbon-identity-framework/blob/master/components/identity-mgt/org.wso2.carbon.identity.mgt/src/main/java/org/wso2/carbon/identity/mgt/mail/DefaultEmailSendingModule.java#L120
[4] https://github.com/wso2/carbon-identity-framework
[5] https://github.com/wso2-extensions/identity-governance/blob/eda8411898118bd4e00ab4a28179cb47873f614d/components/org.wso2.carbon.identity.recovery.endpoint/src/gen/java/org/wso2/carbon/identity/recovery/endpoint/RecoverPasswordApi.java#L41
[6] https://github.com/wso2/carbon-apimgt/blob/6.x/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/modules/password-reset/initiate/initiate.jag#L13

**Comment by rmsamitha** [comment] 2022-01-27 13:33
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-27 13:33 UTC
