### ISSUE TITLE
After running few tests on a slow DB connection oserved a null pointer thrown in the analytics logs after a while

### ISSUE THREAD

**Issue by jsonds** [wso2/product-apim#2621] opened 2018-01-25 11:06 UTC
**Description:**
Ran few chaos scenarios against a apim cluster (pattern 6). This included few api creations and invocation while the database was having a low response rate ( ranging from 100ms to 1000ms delay for a response). Ones the tests were completed removed the latency from the DB. 

While the server was in idle state observed the below exception from the analytic node. Please note that the created api and applications were already deleted at this point.

```
TID: [-1] [] [2018-01-25 07:39:57,061] ERROR {org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction} -  Error while inserting data into table LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY: [-1234:LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY] does not exist {org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction}
org.wso2.carbon.analytics.datasource.commons.exception.AnalyticsTableNotAvailableException: [-1234:LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY] does not exist
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.readTableInfo(AnalyticsDataServiceImpl.java:455)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.lookupTableInfo(AnalyticsDataServiceImpl.java:810)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.preprocessRecordBatch(AnalyticsDataServiceImpl.java:864)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.preprocessRecords(AnalyticsDataServiceImpl.java:790)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.put(AnalyticsDataServiceImpl.java:877)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPutNormal(AnalyticsWritingFunction.java:139)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPut(AnalyticsWritingFunction.java:128)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.apply(AnalyticsWritingFunction.java:119)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.apply(AnalyticsWritingFunction.java:45)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
TID: [-1] [] [2018-01-25 07:39:57,064] ERROR {org.apache.spark.executor.Executor} -  Exception in task 0.0 in stage 1365647.0 (TID 2120213) {org.apache.spark.executor.Executor}
java.lang.RuntimeException: Error while inserting data into table LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY: [-1234:LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY] does not exist
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPutNormal(AnalyticsWritingFunction.java:143)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPut(AnalyticsWritingFunction.java:128)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.apply(AnalyticsWritingFunction.java:119)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.apply(AnalyticsWritingFunction.java:45)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.analytics.datasource.commons.exception.AnalyticsTableNotAvailableException: [-1234:LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY] does not exist
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.readTableInfo(AnalyticsDataServiceImpl.java:455)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.lookupTableInfo(AnalyticsDataServiceImpl.java:810)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.preprocessRecordBatch(AnalyticsDataServiceImpl.java:864)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.preprocessRecords(AnalyticsDataServiceImpl.java:790)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.put(AnalyticsDataServiceImpl.java:877)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPutNormal(AnalyticsWritingFunction.java:139)
        ... 11 more
TID: [-1] [] [2018-01-25 07:39:57,072]  WARN {org.apache.spark.scheduler.TaskSetManager} -  Lost task 0.0 in stage 1365647.0 (TID 2120213, localhost): java.lang.RuntimeException: Error while inserting data into table LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY: [-1234:LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY] does not exist
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPutNormal(AnalyticsWritingFunction.java:143)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPut(AnalyticsWritingFunction.java:128)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.apply(AnalyticsWritingFunction.java:119)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.apply(AnalyticsWritingFunction.java:45)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.analytics.datasource.commons.exception.AnalyticsTableNotAvailableException: [-1234:LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY] does not exist
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.readTableInfo(AnalyticsDataServiceImpl.java:455)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.lookupTableInfo(AnalyticsDataServiceImpl.java:810)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.preprocessRecordBatch(AnalyticsDataServiceImpl.java:864)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.preprocessRecords(AnalyticsDataServiceImpl.java:790)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.put(AnalyticsDataServiceImpl.java:877)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPutNormal(AnalyticsWritingFunction.java:139)
        ... 11 more
 {org.apache.spark.scheduler.TaskSetManager}
TID: [-1] [] [2018-01-25 07:39:57,073] ERROR {org.apache.spark.scheduler.TaskSetManager} -  Task 0 in stage 1365647.0 failed 1 times; aborting job {org.apache.spark.scheduler.TaskSetManager}
TID: [-1234] [] [2018-01-25 07:39:57,075] ERROR {org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService} -  Error while executing query :         INSERT OVERWRITE table loganalyzer_apim_artifact_deleted_daily        SELECT            temp.artifact AS logArtifact,            temp.tenantID AS tenantID,            SUM(temp.artifactCount) AS totalArtifactCount,            getDateStartingTime(temp.byYear, temp.byMonth , temp.byDay) AS _timestamp        FROM (            SELECT                SUBSTRING(_content,17,100) AS artifact,                getYear(_eventTimeStamp) AS byYear,                getMonth(_eventTimeStamp) AS byMonth,                getDay(_eventTimeStamp) AS byDay,                count(*) AS artifactCount,                tenantID AS tenantID            FROM CopyOfLoganalyzer            WHERE _content LIKE "%Destroying API:%"            GROUP BY tenantID, _content, _eventTimeStamp            ORDER BY _eventTimeStamp        )temp        GROUP BY temp.tenantID, temp.artifact, temp.byYear, temp.byMonth, temp.byDay        ORDER BY temp.byYear, temp.byMonth, temp.byDay {org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService}
org.wso2.carbon.analytics.spark.core.exception.AnalyticsExecutionException: Exception in executing query INSERT OVERWRITE table loganalyzer_apim_artifact_deleted_daily        SELECT            temp.artifact AS logArtifact,            temp.tenantID AS tenantID,            SUM(temp.artifactCount) AS totalArtifactCount,            getDateStartingTime(temp.byYear, temp.byMonth , temp.byDay) AS _timestamp        FROM (            SELECT                SUBSTRING(_content,17,100) AS artifact,                getYear(_eventTimeStamp) AS byYear,                getMonth(_eventTimeStamp) AS byMonth,                getDay(_eventTimeStamp) AS byDay,                count(*) AS artifactCount,                tenantID AS tenantID            FROM CopyOfLoganalyzer            WHERE _content LIKE "%Destroying API:%"            GROUP BY tenantID, _content, _eventTimeStamp            ORDER BY _eventTimeStamp        )temp        GROUP BY temp.tenantID, temp.artifact, temp.byYear, temp.byMonth, temp.byDay        ORDER BY temp.byYear, temp.byMonth, temp.byDay
        at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQueryLocal(SparkAnalyticsExecutor.java:918)
        at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQuery(SparkAnalyticsExecutor.java:875)
        at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.executeQuery(CarbonAnalyticsProcessorService.java:201)
        at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.executeScript(CarbonAnalyticsProcessorService.java:151)
        at org.wso2.carbon.analytics.spark.core.AnalyticsTask.execute(AnalyticsTask.java:60)
        at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1365647.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1365647.0 (TID 2120213, localhost): java.lang.RuntimeException: Error while inserting data into table LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY: [-1234:LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY] does not exist
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPutNormal(AnalyticsWritingFunction.java:143)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPut(AnalyticsWritingFunction.java:128)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.apply(AnalyticsWritingFunction.java:119)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.apply(AnalyticsWritingFunction.java:45)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.analytics.datasource.commons.exception.AnalyticsTableNotAvailableException: [-1234:LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY] does not exist
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.readTableInfo(AnalyticsDataServiceImpl.java:455)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.lookupTableInfo(AnalyticsDataServiceImpl.java:810)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.preprocessRecordBatch(AnalyticsDataServiceImpl.java:864)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.preprocessRecords(AnalyticsDataServiceImpl.java:790)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.put(AnalyticsDataServiceImpl.java:877)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPutNormal(AnalyticsWritingFunction.java:139)
        ... 11 more

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
        at scala.Option.foreach(Option.scala:236)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1858)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1915)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsRelation.writeDataFrameToDAL(AnalyticsRelation.java:233)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsRelation.insert(AnalyticsRelation.java:223)
        at org.apache.spark.sql.execution.datasources.InsertIntoDataSource.run(InsertIntoDataSource.scala:40)
        at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:58)
        at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:56)
        at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:70)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:132)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:130)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:130)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:55)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:55)
        at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:145)
        at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:130)
        at org.apache.spark.sql.DataFrame$.apply(DataFrame.scala:52)
        at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:817)
        at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQueryLocal(SparkAnalyticsExecutor.java:914)
        ... 11 more
Caused by: java.lang.RuntimeException: Error while inserting data into table LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY: [-1234:LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY] does not exist
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPutNormal(AnalyticsWritingFunction.java:143)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPut(AnalyticsWritingFunction.java:128)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.apply(AnalyticsWritingFunction.java:119)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.apply(AnalyticsWritingFunction.java:45)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
        ... 3 more
Caused by: org.wso2.carbon.analytics.datasource.commons.exception.AnalyticsTableNotAvailableException: [-1234:LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY] does not exist
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.readTableInfo(AnalyticsDataServiceImpl.java:455)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.lookupTableInfo(AnalyticsDataServiceImpl.java:810)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.preprocessRecordBatch(AnalyticsDataServiceImpl.java:864)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.preprocessRecords(AnalyticsDataServiceImpl.java:790)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.put(AnalyticsDataServiceImpl.java:877)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPutNormal(AnalyticsWritingFunction.java:139)
        ... 11 more
TID: [-1234] [] [2018-01-25 07:39:57,083] ERROR {org.wso2.carbon.analytics.spark.core.AnalyticsTask} -  Error while executing the scheduled task for the script: APIM_LOGANALYZER_SCRIPT {org.wso2.carbon.analytics.spark.core.AnalyticsTask}
org.wso2.carbon.analytics.spark.core.exception.AnalyticsExecutionException: Exception in executing query INSERT OVERWRITE table loganalyzer_apim_artifact_deleted_daily        SELECT            temp.artifact AS logArtifact,            temp.tenantID AS tenantID,            SUM(temp.artifactCount) AS totalArtifactCount,            getDateStartingTime(temp.byYear, temp.byMonth , temp.byDay) AS _timestamp        FROM (            SELECT                SUBSTRING(_content,17,100) AS artifact,                getYear(_eventTimeStamp) AS byYear,                getMonth(_eventTimeStamp) AS byMonth,                getDay(_eventTimeStamp) AS byDay,                count(*) AS artifactCount,                tenantID AS tenantID            FROM CopyOfLoganalyzer            WHERE _content LIKE "%Destroying API:%"            GROUP BY tenantID, _content, _eventTimeStamp            ORDER BY _eventTimeStamp        )temp        GROUP BY temp.tenantID, temp.artifact, temp.byYear, temp.byMonth, temp.byDay        ORDER BY temp.byYear, temp.byMonth, temp.byDay
        at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQueryLocal(SparkAnalyticsExecutor.java:918)
        at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQuery(SparkAnalyticsExecutor.java:875)
        at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.executeQuery(CarbonAnalyticsProcessorService.java:201)
        at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.executeScript(CarbonAnalyticsProcessorService.java:151)
        at org.wso2.carbon.analytics.spark.core.AnalyticsTask.execute(AnalyticsTask.java:60)
        at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1365647.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1365647.0 (TID 2120213, localhost): java.lang.RuntimeException: Error while inserting data into table LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY: [-1234:LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY] does not exist
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPutNormal(AnalyticsWritingFunction.java:143)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPut(AnalyticsWritingFunction.java:128)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.apply(AnalyticsWritingFunction.java:119)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.apply(AnalyticsWritingFunction.java:45)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.analytics.datasource.commons.exception.AnalyticsTableNotAvailableException: [-1234:LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY] does not exist
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.readTableInfo(AnalyticsDataServiceImpl.java:455)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.lookupTableInfo(AnalyticsDataServiceImpl.java:810)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.preprocessRecordBatch(AnalyticsDataServiceImpl.java:864)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.preprocessRecords(AnalyticsDataServiceImpl.java:790)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.put(AnalyticsDataServiceImpl.java:877)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPutNormal(AnalyticsWritingFunction.java:139)
        ... 11 more

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
        at scala.Option.foreach(Option.scala:236)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1832)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1845)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1858)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1915)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsRelation.writeDataFrameToDAL(AnalyticsRelation.java:233)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsRelation.insert(AnalyticsRelation.java:223)
        at org.apache.spark.sql.execution.datasources.InsertIntoDataSource.run(InsertIntoDataSource.scala:40)
        at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:58)
        at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:56)
        at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:70)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:132)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.apply(SparkPlan.scala:130)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:130)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:55)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:55)
        at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:145)
        at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:130)
        at org.apache.spark.sql.DataFrame$.apply(DataFrame.scala:52)
        at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:817)
        at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQueryLocal(SparkAnalyticsExecutor.java:914)
        ... 11 more
Caused by: java.lang.RuntimeException: Error while inserting data into table LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY: [-1234:LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY] does not exist
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPutNormal(AnalyticsWritingFunction.java:143)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPut(AnalyticsWritingFunction.java:128)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.apply(AnalyticsWritingFunction.java:119)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.apply(AnalyticsWritingFunction.java:45)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
        ... 3 more
Caused by: org.wso2.carbon.analytics.datasource.commons.exception.AnalyticsTableNotAvailableException: [-1234:LOGANALYZER_APIM_ARTIFACT_DELETED_DAILY] does not exist
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.readTableInfo(AnalyticsDataServiceImpl.java:455)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.lookupTableInfo(AnalyticsDataServiceImpl.java:810)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.preprocessRecordBatch(AnalyticsDataServiceImpl.java:864)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.preprocessRecords(AnalyticsDataServiceImpl.java:790)
        at org.wso2.carbon.analytics.dataservice.core.AnalyticsDataServiceImpl.put(AnalyticsDataServiceImpl.java:877)
        at org.wso2.carbon.analytics.spark.core.sources.AnalyticsWritingFunction.recordsPutNormal(AnalyticsWritingFunction.java:139)
        ... 11 more

```

**Suggested Labels:**
APIM-2.1.0 wum (1516470910911)
Type/bug
Priority/high
Sevirity/Minor

**Affected Product Version:**
APIM-2.1.0 wum (1516470910911)

**OS, DB, other environment details and versions:**    
OS: Ubuntu 14.04
DB: MySQL 5.5.58
JDK: Oracke jdk-8u121
Setup: puppet pattern 6
Note: enabled log4jdbc

**Comment by rmsamitha** [comment] 2022-01-27 09:50
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-27 09:50 UTC
Labels: 2.2.0, Affected/2.1.0
