### ISSUE TITLE
[UX] Publisher should be able to enable notifications from publisher app

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2980] opened 2018-03-11 05:40 UTC
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Visibility of system status -Is the user informed about what's going on
Consistency and standards - Is flow maintain the same patterns and consistency
Recognition rather than recall - Is the objects, actions, and options clearly visible

***Related task:***
Notify subscribers about new API version

***Issue and proposed solution:***
Without going to the carbon console Main > Resource > Browse, publisher should be able to enable notification and edit other notification options from the publisher app.

***Doc Link:***
[1] https://docs.wso2.com/display/AM210/Enabling+Notifications	

**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.1.0

**Comment by rmsamitha** [comment] 2022-01-28 04:33
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:33 UTC
Labels: Priority/Low, Affected/2.1.0
