### ISSUE TITLE
[Store] Inability to uniquely identify the APIs under subscriptions

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6671] opened 2019-10-25 05:43 UTC
As shown in the screenshot below, the APIs listed under the subscriptions cannot be uniquely identified. It is better to show the version of the API and also the domain (since all public APIs with the same name are also listed here).

![1](https://user-images.githubusercontent.com/30475839/67545818-2b586580-f718-11e9-89ff-732696baa1b4.png)

**Comment by dushaniw** [comment] 2019-11-13 11:16
Duplicate of https://github.com/wso2/product-apim/issues/6712

**Closed by dushaniw** 2019-11-13 11:16 UTC
