### ISSUE TITLE
Unable to add any files using "Create Text content" option in firefox browser

### ISSUE THREAD

**Issue by niveathika** [wso2/product-apim#3019] opened 2018-03-13 10:14 UTC
**Description:**
In management console Home > Resources > Browse, cannot add any files using "Create Text Content" options.

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**
2.1.0, 2.0.0, 1.10.0

**OS, DB, other environment details and versions:**    
Firefox 58.0.2

**Steps to reproduce:**
1. Start the server
2. Navigate to Home > Resources > Browse, in the management console
3.  Click "Add Resource"
4. Select "Create Text Content" option
5. Fill the details
6. Click "Add" button

**Related Issues:**
The same issue was faced in updating the resource - https://wso2.org/jira/browse/REGISTRY-2156

**Comment by rmsamitha** [comment] 2022-01-28 04:29
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:29 UTC
Labels: Priority/Low, Affected/2.1.0
