### ISSUE TITLE
[WSO2 API MANAGER - PRIVACY POLICY] Make the "Disclaimer" as a link

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#2873] opened 2018-03-06 11:14 UTC
**Description:**
Make the Disclaimer as clickable link as it refer the other section of the document.

**Suggested Labels:**
Type/Improvement
Severity/Major
Priority/High
Affected/2.1.0 Update13

**Affected Product Version:**
APIM 2.1.0 Update13

**Comment by rmsamitha** [comment] 2022-01-28 04:42
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:42 UTC
Labels: Priority/Normal, Affected/2.1.0
