### ISSUE TITLE
Privacy policy doesn't contain reasons why we are collecting PII.

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#2876] opened 2018-03-06 11:38 UTC
**Description:**
In WSO2 APIM policy Privacy policy it doesn't contain why we are collecting some of the PII  like
 Email Address
 FirstName
 LastName at user sign up level.

 As per the reference in below, it should contain information of all PII data which we are using as our privacy policy.

[1] https://ico.org.uk/media/about-the-ico/consultations/2013551/draft-gdpr-consent-guidance-for-consultation-201703.pdf

**Suggested Labels:**
Type/Bug
Severity/Critical
Priority/High
Affected/APIM 2.1.0 Update13

**Affected Product Version:**
APIM 2.1.0 Update 13

**Comment by rmsamitha** [comment] 2022-01-28 04:41
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:41 UTC
Labels: Priority/Normal, Affected/2.1.0
