### ISSUE TITLE
"Invalid input" error message when trying to blacklist a user in admin portal

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#7967] opened 2020-04-28 07:17 UTC
### Description:
In wso2am-2.1.0 when a secondary user is added to the blacklist in the admin portal, just below the textbox where we entered the user name we get "Invalid Input".
![image](https://user-images.githubusercontent.com/20519000/80457839-93009f00-894d-11ea-848c-8150d556b91f.png)

### Steps to reproduce:
1. Create a secondary user store (domain) and add a user to it(DOMAIN/user)
2. Create an API in the publisher and add application subscription to it
3. Generate a token for the mentioned user in the secondary user store.
4. Invoke the API with the token generated.
5. In the admin portal navigate to Throttling Policies --> Black List --> Add Item --> Provide the secondary user store details --> Click on Blacklist.
6. You will be able to see the above-stated error.

### Affected Product Version:
wso2am-2.1.0

#### Related Issues:
https://github.com/wso2/product-apim/issues/6285

**Comment by praminda** [comment] 2020-04-29 02:43
I believe #6285 is the same issue. Please correct me if i'm wrong.

**Comment by praminda** [comment] 2020-04-29 02:43
Duplicate of #6285

**Closed by praminda** 2020-04-29 02:43 UTC
Labels: Priority/Normal, Type/Bug
