### ISSUE TITLE
Once scope is selected for a resource from dropdown it is unable to deselect 

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#5363] opened 2019-08-26 06:56 UTC
Steps:
1. Add scopes to API
2. Select a scope for a resource from the dropdown
3. There should include an option to remove that scope from the resource.

<img width="964" alt="scope123" src="https://user-images.githubusercontent.com/29066805/63664822-30676a00-c7e6-11e9-9ab5-a47e52c49d27.png">

**Comment by chamilaadhi** [comment] 2019-10-12 06:03
duplicate of https://github.com/wso2/product-apim/issues/6241

**Closed by chamilaadhi** 2019-10-12 06:03 UTC
Labels: 3.0.0, Type/Bug
