### ISSUE TITLE
UpdatedBy column is not populated for AM_API table

### ISSUE THREAD

**Issue by fazlan-nazeem** [wso2/product-apim#2854] opened 2018-03-06 05:15 UTC
**Description:**
There is no easy way to find out who updated an API if a different user edits an API and republishes after some changes. This should be at least populated in the db table correctly. Currently the value is null.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.1.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rmsamitha** [comment] 2022-01-28 04:48
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:48 UTC
Labels: Type/Improvement, Priority/Normal, 2.2.0, 3.x.x
