### ISSUE TITLE
Duplicate roles/scopes after adding role permissions in admin portal

### ISSUE THREAD

**Issue by RakhithaRR** [wso2/product-apim#9618] opened 2020-12-11 04:25 UTC
### Description:
In Admin Portal, after adding role permissions to a role using role alias, duplicate entries of the role alias are created every time you navigate between the pages of the table. This would go away when refreshed but will appear again when you move between pages.

### Affected Product Version:
3.2.0

@tmkasun @chanaka3d 

![Screenshot from 2020-12-11 09-49-27](https://user-images.githubusercontent.com/25485273/101861807-f8c93080-3b96-11eb-88e6-20698f80f3d5.png)

**Comment by kavishkafernando** [comment] 2021-03-19 07:32
Unable to reproduce in latest pack hence closing the issue.

<img width="1116" alt="Screenshot 2021-03-19 at 12 59 59 PM" src="https://user-images.githubusercontent.com/19324135/111745888-41d60280-88b3-11eb-8ba1-48f94d5d48a5.png">
<img width="1079" alt="Screenshot 2021-03-19 at 1 00 04 PM" src="https://user-images.githubusercontent.com/19324135/111745901-469ab680-88b3-11eb-8103-fd3d7b0cdcda.png">

**Closed by kavishkafernando** 2021-03-19 07:32 UTC
Labels: API-M 4.0.0, Priority/High, Type/Bug, Type/React-UI
