### ISSUE TITLE
No Email Notification is sent for a particular email address in registering a user in STORE sign up

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/product-apim#2265] opened 2018-01-08 05:13 UTC
**Suggested Labels:**
Type/Bug
APIM 2.2.0

**Affected Product Version:**
wso2am-2.1.0-update5

**OS, DB, other environment details and versions:**

Standalone
DB - H2
Browser - Chrome Version 61.0.3163.100 (Official Build) (64-bit)
JDK - jdk1.8.0_121

**Steps to reproduce:**

1.Run APIM 2.1.0 update 5
2.Access API Store
3. Go to user Sign up
4. Add a user giving a particular email address

**Observation**
No email message is sent for the users email address by notifying that he has registered that email address under wso2 API store. In order to validate a particular email address which is given in the signup user needs to get a email for his account.

**Comment by chamilaadhi** [comment] 2019-09-16 10:15
duplicate of https://github.com/wso2/product-apim/issues/4070. Hence closing

**Closed by chamilaadhi** 2019-09-16 10:15 UTC
Labels: 2.2.0, Type/Bug
