### ISSUE TITLE
[UI] Blank page when viewing API overview in anonymous mode

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#10830] opened 2021-04-08 05:24 UTC
### Description:
Blank page rendered when viewing API overview page in anonymous mode:

Following error observed in console:
```
TypeError: t is null
    f Environments.jsx:110
    ke Environments.jsx:236
    React 6
    unstable_runWithPriority scheduler.production.min.js:19
    React 5
    default Overview.jsx:193
    promise callback*4616/t.default/< Overview.jsx:187
    React 2
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
    L scheduler.production.min.js:17
    onmessage scheduler.production.min.js:14
    EventHandlerNonNull* scheduler.production.min.js:13
    Webpack 11
```

**Comment by erangatl** [comment] 2021-04-08 07:15
Duplicate of https://github.com/wso2/product-apim/issues/10786
Already fixed with https://github.com/wso2/carbon-apimgt/pull/10252

**Closed** 2021-04-08 11:51 UTC
Labels: API-M 4.0.0, Priority/High, React-UI, Resolution/Duplicate, Type/Bug
