### ISSUE TITLE
APIM fails to start after encrypting passwords using ciphertool

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#10217] opened 2021-03-10 06:45 UTC
### Description:
ciphertool tool was used to encrypt the following passwords in the deployment.toml file as suggested in the documentation.

```
[secrets]
admin_password = "[admin]"
keystore_password = "[wso2carbon]"
key_password = "[wso2carbon]"
truststrore_password = "[wso2carbon]"
```

The resulting file has been attached as a text file [deployment.txt](https://github.com/wso2/product-apim/files/6113684/deployment.txt) to be able to attach to the issue

Starting the APIM fails and the following exception is seen in the logs

```
TID: [2021-03-10 11:54:57,367]  INFO {org.wso2.config.mapper.ConfigParser} - Applying Configurations upon new Templates {org.wso2.config.mapper.ConfigParser}
TID: [2021-03-10 11:54:57,369]  WARN {org.wso2.config.mapper.ConfigParser} - Overriding files in configuration directory /home/uvindra/APIM_packs/Alpha/Secure-vault/wso2am-4.0.0-alpha {org.wso2.config.mapper.ConfigParser}
TID: [2021-03-10 11:54:58,249]  INFO {org.wso2.config.mapper.ConfigParser} - Writing Metadata Entries... {org.wso2.config.mapper.ConfigParser}
TID: [-1234] [] [2021-03-10 11:55:12,100]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Starting WSO2 Carbon...
TID: [-1234] [] [2021-03-10 11:55:12,110]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Operating System : Linux 4.15.0-136-generic, amd64
TID: [-1234] [] [2021-03-10 11:55:12,111]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java Home        : /home/uvindra/Apps/Java11/jdk-11.0.10_linux-x64_bin/jdk-11.0.10
TID: [-1234] [] [2021-03-10 11:55:12,111]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java Version     : 11.0.10
TID: [-1234] [] [2021-03-10 11:55:12,111]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java VM          : Java HotSpot(TM) 64-Bit Server VM 11.0.10+8-LTS-162,Oracle Corporation
TID: [-1234] [] [2021-03-10 11:55:12,111]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Carbon Home      : /home/uvindra/APIM_packs/Alpha/Secure-vault/wso2am-4.0.0-alpha
TID: [-1234] [] [2021-03-10 11:55:12,111]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - Java Temp Dir    : /home/uvindra/APIM_packs/Alpha/Secure-vault/wso2am-4.0.0-alpha/tmp
TID: [-1234] [] [2021-03-10 11:55:12,112]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} - User             : uvindra, en-US, Asia/Colombo
TID: [-1] [] [2021-03-10 11:55:12,290]  INFO {org.wso2.carbon.crypto.provider.internal.DefaultCryptoProviderComponent} - 'CryptoService.Secret' property has not been set. 'org.wso2.carbon.crypto.provider.SymmetricKeyInternalCryptoProvider' won't be registered as an internal crypto provider. Please set the secret if the provider needs to be registered.
TID: [-1] [] [2021-03-10 11:55:12,752]  INFO {org.wso2.carbon.event.output.adapter.kafka.internal.ds.KafkaEventAdapterServiceDS} - Successfully deployed the Kafka output event adaptor service
TID: [-1] [] [2021-03-10 11:55:13,105]  INFO {org.wso2.carbon.event.template.manager.core.internal.ds.TemplateDeployerServiceTrackerDS} - Successfully deployed the execution manager tracker service
TID: [-1234] [] [2021-03-10 11:55:17,568] ERROR {org.wso2.carbon.user.core.internal.Activator} - Cannot start User Manager Core bundle java.lang.NullPointerException
        at java.base/java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:947)
        at java.base/java.lang.StringBuilder.replace(StringBuilder.java:302)
        at org.wso2.securevault.commons.MiscellaneousUtil.resolve(MiscellaneousUtil.java:267)
        at org.wso2.securevault.commons.MiscellaneousUtil.resolve(MiscellaneousUtil.java:243)
        at org.wso2.carbon.user.core.config.RealmConfigXMLProcessor.buildRealmConfiguration(RealmConfigXMLProcessor.java:378)
        at org.wso2.carbon.user.core.config.RealmConfigXMLProcessor.buildRealmConfiguration(RealmConfigXMLProcessor.java:289)
        at org.wso2.carbon.user.core.common.DefaultRealmService.buildBootStrapRealmConfig(DefaultRealmService.java:138)
        at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:86)
        at org.wso2.carbon.user.core.common.DefaultRealmService.<init>(DefaultRealmService.java:115)
        at org.wso2.carbon.user.core.internal.Activator.startDeploy(Activator.java:72)
        at org.wso2.carbon.user.core.internal.BundleCheckActivator.start(BundleCheckActivator.java:61)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
        at org.eclipse.osgi.container.Module.doStart(Module.java:598)
        at org.eclipse.osgi.container.Module.start(Module.java:462)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

```

### Steps to reproduce:
1. Change depolyment.toml file to encrypt the standard suggested passwords as in the documentation.
2. Run ciphertool to encrypt the passwords.
3. Start APIM

**Comment by rmsamitha** [comment] 2021-03-24 13:27
The issue is not reproduced in the master, hence closing.

**Closed by rmsamitha** 2021-03-24 13:27 UTC
Labels: API-M 4.0.0, Feature/CipherTool, Priority/Highest, Type/Bug
