### ISSUE TITLE
API list view is not user friendly

### ISSUE THREAD

**Issue by binodmx** [wso2/product-apim#5881] opened 2019-09-27 05:29 UTC
- API listing table has all lower case table heads. It should be Camel case atleast.
- Cannot select API by clicking on a row in API list view 
- List view state is not saved. After refreshing the page or coming back to the API listing page, it shows the Grid view.

![Screenshot from 2019-09-27 10-56-54](https://user-images.githubusercontent.com/36144069/65744404-e095fe80-e115-11e9-81f8-ec33179619c5.png)

**Comment by binodmx** [comment] 2019-10-04 10:50
Also, it is occurred this error as well. 
https://github.com/wso2/product-apim/issues/6237

**Comment by chamilaadhi** [comment] 2019-10-13 13:23
Fixed the lower case table name issue in 3.0.0 beta
<img width="1410" alt="Screen Shot 2019-10-13 at 6 46 56 PM" src="https://user-images.githubusercontent.com/4861150/66716372-c41ee500-edea-11e9-837a-f9aeddfb7db9.png">

**Comment by dushaniw** [comment] 2020-02-11 08:19
Closing as the issue is fixed.

**Closed by dushaniw** 2020-02-11 08:19 UTC
Labels: Priority/High
