### ISSUE TITLE
NULL is published for  api_version when default api becomes suspended.

### ISSUE THREAD

**Issue by minudika** [wso2/product-apim#2784] opened 2018-02-21 10:43 UTC
**Description:**
When the default API get suspended, NULL is published for the api_version.

This might cause issues in the apim-analytics when trying to insert those NULL values into tables.
Therefore spark script could be failed to execute.

**Suggested Labels:**
bug

**Suggested Assignees:**

**Affected Product Version:**
2.1.0

**Comment by rmsamitha** [comment] 2022-01-27 09:50
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed** 2022-01-28 04:49 UTC
Labels: Affected/2.1.0
