### ISSUE TITLE
[Bug] Published APIs with the api name having capital letters not showing in store when not logged in

### ISSUE THREAD

**Issue by dushansilva** [wso2/product-apim#4022] opened 2018-11-29 09:49 UTC
**Description:**
When APIM 2.5 being setup in an distributed environment with the use of oracle database, the API created with having capital letters in its api name will not be shown in the store when the user is not logged in. This is only found when using oracle databases for the distributed setup.

**Suggested Labels:**
bug

**Affected Product Version:**
apim 2.5

**OS, DB, other environment details and versions:**    
oracle 11g

**Comment by rmsamitha** [comment] 2022-01-28 04:05
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:05 UTC
Labels: 2.5.0
