### ISSUE TITLE
Backend gives an error when running the forget me tool

### ISSUE THREAD

**Issue by chalitha87** [wso2/product-apim#2958] opened 2018-03-09 11:41 UTC
**Description:**
Backend gives some sql exception when running the forget me tool

**Suggested Labels:**
Type/Bug
Severity/Blocker
Priority/Highest
Affected/APIM 2.1.0 update 13

**Affected Product Version:**
APIM 2.1.0 update 13

**OS, DB, other environment details and versions:**    
OS-Mac high sierra
DB-H2
Fresh APIM 2.2.0 update 13

**Steps to reproduce:**

- Create several users in APIM update 13 pack
- Did several action by login via those users
- Configure the config.json file by pointing the Directory and the log file location.
- Delete one of the user from Management console.
- Shut down the APIM server
- Run the forget me tool as ./forgetme.sh -U testuser

**Results:**

- Backend gives the following exception while clearing the information
- Testuser name also still exist in the log files.

`2018-03-09 16:03:58 ERROR ForgetMeExecutionEngine:112 - Interrupted while executing the processor thread : java.util.concurrent.FutureTask@14dd9eb7
java.util.concurrent.ExecutionException: org.wso2.carbon.privacy.forgetme.api.runtime.InstructionExecutionException: Error occurred while executing sql from : /Users/chalitha/Documents/RD/apimupdate13/forgetMe/wso2am-2.1.0-update13/repository/components/tools/identity-anonymization-tool/conf/sql/apim
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.waitForCompletion(ForgetMeExecutionEngine.java:109)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine.execute(ForgetMeExecutionEngine.java:91)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.process(ForgetMeTool.java:188)
	at org.wso2.carbon.privacy.forgetme.ForgetMeTool.main(ForgetMeTool.java:128)
Caused by: org.wso2.carbon.privacy.forgetme.api.runtime.InstructionExecutionException: Error occurred while executing sql from : /Users/chalitha/Documents/RD/apimupdate13/forgetMe/wso2am-2.1.0-update13/repository/components/tools/identity-anonymization-tool/conf/sql/apim
	at org.wso2.carbon.privacy.forgetme.sql.instructions.RdbmsForgetMeInstruction.execute(RdbmsForgetMeInstruction.java:141)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine$ProcessorPipeline.call(ForgetMeExecutionEngine.java:217)
	at org.wso2.carbon.privacy.forgetme.ForgetMeExecutionEngine$ProcessorPipeline.call(ForgetMeExecutionEngine.java:188)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.privacy.forgetme.sql.exception.SQLModuleException: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "APPLICATION_NAME_CONSTRAINT_INDEX_9 ON PUBLIC.SP_APP(APP_NAME, TENANT_ID)"; SQL statement:
UPDATE SP_APP 
SET USERNAME =  ? , APP_NAME =  ? , DESCRIPTION =  ?  
WHERE USERNAME =  ?  AND USER_STORE =  ?  AND TENANT_ID =  ? 
 [23001-140]
	at org.wso2.carbon.privacy.forgetme.sql.module.SPAppSQLExecutionModule.execute(SPAppSQLExecutionModule.java:117)
	at org.wso2.carbon.privacy.forgetme.sql.module.SPAppSQLExecutionModule.execute(SPAppSQLExecutionModule.java:39)
	at org.wso2.carbon.privacy.forgetme.sql.instructions.RdbmsForgetMeInstruction.execute(RdbmsForgetMeInstruction.java:123)
	... 6 more
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "APPLICATION_NAME_CONSTRAINT_INDEX_9 ON PUBLIC.SP_APP(APP_NAME, TENANT_ID)"; SQL statement:
UPDATE SP_APP 
SET USERNAME =  ? , APP_NAME =  ? , DESCRIPTION =  ?  
WHERE USERNAME =  ?  AND USER_STORE =  ?  AND TENANT_ID =  ? 
 [23001-140]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:157)
	at org.h2.index.PageBtree.find(PageBtree.java:121)
	at org.h2.index.PageBtreeLeaf.addRow(PageBtreeLeaf.java:138)
	at org.h2.index.PageBtreeLeaf.addRowTry(PageBtreeLeaf.java:93)
	at org.h2.index.PageBtreeIndex.addRow(PageBtreeIndex.java:90)
	at org.h2.index.PageBtreeIndex.add(PageBtreeIndex.java:81)
	at org.h2.table.RegularTable.addRow(RegularTable.java:116)
	at org.h2.table.Table.updateRows(Table.java:419)
	at org.h2.command.dml.Update.update(Update.java:124)
	at org.h2.command.CommandContainer.update(CommandContainer.java:70)
	at org.h2.command.Command.executeUpdate(Command.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:141)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:127)
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61)
	at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.executeUpdate(HikariPreparedStatementProxy.java)
	at org.wso2.carbon.privacy.forgetme.sql.module.SPAppSQLExecutionModule.execute(SPAppSQLExecutionModule.java:110)
	... 8 more`

**Comment by rmsamitha** [comment] 2022-01-28 04:33
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:33 UTC
Labels: Affected/2.1.0
