### ISSUE TITLE
Sync up apimgt database scripts with Identity Scripts

### ISSUE THREAD

**Issue by ChamNDeSilva** [wso2/product-apim#1760] opened 2017-11-24 16:42 UTC
**Description:**
API Manager database script is missing bellow table compared to the identity table.

CREATE TABLE IF NOT EXISTS  IDN_SAML2_ASSERTION_STORE (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  SAML2_ID  VARCHAR(255) ,
  SAML2_ISSUER  VARCHAR(255) ,
  SAML2_SUBJECT  VARCHAR(255) ,
  SAML2_SESSION_INDEX  VARCHAR(255) ,
  SAML2_AUTHN_CONTEXT_CLASS_REF  VARCHAR(255) ,
  SAML2_ASSERTION  VARCHAR(4096) ,
  PRIMARY KEY (ID)
)ENGINE INNODB;

And there are few VARCHAR expansions from 127 range to 255 range.

When configuring IS as Key Manager it is needed these two scripts to be synced.

**Suggested Labels:**
2.1.0

**Affected Product Version:**

APIM-2.1.0   

**Related Issues:**

**Comment by irham0019** [comment] 2018-01-09 09:26
The issue is fixed by pr[1]
[1] https://github.com/wso2/carbon-apimgt/pull/4915

**Closed** 2018-01-09 09:26 UTC
Labels: 2.2.0
