### ISSUE TITLE
[publisher] typography issue in api listing

### ISSUE THREAD

**Issue by pahans** [wso2/product-apim#6793] opened 2019-11-08 06:37 UTC
![](https://www.evernote.com/l/AK9kBMoNEdBMIqaAnwVGBS26C_AtEgxNJpwB/image.png)

**Comment by tmkasun** [comment] 2019-11-08 07:09
duplicate of https://github.com/wso2/product-apim/issues/6739

**Closed** 2019-11-08 07:09 UTC
Labels: 3.0.1, Resolution/Duplicate
