### ISSUE TITLE
 Add a WSDL to an API operation is not working as expected.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-apim#3336] opened 2018-06-05 10:58 UTC
**Description:**
 **Add a WSDL to an API** operation, only adds the WSDL to registry resources but doesn't update the API with WSDL URI.

**Suggested Labels:**
Type/Bug

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.2.0 WUM

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Follow the doc [1] and invoke the **Add a WSDL to an API** operation to an API. Then from the carbon console, we can confirm that it is added only as registry resource and the API has no reference for it.

[1] - https://docs.wso2.com/display/AM220/apidocs/publisher/index.html#!/operations%23WsdlIndividual%23apisApiIdWsdlPost

**Comment by rmsamitha** [comment] 2022-01-28 04:13
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:13 UTC
Labels: Affected/3.0.0
