### ISSUE TITLE
Filtering when browsing registry

### ISSUE THREAD

**Issue by SachithUd** [wso2/product-apim#3065] opened 2018-03-15 10:01 UTC
**Description:**
When needed to delete a registry endpoint, the only way I know to delete that endpoint (that are created using the management console) is to browse to the directory that contains the endpoint and click on the pages one at a time and search for the endpoint as they are not sorted by alphabetical order or any order that is recognizable.
When there are lots of endpoints, it will not be easy to find the exact one. 
It would be so much more convenient to be able to either filter when browsing folders for elements that contain what user is looking for, or at least have them sorted in alphabetical order, so the user can attempt to guess what page the element is on so he/she can Rename, Move, Delete or Copy the element.

**Suggested Labels:**
Type/Improvement

**Affected Product Version:**
WSO2AM-2.1.0

**Comment by rmsamitha** [comment] 2022-01-28 04:26
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:26 UTC
Labels: Affected/2.1.0
