### ISSUE TITLE
Cannot import GraphQL schema 

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/product-apim#10034] opened 2021-03-01 04:29 UTC
### Description:
When import GraphQL schema, api creation wizard is not getting popup 

### Steps to reproduce:
Get the schema from http://snowtooth.moonhighway.com/
Drag schema to import it apim

### Affected Product Version:
am-4.0.0-alpha

**Comment by malinthaprasan** [comment] 2021-03-15 19:16
There seems to be some validation errors in the SDL that causes this issue and UI doesn't seem to handle it.

![image](https://user-images.githubusercontent.com/1591316/111208604-fb518100-85f0-11eb-8303-6f1f8c161ae5.png)

When SDL validation call success this seems to be working.

**Comment by tmkasun** [comment] 2021-04-02 14:44
Tried uploading the schema after removing the none standard code from the SDL,  can't reproduce it in the latest pack hence closing the issue

**Closed by tmkasun** 2021-04-02 14:44 UTC
Labels: API-M 4.0.0, Complexity/Low, Priority/Normal, Publisher, React-UI, Type/Bug
