### ISSUE TITLE
Returning errors Subscription blocking in the Cross Tenant Subscription flow - APIM 3.2.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11907] opened 2021-10-27 06:19 UTC
### Description:
Throwing errors when blocking subscriptions in the cross tenant subscriptions.

### Steps to reproduce:

- Enable cross tenant subscription by modifying the **deployment.toml** file.
- Create a tenant domain (**def.com**)
- Log into the publisher portal by using the tenant admin credentials.
- Publish an API. (**PizzaShackAPI**)
- Log into the dev portal by using carbon super admin credentials.
- Subscribe to the API with an application and generate application keys.
- Again log into the publisher portal by using tenant admin's credentials.
- Under the **Subscriptions** section, tried to block the subscription and was able to see an error message at the UI level. (Internal Server Error)

![something](https://user-images.githubusercontent.com/18566908/139009590-11ca6c15-af9f-4eab-9d89-49068d975ad9.png)

- Furthermore, able to see the below error logs in the carbon logs.
```
TID: [38] [api/am/publisher] [2021-10-25 17:35:32,329] ERROR {org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.SubscriptionsApiServiceImpl} - Error while blocking the subscription ffcfe26e-fd7c-42ef-bcf2-cb2e46ad26ed org.wso2.carbon.apimgt.api.APIManagementException: Cannot retrieve service provider for the given consumer key : fDkK8dAOfAFDkeVCo_gxibqWWt4a
    at org.wso2.carbon.apimgt.impl.AbstractKeyManager.handleException_aroundBody12(AbstractKeyManager.java:269)
    at org.wso2.carbon.apimgt.impl.AbstractKeyManager.handleException(AbstractKeyManager.java:267)
    at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.retrieveApplication_aroundBody10(AMDefaultKeyManagerImpl.java:360)
    at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.retrieveApplication(AMDefaultKeyManagerImpl.java:350)
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getClientOfApplication_aroundBody92(ApiMgtDAO.java:2288)
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getClientOfApplication(ApiMgtDAO.java:2255)
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getOAuthApplications_aroundBody90(ApiMgtDAO.java:2246)
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getOAuthApplications(ApiMgtDAO.java:2243)
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getApplicationById_aroundBody278(ApiMgtDAO.java:6423)
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getApplicationById(ApiMgtDAO.java:6387)
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getSubscriptionByUUID_aroundBody48(ApiMgtDAO.java:1212)
    at org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO.getSubscriptionByUUID(ApiMgtDAO.java:1197)
    at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getSubscriptionByUUID_aroundBody136(AbstractAPIManager.java:1951)
    at org.wso2.carbon.apimgt.impl.AbstractAPIManager.getSubscriptionByUUID(AbstractAPIManager.java:1950)
    at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.getSubscriptionByUUID_aroundBody64(UserAwareAPIProvider.java:331)
    at org.wso2.carbon.apimgt.impl.UserAwareAPIProvider.getSubscriptionByUUID(UserAwareAPIProvider.java:329)
    at org.wso2.carbon.apimgt.rest.api.publisher.v1.impl.SubscriptionsApiServiceImpl.subscriptionsBlockSubscriptionPost(SubscriptionsApiServiceImpl.java:70)
    at org.wso2.carbon.apimgt.rest.api.publisher.v1.SubscriptionsApi.subscriptionsBlockSubscriptionPost(SubscriptionsApi.java:56)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
    at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:193)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
    at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
    at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
    at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
    at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
    at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:86)
    at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:110)
    at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:103)
    at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
    at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
    at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
    at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
    at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
    at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:124)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.wso2.carbon.apimgt.impl.kmclient.KeyManagerClientException: Received status code: 403 Reason: 
    at org.wso2.carbon.apimgt.impl.kmclient.KMClientErrorDecoder.decode_aroundBody0(KMClientErrorDecoder.java:29)
    at org.wso2.carbon.apimgt.impl.kmclient.KMClientErrorDecoder.decode(KMClientErrorDecoder.java:27)
    at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96)
    at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
    at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
    at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
    at com.sun.proxy.$Proxy242.getApplication(Unknown Source)
    at org.wso2.carbon.apimgt.impl.AMDefaultKeyManagerImpl.retrieveApplication_aroundBody10(AMDefaultKeyManagerImpl.java:357)
    ... 67 more
```

### Affected Product Version:
3.2.0

**Comment by YasasRangika** [comment] 2021-11-03 12:32
closing this issue since another issue [1] occurs when reproducing this in master.
[1] https://github.com/wso2/product-apim/issues/11944

**Comment by HiranyaKavishani** [comment] 2022-01-19 08:21
The issue is not reproducing now. @YasasRangika 
Could you please add this to master?

**Closed** 2024-12-09 11:05 UTC
Labels: Type/Bug, Priority/Normal, WUM
