### ISSUE TITLE
Cannot add certificates through UI for the endpoints that matches with the same hostname as 

### ISSUE THREAD

**Issue by Megala21** [wso2/product-apim#2662] opened 2018-02-01 18:07 UTC
**Description:**
If I access publisher app through https://localhost:9443/publisher. Even if I define an endpoint with different port but same host name(E.g. http://localhost:9444/publisher), it gives following error,
**You must first enter Production/ Sandbox endpoints to add a certificate or the Endpoints you have entered are not valid.**
This is related with the feature https://docs.wso2.com/display/AM210/Dynamic+SSL+Certificate+Installation

**Suggested Labels:**
Bug, APIM2.x, WUM updated APIM 2.1

**Suggested Assignees:**
N/A

**Affected Product Version:** WUM updated APIM 2.1

**OS, DB, other environment details and versions:**   Chrome, Ubuntu 16.04 

**Steps to reproduce:**

1. Access the pubisher application by using "https://localhost:9443/publisher"
2. Create a API through publisher UI
3. Define the production endpoint as https://localhost:9444
4. Click on Manage certificates
5. It should give a pop-up as below,
**You must first enter Production/ Sandbox endpoints to add a certificate or the Endpoints you have entered are not valid.**

**Related Issues:**
N/A

**Comment by rmsamitha** [comment] 2022-01-28 04:51
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:51 UTC
Labels: Affected/2.1.0
