### ISSUE TITLE
[IS-as-KM 5.5.0] Error is thrown when generating access tokens

### ISSUE THREAD

**Issue by ThilinaManamgoda** [wso2/product-apim#3182] opened 2018-04-06 09:04 UTC
**Description:**
Following error is thrown when an Access token is created for an Application through Store. Although the process is not interpreted and no exceptions are shown in the UI. The generated access token is also working.
`| [2018-04-05 11:29:20,910] ERROR {org.wso2.carbon.registry.core.internal.RegistryCoreServiceComponent} -  Unable to create fixed remote mounts.
is-as-km_1      | org.wso2.carbon.registry.core.exceptions.RegistryException: An exception occurred while executing handler chain. null
is-as-km_1      |       at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.delete(HandlerManager.java:2652)
is-as-km_1      |       at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.delete(UserDefinedHandlerManager.java:215)
is-as-km_1      |       at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.delete(HandlerLifecycleManager.java:443)
is-as-km_1      |       at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.delete(EmbeddedRegistry.java:851)
is-as-km_1      |       at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.delete(CacheBackedRegistry.java:595)
is-as-km_1      |       at org.wso2.carbon.registry.core.session.UserRegistry.deleteInternal(UserRegistry.java:867)
is-as-km_1      |       at org.wso2.carbon.registry.core.session.UserRegistry.access$1100(UserRegistry.java:61)
is-as-km_1      |       at org.wso2.carbon.registry.core.session.UserRegistry$12.run(UserRegistry.java:842)
is-as-km_1      |       at org.wso2.carbon.registry.core.session.UserRegistry$12.run(UserRegistry.java:839)
is-as-km_1      |       at java.security.AccessController.doPrivileged(Native Method)
is-as-km_1      |       at org.wso2.carbon.registry.core.session.UserRegistry.delete(UserRegistry.java:839)
is-as-km_1      |       at org.wso2.carbon.registry.core.internal.RegistryCoreServiceComponent.setupMounts(RegistryCoreServiceComponent.java:303)
is-as-km_1      |       at org.wso2.carbon.registry.core.utils.RegistryUtils.initializeTenant(RegistryUtils.java:1163)
is-as-km_1      |       at org.wso2.carbon.identity.application.mgt.ApplicationMgtUtil.storePermissions(ApplicationMgtUtil.java:253)
is-as-km_1      |       at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.createApplication(ApplicationManagementServiceImpl.java:140)
is-as-km_1      |       at org.wso2.carbon.apimgt.keymgt.service.APIKeyMgtSubscriberService.createOAuthApplicationByApplicationInfo(APIKeyMgtSubscriberService.java:153)
is-as-km_1      |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
is-as-km_1      |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
is-as-km_1      |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
is-as-km_1      |       at java.lang.reflect.Method.invoke(Method.java:498)
is-as-km_1      |       at org.apache.axis2.rpc.receivers.RPCUtil.invokeServiceClass(RPCUtil.java:212)
is-as-km_1      |       at org.apache.axis2.rpc.receivers.RPCMessageReceiver.invokeBusinessLogic(RPCMessageReceiver.java:117)
is-as-km_1      |       at org.apache.axis2.receivers.AbstractInOutMessageReceiver.invokeBusinessLogic(AbstractInOutMessageReceiver.java:40)
is-as-km_1      |       at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:110)
is-as-km_1      |       at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
is-as-km_1      |       at org.apache.axis2.transport.http.HTTPTransportUtils.processHTTPPostRequest(HTTPTransportUtils.java:173)
is-as-km_1      |       at org.apache.axis2.transport.http.AxisServlet.doPost(AxisServlet.java:147)
is-as-km_1      |       at org.wso2.carbon.core.transports.CarbonServlet.doPost(CarbonServlet.java:232)
is-as-km_1      |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
is-as-km_1      |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
is-as-km_1      |       at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
is-as-km_1      |       at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)
is-as-km_1      |       at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)
is-as-km_1      |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
is-as-km_1      |       at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)
is-as-km_1      |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
is-as-km_1      |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
is-as-km_1      |       at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
is-as-km_1      |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
is-as-km_1      |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
is-as-km_1      |       at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:72)
is-as-km_1      |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
is-as-km_1      |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
is-as-km_1      |       at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
is-as-km_1      |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
is-as-km_1      |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
is-as-km_1      |       at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:65)
is-as-km_1      |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
is-as-km_1      |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
is-as-km_1      |       at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
is-as-km_1      |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
is-as-km_1      |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
is-as-km_1      |       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
is-as-km_1      |       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
is-as-km_1      |       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
is-as-km_1      |       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
is-as-km_1      |       at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80)
is-as-km_1      |       at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:91)
is-as-km_1      |       at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:60)
is-as-km_1      |       at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)
is-as-km_1      |       at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)
is-as-km_1      |       at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)
is-as-km_1      |       at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)
is-as-km_1      |       at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)
is-as-km_1      |       at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)
is-as-km_1      |       at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
is-as-km_1      |       at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)
is-as-km_1      |       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
is-as-km_1      |       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
is-as-km_1      |       at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
is-as-km_1      |       at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
is-as-km_1      |       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1775)
is-as-km_1      |       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1734)
is-as-km_1      |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
is-as-km_1      |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
is-as-km_1      |       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
is-as-km_1      |       at java.lang.Thread.run(Thread.java:748)
is-as-km_1      | Caused by: java.lang.NullPointerException
is-as-km_1      |       at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.delete(MountHandler.java:492)
is-as-km_1      |       at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.delete(HandlerManager.java:2628)
is-as-km_1      |       ... 76 more
`
**Affected Product Version:**
 Identity Server as a Key Manager 5.5.0

**OS, DB, other environment details and versions:**    
Docker Compose 
APIM 2.2.0 + Analytics 2.2.0 + IS-KM 5.5.0

**Steps to reproduce:**
Logging to Store as "admin" and create an Access token for an Application.
Configuration files for IS-KM can be found [here.](https://github.com/wso2/docker-apim/tree/master/docker-compose/APIM-ISasKM-with-Analytics/is-as-km/repository)

**Comment by pubudu538** [comment] 2018-09-07 12:38
Were you able to find the root cause for the issue?

**Comment by kavishkafernando** [comment] 2020-11-27 09:23
Closing the issue due to insufficient information. Please re-open the issue if it gets reproduced.

**Closed by kavishkafernando** 2020-11-27 09:23 UTC
