### ISSUE TITLE
Test console related issues

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-apim#10550] opened 2021-03-30 06:14 UTC
### Description:
The following issues are there in the test console in the publisher.

**Issue 1**
1. Login in as API creator.
2. Test console is not listed in the left side menu of the publisher. Only available via overview page.

**Issue 2**
1. When accessing an API via test console, it loads http url instead of the https url under servers. Due to protocol mismatch, the request fails. Need to load https url by default.
2. Cors related issue is already fixed. https://github.com/wso2/product-apim/pull/10315

**Issue 3**
1. When logged in as publisher, test console should be disable. At the moment when you login in as publisher, you cannot generate a test token.

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by malinthaprasan** [comment] 2021-03-31 10:27
Reduced the priority as none of the above issues are blockers.

**Comment by tmkasun** [comment] 2021-04-02 06:44
- `Issue 1` is fixed already 
- Issue 2 can be reproduced in master @renuka-fernando Do you have any insight on this ?
- > When logged in as publisher, test console should be disabled
  - I doubt whether this is valid @pubudu538  ? IMO  testing should be enabled for all the users at all times (with conditional messages in relevant states) ?

**Comment by pubudu538** [comment] 2021-04-02 06:47
+1 to support all the users testing the API.

**Comment by tmkasun** [comment] 2021-04-06 10:14
Update on the issue:

- Issue 2 is already fixed in the master
- Issue 3 is no longer valid since we agree to allow API testing for all roles

As per the above comments, all the issues are fixed now, hence closing the issue

**Closed by tmkasun** 2021-04-06 10:14 UTC
Labels: API-M 4.0.0, Feature/TestConsole/Publisher, Priority/Normal, React-UI, Severity/Major, Type/Bug
