### ISSUE TITLE
Import/export CLI tool mentioned -q flag

### ISSUE THREAD

**Issue by Mariangela** [wso2/product-apim#3519] opened 2018-07-06 14:16 UTC
**Description:**
In the help option of the import/export CLI tool of the list apis command the -q --query flag is mentioned in the examples. However, this flag is not used in APIM 2.5.0. Therefore, it will be good if we can update the help information in the CLI import/export tool.

**Suggested Labels:**
2.5.0, improvement

**Suggested Assignees:**
Uvindra

**Affected Product Version:**
API-M 2.5.0 import/export CLI tool

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by rmsamitha** [comment] 2022-01-28 04:10
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:11 UTC
