### ISSUE TITLE
Tenant domain warnings when invoking an api

### ISSUE THREAD

**Issue by selakap** [wso2/product-apim#9852] opened 2021-02-03 09:58 UTC
### Description:
When invoking an API (which belongs to a tenant) using apim 3.0.0 (fresh and the wum updated pack), there is a warn message as below(but the invocation was successful)

**TID: [1] [] [2021-02-03 12:40:12,218]  WARN {org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver} - Tenant domain is not available in tenant request message context, hence it might not be set in the thread local carbon context**

### Steps to reproduce:
- Create a new tenant
- Log into publisher using new tenant admin
- Created an API and invoke it
- Observed the warn message but the invocation was successful

### Affected Product Version:
 Wso2 apim 3.0.0

**Comment by HeshanSudarshana** [comment] 2021-04-08 18:37
Closing since the issue is fixed

**Closed by HeshanSudarshana** 2021-04-08 18:37 UTC
Labels: Priority/Normal, Type/Bug
