### ISSUE TITLE
Building payloads through a global synapse handler causing OOM in gateway

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#9672] opened 2020-12-31 07:54 UTC
### Steps to reproduce:
1. Create a global synapse handler and engage to APIM. Build the payload using RelayUtils.buildMessage() in all the 4 flows  handleRequestInFlow,  handleRequestOutFlow,  handleResponseInFlow,  handleResponseOutFlow. 
2. Create a backend that sends a payload with a non-common content type such as application/error+json
3. Create an API in a tenant and use the backend as above
4. Send a request.

Below OOM error can be seen.
```
TID: [-1] [] [2020-12-19 07:42:45,327] ERROR {org.apache.axis2.transport.base.threads.NativeWorkerPool} - Uncaught exception java.lang.OutOfMemoryError: Java heap space
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:233)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
	at org.apache.synapse.commons.json.JsonUtil.writeJsonStream(JsonUtil.java:1168)
	at org.apache.synapse.commons.json.JsonUtil.writeAsJson(JsonUtil.java:385)
	at org.apache.synapse.commons.json.JsonStreamFormatter.writeTo(JsonStreamFormatter.java:70)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.submitResponse(PassThroughHttpSender.java:601)
	at org.apache.synapse.transport.passthru.PassThroughHttpSender.invoke(PassThroughHttpSender.java:285)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.wso2.carbon.core.multitenancy.transports.TenantTransportSender.invoke(TenantTransportSender.java:292)
	at org.apache.axis2.engine.AxisEngine.send(AxisEngine.java:442)
	at org.apache.synapse.core.axis2.Axis2Sender.sendBack(Axis2Sender.java:220)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.send(Axis2SynapseEnvironment.java:554)
	at org.apache.synapse.mediators.builtin.SendMediator.mediate(SendMediator.java:120)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.rest.Resource.process(Resource.java:331)
	at org.apache.synapse.rest.API.process(API.java:381)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:149)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:58)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:327)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:583)
	at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:197)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.processResponse(MultitenantMessageReceiver.java:189)
	at org.wso2.carbon.core.multitenancy.MultitenantMessageReceiver.receive(MultitenantMessageReceiver.java:91)

```

In super tenant flow this doesn't give OOM.
In both flows, the client doesn't get an error response.

Issue can be resolved by removing "org.apache.synapse.commons.json.JsonInputStream" axis2 message context property in the response flow during error situation while building the payload. 
Ex: 

**org.apache.synapse.transport.passthru.util.RelayUtils**
```
    public static void consumeAndDiscardMessage(MessageContext msgContext) throws AxisFault {
        final Pipe pipe = (Pipe) msgContext.getProperty(PassThroughConstants.PASS_THROUGH_PIPE);
        if (pipe != null) {
            try {
                while (!pipe.isProducerCompleted() || pipe.isConsumeRequired()) {
                    consume(pipe);
                    if (pipe.isProducerError()) {
                        break;
                    }
                }
            } catch (IOException exception) {
                handleException("Error when consuming the input stream to discard", exception);
            }
        }
        msgContext.removeProperty(ORG_APACHE_SYNAPSE_COMMONS_JSON_JSON_INPUT_STREAM);  <<<
    }

```

However this doesn't fix the issue of not sending any response to the client. 

### Affected Product Version:
3.1.0

**Comment by Nirothipan** [comment] 2021-04-02 08:33
As per @chashikajw, this issue wasn't reproducible in master. We need to double check and close this one.

**Comment by tharikaGitHub** [comment] 2022-11-01 05:21
Closing as the issue is not reproducible in the master branch.

**Closed by tharikaGitHub** 2022-11-01 05:21 UTC
Labels: Priority/High, WUM, Component/APIM, 4.2.0-M1
