### ISSUE TITLE
Basic Auth property appending to non secured backend resources in API Products

### ISSUE THREAD

**Issue by dileepagayan** [wso2/product-apim#12562] opened 2022-03-06 15:37 UTC
### Description:
When adding the resources to the API product with backend secured and non-secured resources, all the resources are appending with basic auth headers.

### Steps to reproduce:

- Get the latest WUMupdated API manager 4.0.0 product
- Create an API 1 with endpoint security (Basic Auth). Add some resources
- Create an API 2 without endpoint security
- Create an API Product using resources in API 1 and API 2
- Check the synapse configuration generated for the API product. we can see the basic auth header property is appended to the none endpoint secured resources as well.

### Affected Product Version:
API Manager 4.0.0

**Comment by HeshanSudarshana** [comment] 2022-11-30 08:42
Closing the issue since the issue is no longer reproducible.

**Closed by HeshanSudarshana** 2022-11-30 08:42 UTC
Labels: Type/Bug, Priority/Normal
