### ISSUE TITLE
API publish can be done with invalid endpoint url

### ISSUE THREAD

**Issue by aaujayasena** [wso2/product-apim#4048] opened 2018-12-04 08:35 UTC
**Description:**
API publish can be done with the invalid endpoint url for sandbox and production. 

**Suggested Labels:**
Product Scenario

**Affected Product Version:**
APIM 2.6

**OS, DB, other environment details and versions:**    
DB: H2

**Steps to reproduce:**
01. Design API in API publisher
02. Implement API with invalid production or sand box endpoint url (Ex: testurl)
03. Publish the API

**Comment by rmsamitha** [comment] 2022-01-28 04:04
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:04 UTC
Labels: 2.6.0
