### ISSUE TITLE
[UX] APIM carbon console - Add user flow  - UI issues

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2890] opened 2018-03-07 04:54 UTC
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***

Error recognition - Is it precisely indicate the problem
Flexibility and efficiency of use - Does the task cater to both experienced and inexperienced users
Match between system and the real world - Is design match with real world conventions, concepts

***Related task:***
Create users and assign roles to users

***Issues and proposed solutions:***

APIM Carbon console - Add New User screen 

- Should have a guideline about Username policy pattern. The error message appears as password policy violated. Need to define the policy. 

- If you click Next without entering username, password etc the error message is "Username pattern policy violated". This can be reworded to "Enter all required fields".

- When a username that is already existing in the system is entered, the error message is "Could not add user PRIMARY/minoli. Error is: UserAlreadyExisting:Username already exists in the system. Pick another username."
Reword the error message to "Could not add user PRIMARY/minoli. The username already exists in the system. Enter another username".

- The word 'user name' should be one word.

- Change Password screen - When a wrong Current Password is entered, the error message is "Could not change password of admin. Error is: Error while updating password. Wrong old credential provided". This can be reworded to "Could not change the password of <username>. The current password you entered is incorrect".

- Assign Roles screen - There is a section called "Unassigned Roles". This is empty if there are no unassigned roles. When this is empty, it should have a message saying "No unassigned roles found".
	
**Suggested Labels**
UX, Improvements, 2.1.0

**Comment by rmsamitha** [comment] 2022-01-28 04:37
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:37 UTC
Labels: Priority/Low, Affected/2.1.0
