### ISSUE TITLE
When starting the API manger as Gateway worker profile, it is throwing warnings and errors related to TM side

### ISSUE THREAD

**Issue by nadeepoornima** [wso2/product-apim#5048] opened 2019-06-19 09:13 UTC
**Problem**

When starting the APIM as a Gateway worker profile it is showing the following warning.

```
WARN - APIManagerComponent Exception occurred while creating WSO2 Event Adapter. Request Blocking may not work properly
org.wso2.carbon.event.output.adapter.core.exception.OutputEventAdapterException: Output Event Adapter not created as no adapter factory is registered with type wso2event
	at org.wso2.carbon.event.output.adapter.core.internal.CarbonOutputEventAdapterService.create(CarbonOutputEventAdapterService.java:90)
	at org.wso2.carbon.apimgt.impl.internal.APIManagerComponent.configureEventPublisherProperties_aroundBody40(APIManagerComponent.java:645)
	at org.wso2.carbon.apimgt.impl.internal.APIManagerComponent.configureEventPublisherProperties(APIManagerComponent.java:623)
	at org.wso2.carbon.apimgt.impl.internal.APIManagerComponent.activate_aroundBody0(APIManagerComponent.java:237)
	at org.wso2.carbon.apimgt.impl.internal.APIManagerComponent.activate(APIManagerComponent.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:451)
	at org.wso2.carbon.core.init.CarbonServerManager.initializeCarbon(CarbonServerManager.java:515)
	at org.wso2.carbon.core.init.CarbonServerManager.start(CarbonServerManager.java:220)
	at org.wso2.carbon.core.internal.CarbonCoreServiceComponent.activate(CarbonCoreServiceComponent.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
	at org.eclipse.equinox.http.servlet.internal.Activator.registerHttpService(Activator.java:81)
	at org.eclipse.equinox.http.servlet.internal.Activator.addProxyServlet(Activator.java:60)
	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.init(ProxyServlet.java:40)
	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.init(DelegationServlet.java:38)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1230)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1174)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1066)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5409)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5707)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1707)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1697)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
errors:
```
ERROR - DataEndpointConnectionWorker Error while trying to connect to the endpoint. Cannot borrow client for ssl://localhost:9711
org.wso2.carbon.databridge.agent.exception.DataEndpointAuthenticationException: Cannot borrow client for ssl://localhost:9711
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:147)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.run(DataEndpointConnectionWorker.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.databridge.agent.exception.DataEndpointException: Error while opening socket to localhost:9711. Connection refused (Connection refused)
	at org.wso2.carbon.databridge.agent.endpoint.binary.BinarySecureClientPoolFactory.createClient(BinarySecureClientPoolFactory.java:75)
	at org.wso2.carbon.databridge.agent.client.AbstractClientPoolFactory.makeObject(AbstractClientPoolFactory.java:39)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1212)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:137)
	... 6 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:426)
	at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:88)
	at org.wso2.carbon.databridge.agent.endpoint.binary.BinarySecureClientPoolFactory.createClient(BinarySecureClientPoolFactory.java:58)
	... 9 more
```
**Affected version**
APIM 2.6.0

**Reproduced Steps**

1. Take a WUM updated pack of APIM 2.6.0 and unzip.
2. Go to "bin" folder and run the "profileSetup.sh" script as "**_sh profileSetup.sh -Dprofile=gateway-worker_**" 
The output of that run as follows.
```
Starting to optimize API Manager for the Gateway worker profile
profileSetup.sh: 1: profileSetup.sh: xmllint: not found
profileSetup.sh: 1: profileSetup.sh: xmllint: not found
[2019-06-19 14:20:00:083] INFO - Removed the client-registration#v0.14.war file from ../repository/deployment/server/webapps
[2019-06-19 14:20:00:095] INFO - Removed the am#sample#calculator#v1.war file from ../repository/deployment/server/webapps
[2019-06-19 14:20:00:105] INFO - Removed the api#am#store#v0.14.war file from ../repository/deployment/server/webapps
[2019-06-19 14:20:00:113] INFO - Removed the api#am#publisher#v0.14.war file from ../repository/deployment/server/webapps
[2019-06-19 14:20:00:116] INFO - Removed the authenticationendpoint.war file from ../repository/deployment/server/webapps
[2019-06-19 14:20:00:123] INFO - Removed the api#identity#consent-mgt#v1.0.war file from ../repository/deployment/server/webapps
[2019-06-19 14:20:00:128] INFO - Removed the api#am#admin#v0.14.war file from ../repository/deployment/server/webapps
[2019-06-19 14:20:00:130] INFO - Removed the oauth2.war file from ../repository/deployment/server/webapps
[2019-06-19 14:20:00:134] INFO - Removed the throttle#data#v1.war file from ../repository/deployment/server/webapps
[2019-06-19 14:20:00:166] INFO - Removed store directory from ../repository/deployment/server/jaggeryapps
[2019-06-19 14:20:00:186] INFO - Removed admin directory from ../repository/deployment/server/jaggeryapps
[2019-06-19 14:20:00:221] INFO - Removed publisher directory from ../repository/deployment/server/jaggeryapps
Finished the optimizations
```
3. Then run the wso2server.sh file as "sh wso2server.sh -Dprofile=traffic-manager". While starting the server the above warnning and errors are showing.

**Overcome the issue**

Could able to overcome the issue by setting the ``<PolicyDeployer>`` config as false in the api-manger.xml file. But that was not able to fix the errors(ERROR - DataEndpointConnectionWorker Error while trying to connect to the endpoint. Cannot borrow client for ssl://localhost:9711).

**OS version**
Ubuntu 18.04.2 LTS

**Comment by AmaliMatharaarachchi** [comment] 2019-09-11 11:36
@nadeepoornima 
> Could able to overcome the issue by setting the <PolicyDeployer> config as false in the api-manger.xml file.  

profileSetup.sh already configure this as [1].
https://github.com/wso2/product-apim/blob/9c85a4df3068487669ccbdedbb799a4732a88d3f/modules/distribution/product/src/main/startup-scripts/profileSetup.sh#L325

As per your log it seems that that script was not properly executed due to missing xmllint which may have been the cause of the above issue.
> Starting to optimize API Manager for the Gateway worker profile
> profileSetup.sh: 1: profileSetup.sh: xmllint: not found
> profileSetup.sh: 1: profileSetup.sh: xmllint: not found

Please install xmllint before executing the profileSetup.sh. 
e.g. apt-get install libxml2-utils

**Comment by chamilaadhi** [comment] 2024-03-06 04:01
Closing since no active engagement

**Closed by chamilaadhi** 2024-03-06 04:01 UTC
Labels: Type/Bug, 2.6.0
