### ISSUE TITLE
Unable to download the mediation policies in publisher UI

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#8104] opened 2020-05-19 18:57 UTC
### Description:
In wso2am-3.0.0+1588257170513 and wso2am-3.0.0+1589560096020 when trying to download the mediation policies via publisher UI, nothing is getting downloaded. In the network tab, we were able to see the request being sent and receiving a successful response. But the UI is not prompting for download.  
![image](https://user-images.githubusercontent.com/20519000/82366759-57c72c80-9a30-11ea-9f62-35314d61f6c2.png)

### Steps to reproduce:
1. Navigate to publisher portal
2. Select Runtime Configurations --> Message Mediation --> Under common policies or custom policies click on the download arrow
Note: If you are selecting the custom policy make sure that you have already uploaded a mediation policy to it.

### Affected Product Version:
wso2am-3.0.0

**Comment by praminda** [comment] 2020-05-20 03:53
Duplicate of #7618

**Closed by praminda** 2020-05-20 03:53 UTC
Labels: Priority/Normal, Type/Bug
