### ISSUE TITLE
provide api bandwidth / size of the message 

### ISSUE THREAD

**Issue by vanjikumaran** [wso2/product-apim#3222] opened 2018-04-18 23:29 UTC
**Description:**
provide api bandwidth/size of the message
currently API-M analytics does not provide bandwidth information, how can we get this information. Bandwidth information is needed to bill customers based on bandwidth usage

**Suggested Labels:**
New Feature Request

**Comment by vanjikumaran** [comment] 2020-05-06 18:56
Any update on this?

**Comment by ruks** [comment] 2020-11-27 09:42
@vanjikumaran in analytics response size is published to analytics by default. So you can use it for response path bandwidth. But the request path payload size is not published. For that, you can implement a custom mediation sequence and include request path payload size to the same event.

**Comment by rmsamitha** [comment] 2022-01-28 04:17
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:17 UTC
