### ISSUE TITLE
DB script for MySQL 5.7 complain about max key length

### ISSUE THREAD

**Issue by chintana-zz** [wso2/product-apim#3736] opened 2018-09-14 06:54 UTC
**Description:**
$ mysql -u root -p test2 < apimgt/mysql5.7.sql 
Enter password: 
ERROR 1071 (42000) at line 168: Specified key was too long; max key length is 3072 bytes

**Affected Product Version:**
WSO2 API Manager 2.5.0 (latest WUM updated pack)

**OS, DB, other environment details and versions:** 
macOS High Sierra 10.13.6
$ mysql --version
mysql  Ver 14.14 Distrib 5.7.22, for osx10.13 (x86_64) using  EditLine wrapper

**Steps to reproduce:**
Unzip pack, execute APIM dbscripts on a MySQL 5.7.22 server

**Comment by gusto2** [comment] 2018-10-25 08:51
The same is valid for wso2am-2.6.0

**Comment by rnavagamuwa** [comment] 2019-06-27 09:32
I'm also getting this on APIM 2.6.

#### Affected Product Version:
WSO2 API Manager 2.6.0

#### OS, DB, other environment details and versions:
macOS Mojave 10.14.5
mysql  Ver 8.0.15 for macos10.14 on x86_64 (MySQL Community Server - GPL)

Btw the workaround mentioned by @gusto2 worked.

**Comment by rmsamitha** [comment] 2022-01-28 04:10
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:10 UTC
