### ISSUE TITLE
[Store] Error when viewing more options of API Product

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#5923] opened 2019-09-27 10:05 UTC
Steps to reproduce:
1. Deploy sample API Product
2. View it in Store
3. Click on more - Blank page is rendered with following error:
`ERROR - APIMappingUtil Unrecognized state : null`

![api](https://user-images.githubusercontent.com/19728269/65761446-6a58c280-e13c-11e9-9423-d0c99ec76b6f.png)

**Comment by chamilaadhi** [comment] 2019-10-07 11:08
closing since duplicate of https://github.com/wso2/product-apim/issues/5989

**Closed by chamilaadhi** 2019-10-07 11:08 UTC
Labels: 3.0.0-alpha, Store
