### ISSUE TITLE
[UX] Need to provide confirmation on actions for ./wso2server.sh --cleanRegistry

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#2872] opened 2018-03-06 11:13 UTC
**Description:**
$subject

***Not fulfilling checklist items***
--Is there a confirmation option before committed to actions?

***Related task:****
Error prevention

***Issue:***
 Need to provide confirmation on actions for ./wso2server.sh --cleanRegistry

***Proposed Solution:***
Add confirmation if the user runs with --cleanRegistry argument
	
**Affected Product Version:**
2.1.0

**Comment by rmsamitha** [comment] 2022-01-28 04:42
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:42 UTC
Labels: Affected/2.1.0
