### ISSUE TITLE
SocketException thrown when invoke the api with load test using expired access token

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2201] opened 2018-01-04 12:57 UTC
**Description:**
SocketException thrown when invoke the api with load test using expired access token

**Suggested Labels:**
APIM-2.2.0
Type/bug
Priority/high
Severity/high

**Suggested Assignees:**

**Affected Product Version:**
2.1.0-update4

**OS, DB, other environment details and versions:**    
ubuntu 15.10
standalone pack

**Steps to reproduce:**
- Add an api and an app
- Assign subscription tier : bronze (1000Req/min)
- Invoke the api with load using jmeter script with
    1000 users
    1 loop
    TP  48.4/sec
Partialy the requests are pass with error code [1]; But observed an execption [2] for remaining requests.

[1]
`{"fault":{"code":900901,"message":"Invalid Credentials","description":"Access failure for API: /stocks/1.0.0, version: 1.0.0 status: (900901) - Invalid Credentials. Make sure you have given the correct access token"}}`

[2]
`java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:158)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:82)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:271)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:281)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:257)
	at org.apache.jmeter.protocol.http.sampler.hc.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:199)
	at org.apache.jmeter.protocol.http.sampler.MeasuringConnectionManager$MeasuredConnection.receiveResponseHeader(MeasuringConnectionManager.java:212)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:684)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:486)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.executeRequest(HTTPHC4Impl.java:654)
	at org.apache.jmeter.protocol.http.sampler.HTTPHC4Impl.sample(HTTPHC4Impl.java:413)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerProxy.sample(HTTPSamplerProxy.java:74)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1189)
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1178)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:491)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:425)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:254)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by nuwand** [comment] 2018-01-05 03:10
This looks like an exception on JMeter. Are you seeing exceptions on the server log?

Please see [1] as well to get an idea of the possible causes of this issue occurring on JMeter

[1] - https://github.com/ratpack/ratpack/issues/1242

**Comment by chamindias** [comment] 2018-02-20 12:08
Hi Kavitha,
Can you please provide the information to the [above comment](https://github.com/wso2/product-apim/issues/2201#issuecomment-355462067)? Reducing the priority based on the above comment.

**Comment by dushaniw** [comment] 2020-02-11 06:49
Closing the issue as the requested resources has not been provided, and we could not reproduce the issue. Please feel free to reopen if you run into the same issue again.

**Closed by dushaniw** 2020-02-11 06:49 UTC
Labels: 2.2.0, Priority/Normal, Severity/Critical, Type/Bug
