### ISSUE TITLE
API resources page UI issue

### ISSUE THREAD

**Issue by rmsamitha** [wso2/product-apim#5342] opened 2019-08-22 09:30 UTC
Text area to add a summary description to API resource summary shows a placeholder text as "Click here to add summary", if there is no summary text added yet. This text area doesn't seem as a placeholder. It seems just as a normal text.  
![Screen Shot 2019-08-22 at 2 52 35 PM](https://user-images.githubusercontent.com/2484781/63503160-973a0a00-c4ec-11e9-8514-f74e3d9008e5.png)

**Comment by sanjulamadurapperuma** [comment] 2019-10-11 04:10
Cannot reproduce this issue anymore in the new UI.

![image](https://user-images.githubusercontent.com/32578617/66623848-3042f280-ec0b-11e9-8c03-52dc293290ac.png)

**Comment by tmkasun** [comment] 2020-01-31 09:13
Closing this issue as per the above comment

**Closed by tmkasun** 2020-01-31 09:13 UTC
Labels: 3.0.0, Publisher
