### ISSUE TITLE
Test case 4.7.3: Unable to import an application more than one environment.

### ISSUE THREAD

**Issue by ThamiliniRam** [wso2/product-apim#6044] opened 2019-10-01 06:26 UTC
Test case:
4.7.3 Migrate applications across different environments (eg. Dev, QA, UAT, Prod)

When try to import an application to different environments, it does not allow to import a particular application to another environment. It allows to import for only one environment.

**Comment by dushaniw** [comment] 2019-10-15 09:07
Cannot reproduce the issue. 
Once after importing the application for the first time to an environment, you cannot import it again to the same environment.
If you have already exported the application with keys and imported it. Then if you try to import it back for a different user with keys, throwing an error is expected, as we cannot create the same OAuth app. 

Closing the issue, as we cannot reproduce.

**Closed by dushaniw** 2019-10-15 09:07 UTC
Labels: 3.0.0
