### ISSUE TITLE
Changing the context of an API is not supported

### ISSUE THREAD

**Issue by madeesha** [wso2/product-apim#4186] opened 2019-01-21 05:34 UTC
**Description:**
Currently, APIM product does not support changing the context of an API. It cannot be done without creating a new API. It would be great if we can support this feature in an upcoming version and it would be useful especially in the development time.

**Comment by rmsamitha** [comment] 2022-01-27 13:28
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-27 13:28 UTC
Labels: Type/Improvement
