### ISSUE TITLE
User with creator permission only can add one API property

### ISSUE THREAD

**Issue by Chamindu36** [wso2/product-apim#10527] opened 2021-03-30 05:49 UTC
### Description:
When creating API properties, a user with creator permissions can only create one API property. Once on API property is created the Add New Property button is disappeared.
![Screenshot from 2021-03-30 11-15-22](https://user-images.githubusercontent.com/42435576/112939784-b168af00-9149-11eb-840f-da33bfd4fc14.png)

### Steps to reproduce:
1. Create a user with Creator permissions.
2. log in to the Publisher portal and Create an API.
3. Create a new API property and save it.
4. Then try to create another one.

### Affected Product Version:
4.0.0

### Environment details (with versions):
- OS: Linux 
- Client:
- Env (Docker/K8s):
- Browser - Chrome

---

**Comment by malinthaprasan** [comment] 2021-04-09 16:18
Duplicate of https://github.com/wso2/product-apim/issues/10778 
Seems this is not related to the lifecycle actions.

**Closed by malinthaprasan** 2021-04-09 16:18 UTC
Labels: API-M 4.0.0, Feature/APIProperties, Priority/Normal, React-UI, Type/Bug
