### ISSUE TITLE
Cannot add scopes to API

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/product-apim#5453] opened 2019-09-02 13:58 UTC
Adding scope via REST API doesn't reflect scope changes at the backend side.

See `"scopes":[ .. ]` section

**Request**
```
PUT /api/am/publisher/v1.0/apis/e4dd263c-68b8-4762-bfe2-b3dccbb71fec HTTP/1.1
{  
   "id":"e4dd263c-68b8-4762-bfe2-b3dccbb71fec",
   "name":"api1",
   "description":null,
   "context":"/api1",
   "version":"2.0.0",
   "provider":"admin",
   "lifeCycleStatus":"CREATED",
   "wsdlUri":null,
   "responseCachingEnabled":false,
   "cacheTimeout":300,
   "destinationStatsEnabled":null,
   "hasThumbnail":null,
   "isDefaultVersion":true,
   "enableSchemaValidation":false,
   "type":"HTTP",
   "transport":[  
      "http",
      "https"
   ],
   "tags":[  

   ],
   "policies":[  
      "Unlimited"
   ],
   "apiThrottlingPolicy":"Unlimited",
   "authorizationHeader":null,
   "securityScheme":[  
      "oauth2",
      "oauth_basic_auth_mandatory"
   ],
   "maxTps":null,
   "visibility":"PUBLIC",
   "visibleRoles":[  

   ],
   "visibleTenants":[  

   ],
   "endpointSecurity":null,
   "gatewayEnvironments":[  
      "Production and Sandbox"
   ],
   "labels":[  

   ],
   "mediationPolicies":[  

   ],
   "subscriptionAvailability":"ALL_TENANTS",
   "subscriptionAvailableTenants":[  

   ],
   "additionalProperties":{  

   },
   "monetization":null,
   "accessControl":"NONE",
   "accessControlRoles":[  

   ],
   "businessInformation":{  
      "businessOwner":null,
      "businessOwnerEmail":null,
      "technicalOwner":null,
      "technicalOwnerEmail":null
   },
   "corsConfiguration":{  
      "corsConfigurationEnabled":false,
      "accessControlAllowOrigins":[  
         "*"
      ],
      "accessControlAllowCredentials":false,
      "accessControlAllowHeaders":[  
         "authorization",
         "Access-Control-Allow-Origin",
         "Content-Type",
         "SOAPAction"
      ],
      "accessControlAllowMethods":[  
         "GET",
         "PUT",
         "POST",
         "DELETE",
         "PATCH",
         "OPTIONS"
      ]
   },
   "workflowStatus":null,
   "createdTime":"2019-09-02 18:50:59.596",
   "lastUpdatedTime":"2019-09-02 18:50:59.596",
   "endpointConfig":{  
      "endpoint_type":"http",
      "sandbox_endpoints":{  
         "url":"https://localhost"
      },
      "production_endpoints":{  
         "url":"https://localhost"
      }
   },
   "endpointImplementationType":"ENDPOINT",
   "scopes":[  
      {  
         "name":"aaa",
         "bindings":{  
            "type":"role",
            "values":[  
               "admin"
            ]
         }
      }
   ],
   "operations":[  
      {  
         "id":"",
         "target":"/*",
         "verb":"GET",
         "authType":"Application & Application User",
         "throttlingPolicy":"Unlimited",
         "scopes":[  

         ]
      },
      {  
         "id":"",
         "target":"/*",
         "verb":"PUT",
         "authType":"Application & Application User",
         "throttlingPolicy":"Unlimited",
         "scopes":[  

         ]
      },
      {  
         "id":"",
         "target":"/*",
         "verb":"POST",
         "authType":"Application & Application User",
         "throttlingPolicy":"Unlimited",
         "scopes":[  

         ]
      },
      {  
         "id":"",
         "target":"/*",
         "verb":"DELETE",
         "authType":"Application & Application User",
         "throttlingPolicy":"Unlimited",
         "scopes":[  

         ]
      },
      {  
         "id":"",
         "target":"/*",
         "verb":"PATCH",
         "authType":"Application & Application User",
         "throttlingPolicy":"Unlimited",
         "scopes":[  

         ]
      }
   ],
   "threatProtectionPolicies":null
}
```

**Response**

```
{  
   "id":"e4dd263c-68b8-4762-bfe2-b3dccbb71fec",
   "name":"api1",
   "description":null,
   "context":"/api1",
   "version":"2.0.0",
   "provider":"admin",
   "lifeCycleStatus":"CREATED",
   "wsdlUri":null,
   "responseCachingEnabled":false,
   "cacheTimeout":300,
   "destinationStatsEnabled":null,
   "hasThumbnail":null,
   "isDefaultVersion":true,
   "enableSchemaValidation":false,
   "type":"HTTP",
   "transport":[  
      "http",
      "https"
   ],
   "tags":[  

   ],
   "policies":[  
      "Unlimited"
   ],
   "apiThrottlingPolicy":"Unlimited",
   "authorizationHeader":null,
   "securityScheme":[  
      "oauth2",
      "oauth_basic_auth_mandatory"
   ],
   "maxTps":null,
   "visibility":"PUBLIC",
   "visibleRoles":[  

   ],
   "visibleTenants":[  

   ],
   "endpointSecurity":null,
   "gatewayEnvironments":[  
      "Production and Sandbox"
   ],
   "labels":[  

   ],
   "mediationPolicies":[  

   ],
   "subscriptionAvailability":"ALL_TENANTS",
   "subscriptionAvailableTenants":[  

   ],
   "additionalProperties":{  

   },
   "monetization":null,
   "accessControl":"NONE",
   "accessControlRoles":[  

   ],
   "businessInformation":{  
      "businessOwner":null,
      "businessOwnerEmail":null,
      "technicalOwner":null,
      "technicalOwnerEmail":null
   },
   "corsConfiguration":{  
      "corsConfigurationEnabled":false,
      "accessControlAllowOrigins":[  
         "*"
      ],
      "accessControlAllowCredentials":false,
      "accessControlAllowHeaders":[  
         "authorization",
         "Access-Control-Allow-Origin",
         "Content-Type",
         "SOAPAction"
      ],
      "accessControlAllowMethods":[  
         "GET",
         "PUT",
         "POST",
         "DELETE",
         "PATCH",
         "OPTIONS"
      ]
   },
   "workflowStatus":null,
   "createdTime":"2019-09-02 18:53:37.245",
   "lastUpdatedTime":"2019-09-02 18:53:37.245",
   "endpointConfig":{  
      "endpoint_type":"http",
      "sandbox_endpoints":{  
         "url":"https://localhost"
      },
      "production_endpoints":{  
         "url":"https://localhost"
      }
   },
   "endpointImplementationType":"ENDPOINT",
   "scopes":[  

   ],
   "operations":[  
      {  
         "id":"",
         "target":"/*",
         "verb":"GET",
         "authType":"Application & Application User",
         "throttlingPolicy":"Unlimited",
         "scopes":[  

         ]
      },
      {  
         "id":"",
         "target":"/*",
         "verb":"PUT",
         "authType":"Application & Application User",
         "throttlingPolicy":"Unlimited",
         "scopes":[  

         ]
      },
      {  
         "id":"",
         "target":"/*",
         "verb":"POST",
         "authType":"Application & Application User",
         "throttlingPolicy":"Unlimited",
         "scopes":[  

         ]
      },
      {  
         "id":"",
         "target":"/*",
         "verb":"DELETE",
         "authType":"Application & Application User",
         "throttlingPolicy":"Unlimited",
         "scopes":[  

         ]
      },
      {  
         "id":"",
         "target":"/*",
         "verb":"PATCH",
         "authType":"Application & Application User",
         "throttlingPolicy":"Unlimited",
         "scopes":[  

         ]
      }
   ],
   "threatProtectionPolicies":null
}
```

**Comment by ruks** [comment] 2019-10-09 08:04
The issue is due to the https://github.com/wso2/product-apim/issues/5707. Hence closing.

**Closed by ruks** 2019-10-09 08:04 UTC
Labels: 3.0.0, Publisher, Severity/Critical, Type/Bug
