### ISSUE TITLE
Operations that users can perform on a shared application is not clearly defined

### ISSUE THREAD

**Issue by uvindra** [wso2/product-apim#2690] opened 2018-02-06 07:37 UTC
Application owners are able to share their Applications with others users who belong to the same group[1]. This allows the Application owner to share their API subscription with other users in the same group. The user who is sharing the App should not be able to edit the Application owners App because they do not the own the App.

Currently the experience for the operations that a user can perform on a shared Application is not very good and undefined. Improvements are required to prevent shared users from updating shared Apps.

[1] https://docs.wso2.com/display/AM210/Sharing+Applications+and+Subscriptions

**Comment by TanyaM** [comment] 2020-05-25 13:22
Needs to be fixed in 2.6.0 docs as well

**Comment by rmsamitha** [comment] 2022-01-28 04:49
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:49 UTC
Labels: Severity/Major, 2.1.0, Type/Improvement, Priority/High, Resolution/Fixed, 2.2.0
