### ISSUE TITLE
[APIM 3.0.0] Error pops up when trying to edit and save API.

### ISSUE THREAD

**Issue by shaniR** [wso2/product-apim#5571] opened 2019-09-16 09:32 UTC
1) Create API
2) Edit API Configuration section
3) Click Save.
4) Observe error popping up.
5) Observed error `[2019-09-16 14:59:35,224] ERROR - ApisApiServiceImpl No tier defined for the API` on the console.

**Comment by TanyaM** [comment] 2019-09-25 03:22
Please provide the exact inputs provided to reproduce issue.
Tried with following and issue is not reproducible after Alpha

1. Create API with Create API with **Design a New REST API** option
2. Provided inputs for all mandatory fields. ( no inputs provided for endpoint and business plans)
3. Edit the description in the API Configuration section
No error observed and got the message "Api updated successfullly"

Repeated the same with providing all inputs under step2 and still not able to reproduce.

**Comment by TanyaM** [comment] 2019-09-25 04:45
Closing as this is not reproducible after Alpha

**Closed by TanyaM** 2019-09-25 04:45 UTC
Labels: 3.0.0, Severity/Major
