### ISSUE TITLE
Could not login to APIM apps using social logins

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3463] opened 2018-06-19 09:51 UTC
**Description:**
Followed steps in [1] and [2]. After login through facebook and IS a user consent error occurs without directing to publisher/store.
![user-conscent-error](https://user-images.githubusercontent.com/9837443/41590099-ccbdd5f0-73d3-11e8-82c3-18f974d6117d.png)

[1] https://docs.wso2.com/display/AM220/Log+in+to+the+API+Store+using+Social+Media
[2] https://docs.wso2.com/display/AM220/Configuring+Identity+Server+as+IDP+for+SSO

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.2.0

**Comment by rmsamitha** [comment] 2022-01-28 04:11
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:11 UTC
Labels: Affected/2.2.0
