### ISSUE TITLE
Getting an error stack trace when invoking APIs by using opaque tokens

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/product-apim#11203] opened 2021-05-10 11:11 UTC
### Description:
Getting an error stack trace when invoking APIs by using opaque tokens (Only 1st time per gateway)

### Steps to reproduce:
- Migrate the environment from 2.2.0. version to 3.2.0 with applications that generate opaque tokens.
- After the migration, subscribe to an API with a migrated application.
- Generate an opaque access token from a migrated application.
- Invoke an API by parsing the generated access token and can see the below stack trace in the gateway. But the API invocation is getting successful. (This is only happening for the 1st invocation)

```
TID: [-1234] [] [2021-05-07 00:58:08,786] ERROR {org.wso2.carbon.apimgt.keymgt.token.JWTGenerator} - Error occurred while getting JWT Token client ID : y3vy0tcwvmJogrse9VQJeOu9P90a when getting oAuth App information org.wso2.carbon.identity.oauth.common.exception.InvalidOAuthClientException: Cannot find an application associated with the given consumer key : y3vy0tcwvmJogrse9VQJeOu9P90a
	at org.wso2.carbon.identity.oauth.dao.OAuthAppDAO.handleRequestForANonExistingConsumerKey(OAuthAppDAO.java:1183)
	at org.wso2.carbon.identity.oauth.dao.OAuthAppDAO.getAppInformation(OAuthAppDAO.java:357)
	at org.wso2.carbon.identity.oauth2.util.OAuth2Util.getAppInformationByClientId(OAuth2Util.java:1890)
	at org.wso2.carbon.apimgt.keymgt.token.JWTGenerator.populateStandardClaims_aroundBody0(JWTGenerator.java:102)
	at org.wso2.carbon.apimgt.keymgt.token.JWTGenerator.populateStandardClaims(JWTGenerator.java:63)
	at org.wso2.carbon.apimgt.keymgt.token.AbstractJWTGenerator.buildBody_aroundBody10(AbstractJWTGenerator.java:192)
	at org.wso2.carbon.apimgt.keymgt.token.AbstractJWTGenerator.buildBody(AbstractJWTGenerator.java:190)
	at org.wso2.carbon.apimgt.keymgt.token.AbstractJWTGenerator.generateToken_aroundBody6(AbstractJWTGenerator.java:147)
	at org.wso2.carbon.apimgt.keymgt.token.AbstractJWTGenerator.generateToken(AbstractJWTGenerator.java:138)
	at org.wso2.carbon.apimgt.keymgt.handlers.AbstractKeyValidationHandler.generateConsumerToken_aroundBody6(AbstractKeyValidationHandler.java:151)
	at org.wso2.carbon.apimgt.keymgt.handlers.AbstractKeyValidationHandler.generateConsumerToken(AbstractKeyValidationHandler.java:146)
	at org.wso2.carbon.apimgt.keymgt.service.APIKeyValidationService.validateKey_aroundBody0(APIKeyValidationService.java:238)
	at org.wso2.carbon.apimgt.keymgt.service.APIKeyValidationService.validateKey(APIKeyValidationService.java:82)
	at org.wso2.carbon.apimgt.gateway.handlers.security.keys.APIKeyValidatorClient.getAPIKeyData_aroundBody0(APIKeyValidatorClient.java:54)
	at org.wso2.carbon.apimgt.gateway.handlers.security.keys.APIKeyValidatorClient.getAPIKeyData(APIKeyValidatorClient.java:47)
	at org.wso2.carbon.apimgt.gateway.handlers.security.keys.WSAPIKeyDataStore.getAPIKeyData_aroundBody0(WSAPIKeyDataStore.java:53)
	at org.wso2.carbon.apimgt.gateway.handlers.security.keys.WSAPIKeyDataStore.getAPIKeyData(WSAPIKeyDataStore.java:45)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIKeyValidator.doGetKeyValidationInfo_aroundBody22(APIKeyValidator.java:259)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIKeyValidator.doGetKeyValidationInfo(APIKeyValidator.java:253)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIKeyValidator.getKeyValidationInfo_aroundBody14(APIKeyValidator.java:193)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIKeyValidator.getKeyValidationInfo(APIKeyValidator.java:137)
	at org.wso2.carbon.apimgt.gateway.handlers.security.oauth.OAuthAuthenticator.authenticate_aroundBody4(OAuthAuthenticator.java:326)
	at org.wso2.carbon.apimgt.gateway.handlers.security.oauth.OAuthAuthenticator.authenticate(OAuthAuthenticator.java:114)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate_aroundBody42(APIAuthenticationHandler.java:424)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.isAuthenticate(APIAuthenticationHandler.java:418)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest_aroundBody36(APIAuthenticationHandler.java:354)
	at org.wso2.carbon.apimgt.gateway.handlers.security.APIAuthenticationHandler.handleRequest(APIAuthenticationHandler.java:325)
	at org.apache.synapse.rest.API.process(API.java:373)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcessNonDefaultStrategy(RESTRequestHandler.java:144)
	at org.apache.synapse.rest.RESTRequestHandler.identifyAPI(RESTRequestHandler.java:164)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:95)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:73)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:331)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:99)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:367)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:188)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Affected Product Version:
3.2.0

**Comment by HiranyaKavishani** [comment] 2021-06-04 09:54
The issue is caused by `aud` claim support. It has not been added to latest. Hence close the issue

**Closed by HiranyaKavishani** 2021-06-04 09:54 UTC
Labels: Priority/Normal, Type/Bug
