### ISSUE TITLE
Keyboard navigation for search is not working for API Products

### ISSUE THREAD

**Issue by erangatl** [wso2/product-apim#8764] opened 2020-07-21 16:01 UTC
### Description:

Keyboard navigation for search is not working for API Products
The mouse click is working

![image](https://user-images.githubusercontent.com/20179540/88076809-24bc2900-cb98-11ea-99da-eb674171b3c0.png)

### Steps to reproduce:

1. Search for a product 
2. select it using the keyboard arrows
3. when pressing enter it directs to a not found page

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by Krishanx92** [comment] 2024-12-09 13:17
Cannot reproduce in latest version hence closing

**Closed by Krishanx92** 2024-12-09 13:17 UTC
Labels: Type/Bug, Priority/Normal, React-UI, Publisher
