### ISSUE TITLE
[Publisher] A user with creator role cannot edit prototyped APIs

### ISSUE THREAD

**Issue by ImalshaG** [wso2/product-apim#5970] opened 2019-09-30 04:43 UTC
A user with creator role cannot edit a prototyped API. When trying to edit it at the publisher, a message is displayed at the bottom as " You are not authorized to update particular fields of the API due to insufficient permissions".

![image](https://user-images.githubusercontent.com/47671237/65850011-9e192f80-e36a-11e9-85ff-df48f0bb55c3.png)

**Comment by chamilaadhi** [comment] 2019-10-03 04:29
duplicate of https://github.com/wso2/product-apim/issues/5775

**Closed by chamilaadhi** 2019-10-03 04:29 UTC
