### ISSUE TITLE
Error while starting a fresh pack - wso2am-4.0.0-alpha

### ISSUE THREAD

**Issue by pubudu538** [wso2/product-apim#10062] opened 2021-03-02 08:18 UTC
### Description:

The following error is thrown when starting up.

ERROR - APIMgtGatewayCacheMessageListener JMSException occurred when processing the received message 
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('a' (code 97)): was expecting comma to separate Object entries
 at [Source: (String)"{"event":{"payloadData":{"type":"gatewayUsernameCache","value":"["apim_reserved_user@carbon.super"]"}}}"; line: 1, column: 68]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840) ~[com.fasterxml.jackson.core.jackson-core_2.10.3.jar:2.9.8]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712) ~[com.fasterxml.jackson.core.jackson-core_2.10.3.jar:2.9.8]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637) ~[com.fasterxml.jackson.core.jackson-core_2.10.3.jar:2.9.8]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:2293) ~[com.fasterxml.jackson.core.jackson-core_2.10.3.jar:2.9.8]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:917) ~[com.fasterxml.jackson.core.jackson-core_2.10.3.jar:2.9.8]
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:250) ~[com.fasterxml.jackson.core.jackson-databind_2.10.3.jar:2.9.9.2]
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258) ~[com.fasterxml.jackson.core.jackson-databind_2.10.3.jar:2.9.9.2]
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:258) ~[com.fasterxml.jackson.core.jackson-databind_2.10.3.jar:2.9.9.2]
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68) ~[com.fasterxml.jackson.core.jackson-databind_2.10.3.jar:2.9.9.2]
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15) ~[com.fasterxml.jackson.core.jackson-databind_2.10.3.jar:2.9.9.2]
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4270) ~[com.fasterxml.jackson.core.jackson-databind_2.10.3.jar:2.9.9.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2720) ~[com.fasterxml.jackson.core.jackson-databind_2.10.3.jar:2.9.9.2]
	at org.wso2.carbon.apimgt.gateway.listeners.APIMgtGatewayCacheMessageListener.onMessage_aroundBody0(APIMgtGatewayCacheMessageListener.java:53) [org.wso2.carbon.apimgt.gateway_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.gateway.listeners.APIMgtGatewayCacheMessageListener.onMessage(APIMgtGatewayCacheMessageListener.java:43) [org.wso2.carbon.apimgt.gateway_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.handleMessage(JMSTaskManager.java:645) [org.wso2.carbon.apimgt.jms.listener_9.0.5.jar:?]
	at org.wso2.carbon.apimgt.jms.listener.utils.JMSTaskManager$MessageListenerTask.run(JMSTaskManager.java:544) [org.wso2.carbon.apimgt.jms.listener_9.0.5.jar:?]
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

### Environment details (with versions):
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

---

**Comment by uvindra** [comment] 2021-03-02 13:00
This looks like a duplicate of https://github.com/wso2/product-apim/issues/9960

**Closed** 2021-03-02 15:45 UTC
Labels: API-M 4.0.0, Priority/High, Type/Bug
