### ISSUE TITLE
[UX][APIM] Misleading help text on API Create Visibility of Store

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#3096] opened 2018-03-16 09:54 UTC
**Description:**
$subject

Current help text: 
 The API is accessible to everyone and can be advertised in multiple stores - a central store and/or non-WSO2 stores.

"non-WSO2 stores" is misleading since we are providing the general system. Also, this will be problematic for our customers who use this. 

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
--Is the content up to date and accurate?

***Proposed Solution:***
change the text

**Suggested Labels:**
bug

**Affected Product Version:**
2.1.0 update 14

**OS, DB, other environment details and versions:**    
MacOS High sierra/ Chrome 64

**Comment by rmsamitha** [comment] 2022-01-28 04:22
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:22 UTC
Labels: Affected/2.1.0
