### ISSUE TITLE
[UX] Cannot delete Conditional Groups in Advance Throttling Policies

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3148] opened 2018-04-01 21:21 UTC
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
User control and freedom 

***Related task:***
Add throttling policies

***Issue:***
Cannot remove conditional groups after clicking "Add conditional group" button in advance throttling policies.

**Suggested Labels:**
UX, Bug

**Affected Product Version:**
2.2.0

**Comment by rmsamitha** [comment] 2022-01-28 04:21
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:21 UTC
Labels: Affected/2.2.0
