### ISSUE TITLE
[UX] Context of the error message not user friendly for the on boarding users

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#2877] opened 2018-03-06 11:50 UTC
**Description:**

***Not fulfilling checklist items:***
--Is error message expressed in plain language 

***Related task:****
Error recognition

***Issue:***
When you first run without JAVA we are getting an error message with "CARBON cannot execute <path>". IMO users are not aware of the CARBON context and we need to provide the message which helpful to novice users as well

***Proposed Solution:***
We can remove the CARBON related message and keep only the main part with documentation link on how to install and setup pre-requisites. 

"Error: JAVA_HOME is not defined correctly. Refer the documentation __here__ "
	
***Doc Link:***
https://docs.wso2.com/display/AM210/Installation+Prerequisites

**Affected Product Version:**
2.1.0

**Comment by rmsamitha** [comment] 2022-01-28 04:40
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:40 UTC
Labels: Priority/Low, Affected/2.1.0
