### ISSUE TITLE
Cursor jumps to the start of the first line when editing the swagger content in swagger editor.

### ISSUE THREAD

**Issue by menakaj** [wso2/product-apim#5071] opened 2019-06-22 04:31 UTC
When editing swagger definition in the swagger-editor, the cursor jumps to the start of the first line in the editor.

Need to position the cursor again in the correct place to start editing.

**Comment by chamilaadhi** [comment] 2019-10-12 05:12
duplicate of https://github.com/wso2/product-apim/issues/5997

**Closed by chamilaadhi** 2019-10-12 05:12 UTC
Labels: 3.0.0, Priority/Low, Severity/Minor, Type/React-UI, Type/UX, swagger
