### ISSUE TITLE
[UX] [APIM] API create Upload error message not get cleared even after the removing incorrect file

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#3095] opened 2018-03-16 09:28 UTC
**Description:**
$subject

![screenshot-2018-3-16 api publisher - add rest api](https://user-images.githubusercontent.com/6497326/37513213-6d061198-292a-11e8-9c6a-95060c78f184.png)

**Suggested Labels:**
bug

**Affected Product Version:**
2.1.0 update 14

**OS, DB, other environment details and versions:**    
MacOS High sierra/ Chrome 64

**Steps to reproduce:**
1. Goto API create
2. Select design tab
3. Click the select image in the thumbnail 
4. select incorrect image
5. click save
6. Error message will appear
7. Click on Remove
8. Still, you can see the error message

**Related Issues:**

**Comment by rmsamitha** [comment] 2022-01-28 04:24
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:24 UTC
Labels: Affected/2.1.0
