### ISSUE TITLE
[AM-3.0] Missing axis2-client.xml.j2 file

### ISSUE THREAD

**Issue by vinok88** [wso2/product-apim#7920] opened 2020-04-17 04:23 UTC
### Description:
$subject

### Affected Product Version:
3.0.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by praminda** [comment] 2020-04-28 14:20
Duplicate of #7472

**Closed by praminda** 2020-04-28 14:20 UTC
Labels: Priority/Normal, Type/Bug
