### ISSUE TITLE
Improvement of disabling/enabling UI components based on the scopes (apim:api_create and apim:api_publish)

### ISSUE THREAD

**Issue by wasuradananjith** [wso2/product-apim#9177] opened 2020-08-24 10:18 UTC
### Describe your problem(s)
Several improvements can be done to validate the UI functionality.
1. Log in to the Publisher portal as a user with Internal/publisher role and navigate to the **Runtime Configurations** tab. An error will be displayed in the UI as below.
    ![image](https://user-images.githubusercontent.com/25246848/91031925-e0043180-e61e-11ea-8ea6-2e91ae4d9f10.png)
    Further, an error log will be printed in the console as below.
    ```
    [2020-08-24 15:39:18,600] ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed
    [2020-08-24 15:39:18,611] ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed
    ```
2. Expand the **Application Level Security** in the same tab and you can see that **Key Manager Configuration** is enabled. Actually these should be disabled for the users with this role.
   ![image](https://user-images.githubusercontent.com/25246848/91032532-b5ff3f00-e61f-11ea-8d08-3c5fcb0bf8d2.png)
3. Navigate to the **Scopes** page in the Publisher portal (Make sure that there are no scopes created previously) as a user with Internal/creator or Internal/publisher roles. The **Create a new scope** button is enabled. But actually it should be disabled by default for the users with these roles.
    ![image](https://user-images.githubusercontent.com/25246848/91032262-54d76b80-e61f-11ea-87d9-023056b56ca7.png)

### Describe your solution
1. The first issue arises because of the REST API call to https://localhost:9443/api/am/publisher/v1/key-managers as shown below. This call should not be sent if the user has "apim:api_publish" scope by validating through the UI.
    ![image](https://user-images.githubusercontent.com/25246848/91033173-9583b480-e620-11ea-8510-be606c3fc078.png)
2. By checking whether the user role has the scope "apim:api_publish", the corresponding UI elements should be disabled for the second issue as well.
3. By checking whether the user role has the scopes "apim:api_create" or "apim:api_publish", the corresponding UI elements should be disabled for the third issue as well.

### How will you implement it
UI validations can be done.

**Comment by YasasRangika** [comment] 2021-08-25 07:54
Issue 3 is not reproducing in APIM 4.0.0

**Comment by YasasRangika** [comment] 2021-09-08 08:26
Closing this issue since the public fix has been added via https://github.com/wso2/apim-apps/pull/60

**Closed by YasasRangika** 2021-09-08 08:26 UTC
Labels: Type/Improvement, Priority/Normal, React-UI
