### ISSUE TITLE
Small grammer error in delete user admin service (RemoteUserStoreManagerService) error message

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2370] opened 2018-01-11 14:12 UTC
Please see the below error message with deleteUser in RemoteUserStoreManagerService

```
Caused by: org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not exist

```
This should be `Cannot delete user who does not exist`

**Comment by chamilaadhi** [comment] 2019-09-09 06:28
Fixed in Latest versions. Following error message is shown in APIM 2.6.0

`Caused by: org.wso2.carbon.user.core.UserStoreException: 30007 - UserNotFound: User test does not exist in: PRIMARY`

**Closed by chamilaadhi** 2019-09-09 06:28 UTC
Labels: 2.2.0, Type/Bug
