### ISSUE TITLE
Can't build on windows 10 pro : The command line is too long

### ISSUE THREAD

**Issue by yhilem** [wso2/product-apim#3810] opened 2018-10-07 10:21 UTC
**Description:**
This error is raised when I build https://github.com/wso2/product-apim/tree/2.x on windows 10 pro 

C:\OpenSource\wso2-am\product-apim_2.x>mvn clean package -Dcheckstyle.skip -Dmaven.test.skip=true -DskipTests -Dfindbugs.skip=true -Dpmd.skip=true -Dmaven.javadoc.skip=true
[INFO] Scanning for projects...
....
[INFO]
[INFO] --- carbon-p2-plugin:1.5.4:p2-profile-gen (3-p2-profile-generation) @ am-p2-profile ---
[INFO] Running Equinox P2 Director Application
[INFO] Command line:
        cmd.exe /X /C "C:\Platform\Java\jdk1.8.0_172\jre\bin\java.exe -jar C:\Users\yhilem\.m2\repository\org\eclipse\tycho\tycho-p2-runtime\0.13.0\eclipse\plugins\org.eclipse.equinox.launcher_1.2.0.v20110725-1610.jar -nosplash -application org.eclipse.equinox.p2.director -metadataRepository file:C:/OpenSource/wso2-am/product-apim_2.x/modules/p2-profile/product/target/p2-repo -artifactRepository file:C:/OpenSource/wso2-am/product-apim_2.x/modules/p2-profile/product/target/p2-repo -profileProperties org.eclipse.update.install.features=true -installIU org.wso2.carbon.analytics.message.tracer.handler.feature.group/1.3.25,org.jaggeryjs.modules.ws.feature.group/1.4.2,org.wso2.carbon.core.feature.group/4.4.35,org.wso2.carbon.tenant.mgt.common.feature.group/4.6.49,org.apache.axis2.transport.mail.feature.group/2.0.0.wso2v29,org.wso2.carbon.identity.notification.mgt.feature.group/5.12.153,org.wso2.carbon.identity.xacml.server.feature.group/5.12.153,org.wso2.carbon.identity.thrift.authentication.feature.group/5.12.153,org.wso2.carbon.identity.event.server.feature.group/5.12.153,org.wso2.carbon.identity.application.mgt.feature.group/5.12.153,org.wso2.carbon.as.runtimes.cxf.feature.group/4.7.19,org.wso2.carbon.webapp.mgt.server.feature.group/4.7.19,org.wso2.carbon.ntask.core.feature.group/4.6.49,org.wso2.carbon.logging.mgt.feature.group/4.6.49,org.wso2.carbon.module.mgt.server.feature.group/4.7.19,org.wso2.carbon.databridge.datapublisher.feature.group/5.1.42,org.wso2.carbon.databridge.datareceiver.feature.group/5.1.42,org.wso2.carbon.databridge.streamdefn.filesystem.server.feature.group/5.1.42,org.wso2.carbon.event.output.adapter.server.feature.group/5.1.42,org.wso2.carbon.event.output.adapter.email.server.feature.group/5.1.42,org.apache.synapse.wso2.feature.group/4.6.105,org.apache.synapse.transport.nhttp.feature.group/4.6.105,org.wso2.carbon.task.server.feature.group/4.6.105,org.wso2.carbon.mediation.initializer.feature.group/4.6.105,org.wso2.carbon.mediation.admin.feature.group/4.6.105,org.wso2.carbon.inbound.endpoints.server.feature.group/4.6.105,org.wso2.carbon.mediation.configadmin.feature.group/4.6.105,org.wso2.carbon.application.mgt.server.feature.group/4.6.49,org.wso2.carbon.application.mgt.synapse.server.feature.group/4.6.105,org.wso2.carbon.application.mgt.feature.group/4.6.49,org.wso2.carbon.application.deployer.synapse.feature.group/4.6.105,org.wso2.carbon.system.statistics.feature.group/4.6.49,org.wso2.carbon.soaptracer.feature.group/4.6.49,org.wso2.carbon.security.mgt.feature.group/5.12.153,org.wso2.carbon.security.mgt.server.feature.group/5.12.153,org.wso2.carbon.service.mgt.server.feature.group/4.7.19,org.wso2.carbon.message.flows.feature.group/4.6.49,org.wso2.carbon.registry.core.feature.group/4.6.38,org.wso2.carbon.registry.core.server.feature.group/4.6.38,org.wso2.carbon.registry.ui.menu.feature.group/4.6.38,org.wso2.carbon.registry.ui.menu.governance.feature.group/4.6.38,org.wso2.carbon.registry.resource.properties.feature.group/4.6.38,org.wso2.carbon.mediators.server.feature.group/4.6.105,org.wso2.carbon.relay.server.feature.group/4.6.105,org.wso2.am.styles.feature.group/2.6.1.SNAPSHOT,org.wso2.am.multitenancy.dashboard.ui.feature.group/2.6.1.SNAPSHOT,org.wso2.carbon.event.server.feature.group/4.6.49,org.wso2.carbon.event.common.feature.group/4.6.49,org.wso2.carbon.registry.associations.dependencies.feature.group/4.6.38,org.wso2.carbon.registry.community.features.feature.group/4.6.38,org.wso2.carbon.identity.provider.server.feature.group/5.2.6,org.wso2.carbon.identity.oauth.feature.group/6.0.53,org.wso2.carbon.identity.application.authenticator.basicauth.server.feature.group/6.0.6,org.wso2.carbon.identity.application.authenticator.samlsso.server.feature.group/5.1.18,org.wso2.carbon.identity.application.authentication.framework.server.feature.group/5.12.153,org.wso2.carbon.identity.user.registration.server.feature.group/5.12.153,org.wso2.carbon.identity.idp.metadata.saml2.server.feature.group/1.0.5,org.wso2.carbon.tenant.mgt.common.server.feature.group/4.6.49,org.wso2.carbon.deployment.synchronizer.feature.group/4.6.49,org.wso2.carbon.registry.community.features.server.feature.group/4.6.38,org.wso2.carbon.websocket.feature.group/4.6.105,org.wso2.carbon.mediator.cache.server.feature.group/4.6.105,org.wso2.carbon.identity.xacml.mediator.feature.group/4.6.105,org.wso2.carbon.mediator.publishevent.feature.group/4.6.105,org.wso2.carbon.registry.ws.feature.group/4.6.38,org.jaggeryjs.feature.group/0.12.6,org.jaggeryjs.modules.carbon.feature.group/1.5.6,org.jaggeryjs.modules.process.feature.group/1.5.6,org.jaggeryjs.modules.uuid.feature.group/1.5.6,org.jaggeryjs.modules.sso.feature.group/1.5.6,org.jaggeryjs.modules.i18n.feature.group/1.5.6,org.wso2.carbon.apimgt.feature.group/6.4.60,org.wso2.carbon.registry.extensions.feature.group/4.7.27,org.wso2.carbon.registry.extensions.server.feature.group/4.7.27,org.wso2.carbon.governance.metadata.feature.group/4.7.27,org.wso2.carbon.governance.lifecycle.management.feature.group/4.7.27,org.wso2.carbon.user.mgt.feature.group/5.12.153,org.wso2.carbon.identity.core.feature.group/5.12.153,org.wso2.carbon.um.ws.service.server.feature.group/5.1.11,org.wso2.carbon.um.ws.service.client.feature.group/5.1.11,org.wso2.carbon.directory.service.mgr.feature.group/5.12.153,org.wso2.carbon.claim.mgt.feature.group/5.12.153,org.wso2.carbon.identity.authenticator.saml2.sso.server.feature.group/5.2.9,org.wso2.carbon.identity.authenticator.saml2.sso.ui.feature.group/5.2.9,org.wso2.carbon.webapp.mgt.feature.group/4.7.19,org.wso2.carbon.registry.contentsearch.feature.group/4.6.38,org.wso2.carbon.idp.mgt.feature.group/5.12.153,org.wso2.carbon.forum.server.feature.group/6.4.60,org.wso2.carbon.tenant.common.feature.group/4.6.15,org.wso2.carbon.tenant.usage.agent.feature.group/4.6.15,org.wso2.carbon.tenant.throttling.agent.feature.group/4.6.15,org.wso2.carbon.tenant.deployment.feature.group/4.6.15,org.wso2.carbon.ndatasource.feature.group/4.6.49,org.wso2.carbon.apimgt.authenticator.oidc.feature.group/6.4.60,org.wso2.carbon.apimgt.hostobjects.oidc.feature.group/6.4.60,org.wso2.carbon.apimgt.rest.api.publisher.feature.group/6.4.60,org.wso2.carbon.apimgt.rest.api.store.feature.group/6.4.60,org.wso2.carbon.apimgt.rest.api.admin.feature.group/6.4.60,org.wso2.carbon.apimgt.rest.api.dcr.feature.group/6.4.60,org.wso2.ciphertool.feature.group/1.0.0.wso2v8,org.wso2.carbon.metrics.feature.group/1.2.3,org.wso2.carbon.apimgt.throttling.siddhi.extension.feature.group/6.4.60,org.wso2.carbon.apimgt.jms.listener.feature.group/6.4.60,org.wso2.carbon.identity.user.profile.feature.group/5.12.153,org.wso2.carbon.andes.server.feature.group/3.2.44,org.wso2.carbon.event.receiver.feature.group/5.1.42,org.wso2.carbon.event.publisher.feature.group/5.1.42,org.wso2.carbon.event.publisher.aggregate.feature.group/5.1.42,org.wso2.carbon.event.processor.feature.group/2.1.23,org.wso2.carbon.event.tracer.feature.group/5.1.42,org.wso2.carbon.event.flow.feature.group/2.1.23,org.wso2.carbon.siddhi.tryit.feature.group/2.1.23,org.wso2.carbon.event.statistics.feature.group/5.1.42,org.wso2.carbon.event.stream.feature.group/5.1.42,org.wso2.carbon.event.simulator.feature.group/2.1.23,org.wso2.carbon.event.application.deployer.feature.group/5.1.42,org.wso2.carbon.event.template.manager.feature.group/5.1.42,org.wso2.carbon.event.processor.manager.core.feature.group/5.1.42,org.wso2.carbon.event.processor.manager.commons.feature.group/5.1.42,org.wso2.carbon.dashboards.portal.feature.group/2.0.19,org.wso2.carbon.analytics.shared.la.common.feature.group/1.0.4,org.wso2.carbon.analytics.shared.la.apim.feature.group/1.0.4,org.wso2.carbon.analytics.shared.data.agents.log4j.feature.group/1.0.4,org.wso2.carbon.identity.mgt.feature.group/5.12.153,org.wso2.carbon.consent.mgt.server.feature.group/2.0.18,org.wso2.carbon.database.utils.feature.group/2.0.6,org.wso2.carbon.identity.consent.mgt.server.feature.group/5.12.153,org.wso2.carbon.identity.auth.server.feature.group/1.1.20,org.wso2.carbon.identity.authz.server.feature.group/1.1.20,org.wso2.carbon.identity.context.rewrite.server.feature.group/1.1.20, -bundlepool C:\OpenSource\wso2-am\product-apim_2.x\modules\p2-profile\product/target/wso2carbon-core-4.4.35/repository/components -shared C:\OpenSource\wso2-am\product-apim_2.x\modules\p2-profile\product/target/wso2carbon-core-4.4.35/repository/components\p2 -destination C:\OpenSource\wso2-am\product-apim_2.x\modules\p2-profile\product/target/wso2carbon-core-4.4.35/repository/components\default -profile default -roaming"
La ligne de commande est trop longue.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] WSO2 API Manager - Aggregator Module ............... SUCCESS [  1.063 s]
[INFO] WSO2 API Manager - Styles Parent ................... SUCCESS [  0.047 s]
[INFO] WSO2 API Manager - Styles .......................... SUCCESS [  3.031 s]
[INFO] WSO2 Stratos  API Manager - UI styles .............. SUCCESS [  5.125 s]
[INFO] WSO2 API Manager - Multi Tenant Dashboard .......... SUCCESS [  2.203 s]
[INFO] WSO2 API Manager - Features Parent ................. SUCCESS [  0.047 s]
[INFO] WSO2 API Manager - Features Aggregator Module ...... SUCCESS [  0.031 s]
[INFO] WSO2 API Manager - Styles Features ................. SUCCESS [  1.266 s]
[INFO] WSO2 API Manager - Multi Tenant Dashboard Feature .. SUCCESS [  3.093 s]
[INFO] Samples ............................................ SUCCESS [  1.774 s]
[INFO] Clients for samples ................................ SUCCESS [  0.281 s]
[INFO] Publisher API client ............................... SUCCESS [  3.984 s]
[INFO] Store API client ................................... SUCCESS [  2.172 s]
[INFO] Admin API client ................................... SUCCESS [  2.235 s]
[INFO] Back end Service ................................... SUCCESS [  2.734 s]
[INFO] Sample Utils ....................................... SUCCESS [  5.297 s]
[INFO] Sample One ......................................... SUCCESS [ 18.969 s]
[INFO] Sample Two ......................................... SUCCESS [ 16.203 s]
[INFO] Sample Four ........................................ SUCCESS [ 16.452 s]
[INFO] Sample Seven ....................................... SUCCESS [ 15.656 s]
[INFO] Sample Eight ....................................... SUCCESS [ 15.920 s]
[INFO] Sample Nine ........................................ SUCCESS [ 16.063 s]
[INFO] Sample Ten ......................................... SUCCESS [ 15.998 s]
[INFO] WSO2 API Manager - P2 Profile Generation Parent .... SUCCESS [  0.031 s]
[INFO] WSO2 API Manager - P2 Profile Generation ........... FAILURE [01:41 min]
[INFO] API Manager : oauth2-grant-types ................... SKIPPED
[INFO] WSO2 API Manager - Distribution Parent ............. SKIPPED
[INFO] WSO2 API Manager - Distribution .................... SKIPPED
[INFO] WSO2 API Manager - API Import Export ............... SKIPPED
[INFO] WSO2 API Manager - Integration Tests ............... SKIPPED
[INFO] WSO2 API Manager - Integration Test Common Module .. SKIPPED
[INFO] WSO2 API Manager - Integration Admin Clients Module  SKIPPED
[INFO] WSO2 API Manager - Integration Common Test Module .. SKIPPED
[INFO] WSO2 API Manager - Test Artifacts Tests ............ SKIPPED
[INFO] WSO2 API Manager - RestFul Backend Module for Integration Tests SKIPPED
[INFO] WSO2 API Manager - ArtifactDeploymentMonitor WebApp  SKIPPED
[INFO] org.wso2.am.framework.extensions ................... SKIPPED
[INFO] WSO2 API Manager - Integration Extensions Module ... SKIPPED
[INFO] WSO2 API Manager - Integration UI Pages Module ..... SKIPPED
[INFO] WSO2 API Manager - Integration New Test Module ..... SKIPPED
[INFO] WSO2 API Manager - Based on product backend Test Module SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:13 min
[INFO] Finished at: 2018-10-07T12:12:24+02:00
[INFO] Final Memory: 96M/1436M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.wso2.maven:carbon-p2-plugin:1.5.4:p2-profile-gen (3-p2-profile-generation) on project am-p2-profile: P2 publisher return code was 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :am-p2-profile

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

Thanks
Youcef HILEM

**Comment by juandavidgc** [comment] 2018-12-20 19:07
I've got the same error... any update? thanks.

**Comment by chathurabuddi** [comment] 2020-03-19 08:14
same here. Any fixes?

**Comment by rmsamitha** [comment] 2022-01-28 04:10
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:10 UTC
