### ISSUE TITLE
[UX] [Publisher] API Create upload thumbnail image file type restriction 

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#3093] opened 2018-03-16 09:15 UTC
**Description:**
$subject. seems we need to add accept attrib to fix this.

**Suggested Labels:**
bug

**Affected Product Version:**
2.1.0 update 14

**OS, DB, other environment details and versions:**    
MacOS High sierra/ Chrome 64

**Comment by rmsamitha** [comment] 2022-01-28 04:25
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:25 UTC
Labels: Affected/2.1.0
