### ISSUE TITLE
Localization for Chinese characters applied in the endpoint list page by default

### ISSUE THREAD

**Issue by erandidesilva** [wso2/product-apim#2100] opened 2018-01-02 12:31 UTC
OS: Ubuntu 16.04
JDK: 1.8.0_144
Browser: Chrome Version 63.0.3239.108 (Official Build) (64-bit)

**Steps**
1. Open endpoints list page

As shown in the below image, localization is applied by default. Ideally unless customized, localization should not apply

![apim_issue_4](https://user-images.githubusercontent.com/15624590/34483818-e8d3417e-efe6-11e7-882d-0b135ac9e8c5.png)

**Comment by tmkasun** [comment] 2019-10-22 04:17
Fixed in APIM 3.0 alpha, This was caused by `antd` library. We no longer use it.

**Closed by tmkasun** 2019-10-22 04:17 UTC
Labels: 3.0.0, Priority/Highest, Severity/Major, Type/Bug
