### ISSUE TITLE
[Publisher]When it is trying to delete a non-existing endpoint, the response is 200 instead of 404. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#1630] opened 2017-10-01 16:16 UTC
**Steps to reproduce:**
1. Send following cURL command to delete a non-existing endpoint. 

>  _curl -v -k -H "Authorization: Bearer [apim:api_delete]" -H "Content-Type: application/json" -X DELETE https://127.0.0.1:9292/api/am/publisher/v1.0/endpoints/[invalidEndpointId]_

**Expected response:** 404
**Actual Response:** HTTP/1.1 200 OK

**Comment by dushaniw** [comment] 2020-11-10 06:50
Cannot reproduce as /endpoints/{endpointId} does not exist in latest v1 publisher REST APIs. Hence closing

**Closed by dushaniw** 2020-11-10 06:50 UTC
Labels: Affected/3.0.0
