### ISSUE TITLE
Copy - Paste working in a wrong mannner in Swagger tools

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [wso2/product-apim#5885] opened 2019-09-27 05:42 UTC
**Description**

- Tried to paste something in the swagger definition in swagger tool. But it always pastes at the top of the file despite of where we clicked

**Comment by chamilaadhi** [comment] 2019-10-08 03:48
Related issues https://github.com/wso2/product-apim/issues/5997, https://github.com/wso2/product-apim/issues/5885

**Comment by chamilaadhi** [comment] 2019-10-12 05:12
duplicate of https://github.com/wso2/product-apim/issues/5997

**Closed by chamilaadhi** 2019-10-12 05:12 UTC
