### ISSUE TITLE
[AsyncAPI] Generate valid Callback URLs

### ISSUE THREAD

**Issue by lasanthaS** [wso2/product-apim#10362] opened 2021-03-18 11:40 UTC
### Describe your problem(s)
The callback URLs using placeholders and not showing the exact  URL. This needs to be fixed by looking at the deployments for WebSub + HTTPS callback URLs.

### How will you implement it

---

**Comment by sajithshn** [comment] 2021-04-09 16:03
This is a duplicate of https://github.com/wso2/product-apim/issues/10754. Hence closing

**Closed by sajithshn** 2021-04-09 16:03 UTC
Labels: API-M 4.0.0, Feature/AsyncAPIs, Priority/Normal, Severity/Critical, Type/Improvement
