### ISSUE TITLE
[3.2.0-RC5] Migration fails with postgreSQL

### ISSUE THREAD

**Issue by chaminda** [wso2/product-apim#9090] opened 2020-08-16 18:45 UTC
### Description:
Identity component migration steps fails with postgre database-9.6
Getting below error at v-5.10.0 steps.

```
[2020-08-16 23:56:03,026]  INFO - MigrationClientImpl  WSO2 Product Migration Service Task : Start Version : 5.9.0 to 5.10.0
[2020-08-16 23:56:03,056]  INFO - VersionMigration  WSO2 Product Migration Service Task : Version : 5.10.0, Migration Step : ScopeDataMigrator of order : 1 is starting...........................
[2020-08-16 23:56:03,064]  INFO - VersionMigration  WSO2 Product Migration Service Task : Version : 5.10.0, Migration Step : SchemaMigrator of order : 3 is starting...........................
[2020-08-16 23:56:03,066]  INFO - SchemaMigrator  WSO2 Product Migration Service Task : Executing Identity Migration Scripts.
[2020-08-16 23:56:03,315] ERROR - SchemaMigrator Error occurred while executing SQL script for migrating database
java.lang.Exception: Error occurred while executing :   DROP FUNCTION IF EXISTS OIDC_SCOPE_DATA_MIGRATE_FUNCTION
	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQL(SchemaMigrator.java:303) ~[org.wso2.carbon.is.migration-1.0.107.jar:?]
	at org.wso2.carbon.is.migration.service.SchemaMigrator.executeSQLScript(SchemaMigrator.java:234) [org.wso2.carbon.is.migration-1.0.107.jar:?]
	at org.wso2.carbon.is.migration.service.SchemaMigrator.migrate(SchemaMigrator.java:89) [org.wso2.carbon.is.migration-1.0.107.jar:?]
	at org.wso2.carbon.is.migration.VersionMigration.migrate(VersionMigration.java:52) [org.wso2.carbon.is.migration-1.0.107.jar:?]
	at org.wso2.carbon.is.migration.MigrationClientImpl.execute(MigrationClientImpl.java:85) [org.wso2.carbon.is.migration-1.0.107.jar:?]
	at org.wso2.carbon.identity.core.internal.IdentityCoreServiceComponent.activate(IdentityCoreServiceComponent.java:147) [org.wso2.carbon.identity.core_5.17.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
.....
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at end of input
  Position: 59
```

### Steps to reproduce:
Migrate apim 2.x to 3.2.0 using postgre database.

### Affected Product Version:
wso2am-3.2.0-rc5

### Environment details (with versions):
- OS: MacOS

**Comment by dushaniw** [comment] 2020-08-17 05:11
Tried to reproduce this with Postgres 9.6 and API-M RC with latest IS migration client - org.wso2.carbon.is.migration-1.0.107. But could not reproduce. The migration client is running without any errors.

**Comment by dushaniw** [comment] 2020-08-17 06:10
Can reproduce this with PostgreSQL 9.6. Seems in 9.6, the function name should be given with parenthesis

**Comment by dushaniw** [comment] 2020-08-24 05:32
fixed with https://github.com/wso2-extensions/identity-migration-resources/pull/131

**Closed by dushaniw** 2020-08-24 05:32 UTC
Labels: Priority/Highest, Severity/Blocker, Type/Bug
