### ISSUE TITLE
[Pubilsher]PUT /apis/{apiId}/documents/{documentId} : When it is trying to pass an empty document object, 500 returns as the response code instead of 400. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#1629] opened 2017-10-01 14:28 UTC
### **Description:**
When an empty object is passed as the body of the document in PUT operation, 500 returns as the response instead of 400 Bad Request, 

**Steps to reproduce:**
1. Create an API with a document. 
2. Update the document with an empty document body. data.json would be an empty file. 

> _curl -k -v -H "Authorization: Bearer [apim:api_update]" -H "Content-Type: application/json" -X _PUT -d @data.json https://127.0.0.1:9292/api/am/publisher/v1.0/apis/[apiId]/documents/[documentId]__

**Expected response:** 400 Bad request
**Actual response:** HTTP/1.1 500 Internal Server Error

Server
```
[2017-10-01 14:11:13,450]  WARN {org.wso2.msf4j.internal.MSF4JMessageProcessor} - Unmapped exception java.lang.NullPointerException
	at org.wso2.carbon.apimgt.rest.api.publisher.utils.MappingUtil.toDocumentInfo(MappingUtil.java:332)
	at org.wso2.carbon.apimgt.rest.api.publisher.impl.ApisApiServiceImpl.apisApiIdDocumentsDocumentIdPut(ApisApiServiceImpl.java:437)
	at org.wso2.carbon.apimgt.rest.api.publisher.ApisApi.apisApiIdDocumentsDocumentIdPut(ApisApi.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:132)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:139)
	at org.wso2.msf4j.internal.MSF4JMessageProcessor.lambda$receive$0(MSF4JMessageProcessor.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rmsamitha** [comment] 2022-01-28 04:57
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:57 UTC
Labels: Affected/3.0.0
