### ISSUE TITLE
HTTP PATCH method not working when no request body defined  in the resource.

### ISSUE THREAD

**Issue by Prabhashi** [wso2/product-apim#12764] opened 2022-03-24 12:49 UTC
### Description:
 HTTP PATCH method is not working when no request body defined  in a patch resource.

### Steps to reproduce:

- Have a Patch resource as below in the API swagger definition.
  
```
/testpath/{param}:
    patch:
      tags:
        - testpath
      summary: summary.
      description: Test description.
      parameters:
        - name: param
          in: path
          description: Test param desc.
          required: true
          type: string
      responses:
        '200':
          description: successful operation
        '401':
          $ref: '#/responses/UnauthorizedError'
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
```
So the above does not have request body.
- Created an API with this swagger file.
- When trying to invoke patch resource , it is not working because the resource path parameters does not append to the backend URL.

This scenario is working fine with APIM 4.0.

### Affected Product Version:
APIM 2.6.0.79 

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by ashera96** [comment] 2022-03-29 05:29
Duplicate of https://github.com/wso2/product-apim/issues/7462

**Closed** 2023-01-19 14:42 UTC
Labels: Type/Bug, Priority/Normal
