### ISSUE TITLE
[Admin] Inconsistency in Error Validation in blacklist policies

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3154] opened 2018-04-02 06:59 UTC
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Consistency and Standards - Is flow maintain the same patterns and consistency

***Related task:***
Add throttling policies - black list requests

***Issue:***
Validation should be provided under the text input and should maintain consistency.
![blacklist](https://user-images.githubusercontent.com/9837443/38186511-bdcdedb6-3696-11e8-8fb9-d13a9b973638.png)
![blacklist1](https://user-images.githubusercontent.com/9837443/38186538-deb059d8-3696-11e8-858d-52be942231d3.png)

**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.2.0

**Comment by rmsamitha** [comment] 2022-01-28 04:19
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:19 UTC
Labels: Priority/Low, Affected/2.1.0, Affected/2.2.0
