### ISSUE TITLE
Added conditional group for addvance throttling policy has been removed from UI when click on update at edit page

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-apim#2280] opened 2018-01-08 07:11 UTC
**Description:**
Added conditional group for addvance throttling policy has been removed from UI when click on update at edit page

**Suggested Labels:**
APIM-2.2.0
Type/bug
Priority/high
Severity/high

**Suggested Assignees:**

**Affected Product Version:**
2.1.0-update5

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Configure header, query param, jwt claim condition as per here [1]
- Go to admin dashborad and Advance throttle policy tab
- Add new throttling policy and add Conditional group as in below image
![adv-policy](https://user-images.githubusercontent.com/15671620/34661440-ba9efc66-f46f-11e7-9e4c-cc726ff044a5.jpeg)

- Save the policy
- View in advance policy list and click on edit relevant policy
- Without modifying it, click on update 
![adv-policy2](https://user-images.githubusercontent.com/15671620/34661557-8979c8f4-f470-11e7-80fd-26793b9a77f3.jpeg)

- Come again to relevant policy edit page => Added conditional group has been removed (see below image)
![adv-policy3](https://user-images.githubusercontent.com/15671620/34661553-81d4e03e-f470-11e7-970d-ce6f7b16df9e.jpeg)

[1] <https://docs.wso2.com/display/AM2xx/Adding+New+Throttling+Policies#AddingNewThrottlingPolicies-Addinganewadvancedthrottlingpolicy>

**Comment by Krishanx92** [comment] 2018-06-12 05:27
This issue could not reproduce in the APIM 2.2.0.
@kavithasub Did you try to reproduce this in APIM 2.2.0?

**Comment by kavithasub** [comment] 2018-06-12 05:55
@Krishanx92 , tested while APIM-2.1.0-update5
>Affected Product Version:
2.1.0-update5

**Comment by chamindias** [comment] 2018-06-12 11:45
Closing based on https://github.com/wso2/product-apim/issues/2280#issuecomment-396469704

**Closed by chamindias** 2018-06-12 11:45 UTC
Labels: 2.2.0, Priority/High, Severity/Critical, Type/Bug
