### ISSUE TITLE
[Store] UI issue under Applications tab

### ISSUE THREAD

**Issue by ashera96** [wso2/product-apim#6669] opened 2019-10-25 05:25 UTC
As shown in the screenshot below, there is an issue when displaying the name of the application.

![WSO2 APIM Developer Portal](https://user-images.githubusercontent.com/30475839/67545127-a2402f00-f715-11e9-8038-63f2d3f2be66.png)

**Comment by dushaniw** [comment] 2019-11-13 11:25
Duplicate of https://github.com/wso2/product-apim/issues/6683

**Closed by dushaniw** 2019-11-13 11:25 UTC
