### ISSUE TITLE
[DevPortal] Application Changed automatically after subscription

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#5993] opened 2019-09-30 06:48 UTC
Use Case:API adminstrator needs to manage the subscription level plans from admin dashboard, by add/edit/delete
Test Scenario: Edit default BRONZE subscription tier with new #Request and Time, and define for an API. So that subscribers are granted maximum number of request to the API is newly added #Request and Time

Details of the Issue: When I subscribed to Bronze Tier with Default Application ( logged in as Admin Tenant) subscription was done automatically using a previously created secondary application.

![Screenshot from 2019-09-28 21-01-33](https://user-images.githubusercontent.com/38970634/65855176-2a801e00-e37c-11e9-9b32-5b70dfe8b45a.png)
![Screenshot from 2019-09-28 21-01-51](https://user-images.githubusercontent.com/38970634/65855181-2c49e180-e37c-11e9-851a-65dcf3d1ecd9.png)
![Screenshot from 2019-09-28 21-04-04](https://user-images.githubusercontent.com/38970634/65855186-2e13a500-e37c-11e9-9c0f-b2c75534ea09.png)

**Comment by dushansilva** [comment] 2019-10-03 08:29
After offline discussion closing this issue since we cannot reproduce it

**Closed by dushansilva** 2019-10-03 08:29 UTC
