### ISSUE TITLE
Multiple problems with policy attributes window

### ISSUE THREAD

**Issue by 1akshitha** [wso2/product-apim#12484] opened 2022-02-24 16:38 UTC
### Description:
1. Cannot update applied policy attribute values as the save button is disabled.
![image](https://user-images.githubusercontent.com/47380453/155567426-9ada49fd-592d-43cf-9c27-6f4fb812fb52.png)

2. Regex validation does not prevent the policy from save. Still, we can save even though validations are colored in red.
 ![Screenshot 2022-02-24 at 10 07 39 PM](https://user-images.githubusercontent.com/47380453/155567570-4c6206da-e5c5-47ab-94eb-7f45ecb0823a.png)

3.  Attribute values that previously passed validation shows invalid after save.

### Affected Product Version:
4.1.0-alpha

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by ashera96** [comment] 2022-03-03 16:17
Since none of the reported issues are reproducible with the latest pack, closing this issue.

**Closed by ashera96** 2022-03-03 16:17 UTC
Labels: Type/Bug, Priority/Normal, React-UI, APIM - 4.1.0, Feature/OperationPolicies
