### ISSUE TITLE
[DOC] [2.6.0] Update Account locking and Password Policies documentation

### ISSUE THREAD

**Issue by abhishekdesilva** [wso2/product-apim#4180] opened 2019-01-17 09:33 UTC
**Description:**
We need to update the

> Identity Management for the API Store

 documentation to use the new identity management REST APIs for Account Locking and Password Policies.

According to the documentation, the instructions to enable the Account Locking feature describes at [1]. This should be updated to [2] accordingly.

According to the documentation, the instructions to define the Password Policies describes at [3]. This should be updated to [4] accordingly.

**Suggested Labels:**
N/A

**Suggested Assignees:**
N/A

**Affected Product Version:**
N/A

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

[1] https://docs.wso2.com/display/AM260/Identity+Management+for+the+API+Store#IdentityManagementfortheAPIStore-Accountlocking
[2] https://docs.wso2.com/display/IS570/User+Account+Suspension
[3] https://docs.wso2.com/display/AM260/Identity+Management+for+the+API+Store#IdentityManagementfortheAPIStore-Paaswordpolicies
[4] https://docs.wso2.com/display/IS570/Password+Policies

**Comment by rmsamitha** [comment] 2022-01-27 13:32
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-27 13:32 UTC
Labels: Type/Docs, Docs/Has Impact
