### ISSUE TITLE
[UX][Store] Improvements in API level forum section

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3457] opened 2018-06-19 05:50 UTC
**Description:**
When the user goes to API page ->forum tab  and click on "Create new topic" or clicks on a already added forum topic, the user is directed to main forum tab which confuses the user. If the user needs to go back to the API page s/he needs to go to API listing and go to the specific API page. 

Suggestion: Add "Go back" option instead of "Topic list" when directed to main forum tab from API page so that s/he can go back to the API page s/he was before.

**Suggested Labels:**
UX, improvement

**Affected Product Version:**
2.5.0

**Comment by rmsamitha** [comment] 2022-01-28 04:11
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:11 UTC
Labels: Affected/2.5.0
