### ISSUE TITLE
[Admin] Broken sort icon in throttling policy tables

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3155] opened 2018-04-02 07:49 UTC
**Description:**
The tables shows a square instead of the sort icon. The sort icon is broken.
![table-throttling](https://user-images.githubusercontent.com/9837443/38188195-241f486a-369e-11e8-8e08-54cfcb246384.png)

**Suggested Labels:**
UI, improvement

**Affected Product Version:**
2.2.0

**Comment by rmsamitha** [comment] 2022-01-28 04:19
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:19 UTC
Labels: Priority/Low, Affected/2.1.0, Affected/2.2.0
