### ISSUE TITLE
How to capture response from wso2 Rest API that has successfully passed/received on request/response to Backend Soap API

### ISSUE THREAD

**Issue by prats2017** [wso2/product-apim#5560] opened 2019-09-13 17:08 UTC
I am a Newbie and doing a POC to write Wso2 API for SOAP service and generating Rest endpoints. Wso2 Swagger API is working fine and getting response from backend API. Then, I downloaded Java SDK to write client. When I run my client I see that my request has reached Backend server and response has been generated. I also see response in my wso2 logs in Json format.

My problem is, I am not sure how to capture response in client I wrote because wso2 generated API is returning ApiResponse. I have gone through pizza-shack example at and that doesn't seem to be very helpful. Is there any example that I can follow on learn. Or should i be changing code generated by wso2?

**Wso2Client I wrote --**

 public void callWso2API() throws ApiException{
        AllCountryApi allCountryApi = new AllCountryApi();
        String accessToken = "6f529fca-b574-32c2-8833-a7dbcffcaa1d";
        ApiClient apiClient = allCountryApi.getApiClient();
        apiClient.addDefaultHeader("Accept", "application/json"); 
        apiClient.addDefaultHeader("Authorization", "Bearer " + accessToken);
        apiClient.setLenientOnJson(true);
        apiClient.setBasePath("http://XXX:8280/countries1/v1.0.0");
        allCountryApi.allCountryGet();
        System.out.println("End");
    }
**API Class WSo2 generated --**

public class AllCountryApi {
    public void allCountryGet() throws ApiException {
        allCountryGetWithHttpInfo();
    }        
    public ApiResponse<Void> allCountryGetWithHttpInfo() throws ApiException {
        com.squareup.okhttp.Call call = allCountryGetValidateBeforeCall(null, null);
        return apiClient.execute(call);
    }    
}

    **WSo2 Logs have response from backend API. Not sure where i am loosing it--**
    DEBUG - wire HTTP-Sender I/O dispatcher-1 << "<?xml version='1.0' encoding='UTF-8'?><soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope" xmlns:web="http://www.example.com/triad/"><soapenv:Body><web:getAllCountryRequest/></soapenv:Body></soapenv:Envelope>[\r][\n]"
    DEBUG - wire HTTP-Sender I/O dispatcher-1 << "0[\r][\n]"
    wire HTTP-Sender I/O dispatcher-1 << "[\r][\n]"
    wire HTTP-Sender I/O dispatcher-1 >> "HTTP/1.1 200 [\r][\n]"
    wire HTTP-Sender I/O dispatcher-1 >> "Accept: application/soap+xml, text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2[\r][\n]"
    wire HTTP-Sender I/O dispatcher-1 >> "Content-Type: application/soap+xml;charset=utf-8[\r][\n]"
    wire HTTP-Sender I/O dispatcher-1 >> "Content-Length: 744[\r][\n]"
    wire HTTP-Sender I/O dispatcher-1 >> "Date: Fri, 13 Sep 2019 18:13:49 GMT[\r][\n]"
    wire HTTP-Sender I/O dispatcher-1 >> "[\r][\n]"
    wire HTTP-Sender I/O dispatcher-1 >> "<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope"><env:Header/><env:Body><ns2:getAllCountryResponse xmlns:ns2="http://www.example.com/triad/"><ns2:countryDetails><ns2:name>Poland</ns2:name><ns2:population>38186860</ns2:population><ns2:capital>Warsaw</ns2:capital><ns2:currency>PLN</ns2:currency></ns2:countryDetails><ns2:countryDetails><ns2:name>United Kingdom</ns2:name><ns2:population>63705000</ns2:population><ns2:capital>London</ns2:capital><ns2:currency>GBP</ns2:currency></ns2:countryDetails><ns2:countryDetails><ns2:name>India</ns2:name><ns2:population>46704314</ns2:population><ns2:capital>Delhi</ns2:capital><ns2:currency>INR</ns2:currency></ns2:countryDetails></ns2:getAllCountryResponse></env:Body></env:Envelope>"
    wire HTTP-Listener I/O dispatcher-1 << "HTTP/1.1 200 [\r][\n]"
    wire HTTP-Listener I/O dispatcher-1 << "Accept: application/soap+xml, text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2[\r][\n]"
    wire HTTP-Listener I/O dispatcher-1 << "Access-Control-Allow-Origin: *[\r][\n]"
    wire HTTP-Listener I/O dispatcher-1 << "Access-Control-Allow-Methods: GET[\r][\n]"
    wire HTTP-Listener I/O dispatcher-1 << "Access-Control-Allow-Headers: authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction[\r][\n]"
    wire HTTP-Listener I/O dispatcher-1 << "Content-Type: application/json; charset=utf-8[\r][\n]"
    wire HTTP-Listener I/O dispatcher-1 << "Date: Fri, 13 Sep 2019 18:13:49 GMT[\r][\n]"
    wire HTTP-Listener I/O dispatcher-1 << "Transfer-Encoding: chunked[\r][\n]"
    DEBUG - wire HTTP-Listener I/O dispatcher-1 << "Connection: Keep-Alive[\r][\n]"
    DEBUG - wire HTTP-Listener I/O dispatcher-1 << "[\r][\n]"
    DEBUG - wire HTTP-Listener I/O dispatcher-1 << "118[\r][\n]"
    DEBUG - wire HTTP-Listener I/O dispatcher-1 << "{"**getAllCountryResponse":{"countryDetails":[{"name":"Poland","population":38186860,"capital":"Warsaw","currency":"PLN"},{"name":"United Kingdom","population":63705000,"capital":"London","currency":"GBP"},{"name":"India","population":46704314,"capital":"Delhi","currency":"INR"}]}}[\r][\n]"**

**Comment by prats2017** [comment] 2019-09-13 18:18
Also, when I try to print response in APIReponse.execute() it is null so, clearly response is not being captured. Am i missing out on some step/configuration here?

**Comment by chamilaadhi** [comment] 2019-09-18 11:01
Closing this jira since https://github.com/wso2/product-apim/issues/5580 is a duplicate of this. We could continue on this issue in https://github.com/wso2/product-apim/issues/5580

**Closed by chamilaadhi** 2019-09-18 11:01 UTC
