### ISSUE TITLE
[UX][Store] API overview "More APIs from <provider>" shows APIs not listed in the API Listing

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2974] opened 2018-03-10 02:31 UTC
**Description:**
When show all versions are set to false(default behavior) in api-manager.xml when the latest version is deployed as a prototype the store API listing only shows the deployed prototyped version, but when we go to API overview of the prototyped API, in More APIs from '<provider>' section shows the latest published API but this is not listed in API listing.

**Suggested Labels:**
Bug, UX

**Affected Product Version:**
2.1.0

**Comment by rmsamitha** [comment] 2022-01-28 04:33
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:33 UTC
Labels: Affected/2.1.0
