### ISSUE TITLE
Add new scope button is not visible

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#10570] opened 2021-03-30 06:38 UTC
![image](https://user-images.githubusercontent.com/1345278/112944534-9baab800-9150-11eb-81e0-4d69a37f4dee.png)

**Comment by RAVEENSR** [comment] 2021-04-02 10:40
Duplicate of https://github.com/wso2/product-apim/issues/10531. Hence closing.

**Closed by RAVEENSR** 2021-04-02 10:40 UTC
Labels: API-M 4.0.0, Priority/Normal, React-UI, Type/Bug
