### ISSUE TITLE
[UX][Admin] Allow users to select permissions in subscription policies 

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3151] opened 2018-04-02 03:21 UTC
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
User control and freedom

***Related task:***
Add subscription-level/application-level throttling policies

***Issue:***
When adding a subscription policy the user needs to type the full name of the policy. And user is not given details to add multiple roles. 
The permission radio buttons need to be before the input field.
"This tier is **Allowed** for above roles" help tag "Allowed", "Deny" needs to be changed according to the selected permission.

***Proposed Solution:***
Add select 2 multi value select boxes https://select2.org/tagging#tagging-with-multi-value-select-boxes 
	
**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.2.0

**Comment by rmsamitha** [comment] 2022-01-28 04:24
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:24 UTC
Labels: Affected/2.1.0, Affected/2.2.0
