### ISSUE TITLE
Error while creating an API by importing the OAS definition using REST api-publiser V1

### ISSUE THREAD

**Issue by VimukthiMayadunne** [wso2/product-apim#7184] opened 2019-12-20 05:40 UTC
Ho to reproduce:-

1. Send an API request to following  REST API-publisher V1:- 
                   https://apis.wso2.com/api/am/publisher/v1.0/apis/import-openapi
2. Provide the endpoint config incorrect JSON syntax  under additional properties 
```
  formData: {
          url: "https://petstore.swagger.io/v2/swagger.json",
          additionalProperties:
            '{ "name": "PetstoreAPI", "context" : "/petstore", "version" : "1.0.0", "endpointConfig":"{"production_endpoints":{"url":"https://localhost:9443/am/sample/pizzashack/v1.0/api/","config":null},"sandbox_endpoints":{"url":"https://localhost:9443/am/sample/pizzashack/v1.0/api/","config":null},"endpoint_type":"http"}"}'
        }

```

Swagger URL- https://petstore.swagger.io/v2/swagger.json

Once the request is sent sever sent the following response:-
`              {"code":500,"message":"Internal server error","description":"Error while adding new API : null-PetstoreAPI-1.0.0 - Invalid endpoint config JSON found in API: PetstoreAPI 1.0.0","moreInfo":"","error":[]}`

Observation-

1.  Following logs in the server console[1]
2. But in the UI the API is shown even though once click on the API nothing gets loaded to the UI.[2]
3. That API cannot be deleted after creating sends an error message saying something went wrong.[3]
4. Users can't create any more APIs using the same OAS files saying that can't allocate the scope.[4]

[1]  
![Screenshot from 2019-12-20 11-00-34](https://user-images.githubusercontent.com/42222921/71232448-12cf8a80-2318-11ea-8e5a-90aee2dc4f53.png)
![Screenshot from 2019-12-20 11-00-52](https://user-images.githubusercontent.com/42222921/71232456-1400b780-2318-11ea-9dec-31585ccadbe7.png)

[2]
![Screenshot from 2019-12-20 11-01-57](https://user-images.githubusercontent.com/42222921/71232502-3d214800-2318-11ea-86ac-a391485a3f88.png)
![Screenshot from 2019-12-20 11-02-27](https://user-images.githubusercontent.com/42222921/71232503-3eeb0b80-2318-11ea-81d4-c49def861faa.png)

[3]
![Screenshot from 2019-12-20 11-03-10](https://user-images.githubusercontent.com/42222921/71232536-5b874380-2318-11ea-9c08-895675cf630e.png)

[4]
[2019-12-20 11:04:54,112] ERROR - ApisApiServiceImpl Scope read:pets is already assigned by another API
![Screenshot from 2019-12-20 11-04-56](https://user-images.githubusercontent.com/42222921/71232619-b0c35500-2318-11ea-98dd-2564e1229e1f.png)

**Comment by dushaniw** [comment] 2020-02-16 07:40
Cannot reproduce the issue. Tried with the following formData payload for **additionalProperties**,
```
{ "name": "PetstoreAPI", 
"context" : "/petstore", 
"version" : "1.0.0", 
"endpointConfig":"{
	"production_endpoints":{"url":"https://localhost:9443/am/sample/pizzashack/v1.0/api/","config":null},
	"sandbox_endpoints":{"url":"https://localhost:9443/am/sample/pizzashack/v1.0/api/","config":null},
	"endpoint_type":"http"
	}"
}
```
Getting a Bad Request response as expected and the API is not created partially

```
{
    "code": 400,
    "message": "Bad Request",
    "description": "Error while parsing 'additionalProperties'",
    "moreInfo": "",
    "error": []
}
```

**Comment by dushaniw** [comment] 2020-02-16 07:41
Hence reducing the priority.

**Comment by dushaniw** [comment] 2020-02-16 07:44
Closing the issue as we cannot reproduce. Please comment to reopen if you run into the same issue and provide the exact payload used to import API.

**Closed by dushaniw** 2020-02-16 07:44 UTC
Labels: 3.0.0, Priority/Normal, Type/Bug
