### ISSUE TITLE
org.wso2.carbon.relay.ExpandingMessageFormatter has a incorrect ContentType in the axis2.xml

### ISSUE THREAD

**Issue by NipuniC** [wso2/product-apim#3895] opened 2018-10-27 09:29 UTC
**Description:**
In the axis2.xml the below message formatter has an incorrect contentType.
    
```
<messageFormatter contentType="application/octet-streaml" 
                          class="org.wso2.carbon.relay.ExpandingMessageFormatter"/>
```
The contentType should be corrected as **application/octet-stream** removing the additional letter **l** from the end. 
This issue can be seen in both AM-2.2.0 and AM-2.5.0 but not in earlier versions. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
AM-2.2.0 , AM-2.5.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by setterlee** [comment] 2019-05-02 20:34
yeap... happens to me...! must be changed

**Comment by rmsamitha** [comment] 2022-01-28 04:08
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:08 UTC
