### ISSUE TITLE
Endpoint config in publisher REST API for "updating API" doc

### ISSUE THREAD

**Issue by lahirugmg** [wso2/product-apim#8591] opened 2020-07-06 00:17 UTC
### Description:
Sample at [1] doesn't include endpoint configuration even though it is possible. It has 'null' for "config" at all the places.  Can we update it?
{
  "suspendErrorCode": "101504",
  "suspendDuration": "1000",
  "suspendMaxDuration": "5000",
  "factor": "2",
  "retryErroCode": [
    "101504",
    "101505"
  ],
  "retryTimeOut": "3",
  "retryDelay": "1000",
  "actionSelect": "fault",
  "actionDuration": "909090"
}
BTW, have we published Swagger for our Publiser/Stoere APIs somewhere?

[1] https://docs.wso2.com/display/AM210/apidocs/publisher/#!/operations#APIIndividual#apisApiIdPut

### Content Positioning in Documentation:
- Link:https://docs.wso2.com/display/AM210/apidocs/publisher/#!/operations#APIIndividual#apisApiIdPut

- Heading (& Step): Update an API

**Comment by slarti-b** [comment] 2023-07-04 09:54
This kind of thing is important to be able to control via the API if you are trying to do scripted, reproducible installations.  For us, the only way we could get a web socket connection working at all in 4.2.0 was using this config to turn off suspension (this is a work-around for another bug where the global timeout tries to apply to web sockets as well, but still it's the only way they work for any length of time).  It's been open for three years now...

**Comment by lahirus** [comment] 2023-07-04 16:55
I've created a doc issue for new version as well

https://github.com/wso2/docs-apim/issues/7117

**Comment by HiranyaKavishani** [comment] 2024-11-21 10:20
Closing the issue since the doc issue is created

**Closed by HiranyaKavishani** 2024-11-21 10:20 UTC
Labels: Priority/Normal, Type/Docs, Docs/Has Impact
