### ISSUE TITLE
Invocation failure for API Product when relevant API has a sequence

### ISSUE THREAD

**Issue by wggihan** [wso2/product-apim#12465] opened 2022-02-23 12:01 UTC
### Description:
500 internal server error due to $subject.

### Steps to reproduce:
First, create an API with an in sequence. You can use the default offering (disable_chunking etc.). 
This API execution will happen successfully without any issue.
Then create an API Product out of this API.
API Product execution will fail with an internal server error.

### Affected Product Version:
APIM 4.0.0/APIM 4.1.0

**Comment by HiranyaKavishani** [comment] 2022-02-24 04:36
It causes the following error as the synapse mediate trying to find the sequence named Prod:v1.0.0--In
```
{"code":"0","type":"Status report","message":"Runtime Error","description":"Sequence named Value {name ='null', keyValue ='Prod:v1.0.0--In'} cannot be found"}%
```

But the actual name is appended with uuid as bellow (from 400)
`Prod:v1.0.0--0e74b3b9-fc08-4250-8a59-42804ca1f45a--In`

**Comment by CrowleyRajapakse** [comment] 2022-02-28 11:55
Since the sequence related implementation has been changed in APIM 4.1 with OPA feature, this issue Cann't be reproduced in latest post alpha APIM 4.1 pack.

**Comment by chamilaadhi** [comment] 2022-03-15 11:04
Duplicate issue https://github.com/wso2/product-apim/issues/12587 . For 4.0.0 this will be fixed from U2 update

**Comment by tharikaGitHub** [comment] 2022-03-30 12:18
Closing as per the above comments.

**Closed by tharikaGitHub** 2022-03-30 12:18 UTC
Labels: Type/Bug, Priority/Highest, APIM - 4.1.0
