### ISSUE TITLE
[Publisher] Issues when editing the API definition using swagger editor

### ISSUE THREAD

**Issue by nipunsampath** [wso2/product-apim#5997] opened 2019-09-30 08:17 UTC
**Issue:**
Sometimes the cursor moves to the beginning of the page when typing in the swagger editor. 

**Related issue** : https://github.com/wso2/product-apim/issues/5885

**Comment by chamilaadhi** [comment] 2019-10-12 05:02
Related issue https://github.com/wso2/product-apim/issues/5071

**Comment by menakaj** [comment] 2020-02-17 04:47
Duplicate of https://github.com/wso2/product-apim/issues/7446

**Closed by menakaj** 2020-02-17 04:47 UTC
Labels: Priority/High, Severity/Major
