### ISSUE TITLE
[UX] Error message displayed when adding a duplicate policy name should indicate the problem

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3149] opened 2018-04-01 21:59 UTC
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Error Recognition 
- Is error message expressed in plain language 
- Is it precisely indicate the problem

Error Recovery
- Does the error message constructively suggest a solution

***Related task:***
Add advanced throttling policies

***Issue:***
The error message displayed when adding a duplicate policy name does not indicate the problem and the solution. Unwanted data is shown in the message. 
![advanced-throttling-tier-error](https://user-images.githubusercontent.com/9837443/38177656-397f7686-3648-11e8-9d81-b3300dad1064.png)

**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.2.0

**Comment by rmsamitha** [comment] 2022-01-28 04:21
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:21 UTC
Labels: Affected/2.1.0, Affected/2.2.0
