### ISSUE TITLE
[UX] Tenant activation does not give any indication on the active state

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#2918] opened 2018-03-07 12:20 UTC
**Description:**
Tenant activation does not give any indication on the active state

**Suggested Labels:**
improvement 

**Affected Product Version:**
2.1.0

**Steps to reproduce:**
1. log into carbon console
2. goto configure-> multitenancy-> view Tenants 
3. Click on Any activated tenant checkbox
4. The confirmation message appears to confirm the action
5. Now click on the checkbox to activate again

the checkbox will get activated and no status message or indication appears on the screen

**Comment by rmsamitha** [comment] 2022-01-28 04:35
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:35 UTC
Labels: Priority/Low, Affected/2.1.0
