### ISSUE TITLE
[UX] Login page help content are outdated

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#2862] opened 2018-03-06 09:02 UTC
**Description:**
this page contains few links to different doc pages and those are outdated. IMO we can remove those from the login page

About link: https://<host>:9443/carbon/product/about.html
Sign-in Help: https://172.17.0.1:9443/carbon/docs/signin_userguide.html

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    
Ubuntu

**Comment by rmsamitha** [comment] 2022-01-28 04:45
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:45 UTC
Labels: Priority/Normal
