### ISSUE TITLE
Unable to add multiple entries for Alert configurations at the same time in Publisher and Dev Portal with API Manager 3.2.0

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-apim#11439] opened 2021-07-15 07:28 UTC
### Description:
When we try to add multiple entries at the same time for Alert Configurations in Publisher and Dev Portal, the '+' mark will be disabled.

### Steps to reproduce:

- Go to Publisher Portal -> Settings. Then click the Settings button of 'Abnormal Response Time' and then click '+ New Configuration'.
- After adding API Name, Version and 'Abnormal Response Time', click + mark to add. The entry should be successfully added and displayed in the list.
- Then again click '+ New Configuration' and try to add another entry but the '+' mark is disabled.

<img width="1425" alt="Disable_Plus_Mark" src="https://user-images.githubusercontent.com/8849472/125634835-3793d493-724a-497c-89ec-2ae909ffc581.png">

- This is common for 'Abnormal Backend Time' in publisher and 'Abnormal Requests per Minute' in Dev Portal as well.

### Affected Product Version:
API Manager 3.2.0

**Comment by YasasRangika** [comment] 2021-08-24 11:13
We can close this issue since this is not reproducing in master.

**Closed** 2021-08-24 12:19 UTC
Labels: Type/Bug, Priority/Normal
