### ISSUE TITLE
Improvement in the view of custom subscription policy

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#7025] opened 2019-11-29 09:06 UTC
Shall we keep it as empty instead of showing null, if the user did not add any description to custom subscription tier?

![image](https://user-images.githubusercontent.com/19728269/69856396-936c0f80-12b3-11ea-9a61-10bf3281075f.png)

**Comment by Meruja** [comment] 2019-12-02 06:37
Unable to reproduce the issue
<img width="603" alt="Screenshot 2019-12-02 at 12 06 22 PM" src="https://user-images.githubusercontent.com/28688743/69935889-34e5a200-14fc-11ea-8d98-fd1037f31078.png">

**Comment by dushaniw** [comment] 2019-12-04 05:51
This is reproducible with only with Oracle as Oracle does not support keeping the EMPTY string in tables. As this depends entirely on the behavior of the database, we might can add a check from UI side.

**Comment by chanaka3d** [comment] 2020-10-03 01:34
Fixed with carbon-apimgt 6.8.40-SNAPSHOT

**Closed by chanaka3d** 2020-10-03 01:34 UTC
Labels: Affected/3.0.0, Affected/3.1.0, Priority/Low, Type/React-UI
