### ISSUE TITLE
[UX] Carbon console login page client side validation 

### ISSUE THREAD

**Issue by dakshika** [wso2/product-apim#2896] opened 2018-03-07 07:00 UTC
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Error recognition --Is it precisely indicate the problem

***Related task:***
Login to carbon console

***Issue:***
We need to add $subject, currently even with single empty filed we are getting the same error message. 

***Proposed Solution:***
Need to do inline field validation
	
***Doc Link:***

**Affected Product Version:**
2.1.0 

**Steps to reproduce:**
1. Enter username
2. press sign in

**Comment by rmsamitha** [comment] 2022-01-28 04:36
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:36 UTC
Labels: Priority/Low, 3.x.x, Affected/2.1.0
