### ISSUE TITLE
Are we dropping the general forum for store

### ISSUE THREAD

**Issue by chanaka3d** [wso2/product-apim#3113] opened 2018-03-19 04:46 UTC
**Description:**
In addition to the per API forum we have a general forum in the 2.x

<img width="1003" alt="screen shot 2018-03-19 at 10 13 30 am" src="https://user-images.githubusercontent.com/3424539/37578378-77ed0a68-2b5e-11e8-941f-8c6f7bdaca03.png">

Are we dropping this feature for 3.0.0?

**Comment by nuwand** [comment] 2018-03-19 04:48
Let's leave it under low priority at the moment. We need to add it, but not super urgent for 3.0.0, maybe in 3.1.0.

**Comment by rmsamitha** [comment] 2022-01-28 04:21
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:21 UTC
Labels: Type/Task, Type/Question, Priority/Low, Affected/3.0.0
