### ISSUE TITLE
WSO2 APIM java client SDK returns org.wso2.client.api.ApiException: Content type “text/xml” is not supported

### ISSUE THREAD

**Issue by doudoubean** [wso2/product-apim#3854] opened 2018-10-16 05:48 UTC
**Description:**
I've created an API using WSO2 Api Manager and downloaded JAVA client SDK.When I tried to send soap request using client SDK I'm getting an error org.wso2.client.api.ApiException: Content type "text/xml" is not supported

**Suggested Labels:**
Java client SDK

**Affected Product Version:**
Affected Product Version:2.5.0
**OS, DB, other environment details and versions:**    
OS: windows7 ultimate x64
DB:h2
jdk version:1.8.0_144
maven version:3.5.0
**Steps to reproduce:**
1、unzip downloaded java client sdk
2、execute "mvn install" command
3、create a maven project in intellij idea IDE
4、according to sdk readme documentation instruction，add related dependency to pom.xml
5、create a test class
6、run test program.

`import org.wso2.client.api.*;
import org.wso2.client.api.auth.*;
import org.wso2.client.api.SoapTest.DefaultApi;

import java.io.File;
import java.util.*;

public class DefaultApiExample {

    public static void main(String[] args) {

        DefaultApi apiInstance = new DefaultApi();
        String soAPRequest = "<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:quer=\"http://ws.cdyne.com/PhoneVerify/query\">\n" +
                "   <soapenv:Header/>\n" +
                "   <soapenv:Body>\n" +
                "      <quer:CheckPhoneNumber>\n" +
                "         \n" +
                "         <quer:PhoneNumber>18006785432</quer:PhoneNumber>\n" +
                "         \n" +
                "         <quer:LicenseKey>0</quer:LicenseKey>\n" +
                "      </quer:CheckPhoneNumber>\n" +
                "   </soapenv:Body>\n" +
                "</soapenv:Envelope>"; // String | SOAP request.
        String soAPAction = "http://ws.cdyne.com/PhoneVerify/query/CheckPhoneNumber"; // String | SOAPAction header for soap 1.1
        try {
            apiInstance.post(soAPRequest, soAPAction);
        } catch (ApiException e) {
            System.err.println("Exception when calling DefaultApi#post");
            e.printStackTrace();
        }
    }
}`

**Comment by prats2017** [comment] 2019-09-05 20:24
@doudoubean Did you find the fix for your issue. I am currently stuck with the same issue and there is no help on Net.

**Comment by rmsamitha** [comment] 2022-01-28 04:08
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:08 UTC
