### ISSUE TITLE
Page loop Publisher Wso2 APIM (ERROR - WebAppManager org.mozilla.javascript.EcmaError: SyntaxError: Unexpected token: < (<<http>>/META-INF/scripts/http.js#17))

### ISSUE THREAD

**Issue by hungtv-86** [wso2/product-apim#7262] opened 2020-01-16 10:59 UTC
[2020-01-16 16:56:28,054] ERROR - WebAppManager org.mozilla.javascript.EcmaError: SyntaxError: Unexpected token: < (<<http>>/META-INF/scripts/http.js#17)
org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: SyntaxError: Unexpected token: < (<<http>>/META-INF/scripts/http.js#17)
        at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:587) ~[org.jaggeryjs.scriptengine_0.14.11.jar:?]
        at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:289) ~[org.jaggeryjs.scriptengine_0.14.11.jar:?]
        at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:589) [org.jaggeryjs.jaggery.core_0.14.11.jar:?]
        at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508) [org.jaggeryjs.jaggery.core_0.14.11.jar:?]
        at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24) [org.jaggeryjs.jaggery.core_0.14.11.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-servlet-api_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) [tomcat_9.0.22.wso2v1.jar:?]
        at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:76) [org.jaggeryjs.jaggery.core_0.14.11.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
        at org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53) [org.wso2.carbon.ui_4.5.1.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat_9.0.22.wso2v1.jar:?]
        at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:80) [org.wso2.carbon.identity.context.rewrite.valve_1.3.6.jar:?]
        at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:100) [org.wso2.carbon.identity.authz.valve_1.3.6.jar:?]
        at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:74) [org.wso2.carbon.identity.auth.valve_1.3.6.jar:?]
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
        at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
        at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
        at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:146) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) [tomcat_9.0.22.wso2v1.jar:?]
        at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
        at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:116) [org.wso2.carbon.tomcat.ext_4.5.1.jar:?]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587) [tomcat_9.0.22.wso2v1.jar:?]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat_9.0.22.wso2v1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat_9.0.22.wso2v1.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: org.mozilla.javascript.EcmaError: SyntaxError: Unexpected token: < (<<http>>/META-INF/scripts/http.js#17)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3687) ~[js_1.7.0.R4wso2v1.jar:?]
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3665) ~[js_1.7.0.R4wso2v1.jar:?]
        at org.mozilla.javascript.NativeJSON.parse(NativeJSON.java:112) ~[js_1.7.0.R4wso2v1.jar:?]
        at org.mozilla.javascript.NativeJSON.execIdCall(NativeJSON.java:88) ~[js_1.7.0.R4wso2v1.jar:?]
        at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97) ~[js_1.7.0.R4wso2v1.jar:?]
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) ~[js_1.7.0.R4wso2v1.jar:?]
        at org.jaggeryjs.rhino.<<http>>.META_INF.scripts.c0._c_anonymous_2(<<http>>/META-INF/scripts/http.js:17) ~[?:?]
        at org.jaggeryjs.rhino.<<http>>.META_INF.scripts.c0.call(<<http>>/META-INF/scripts/http.js) ~[?:?]
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63) ~[js_1.7.0.R4wso2v1.jar:?]
        at org.jaggeryjs.rhino.<<http>>.META_INF.scripts.c0._c_anonymous_5(<<http>>/META-INF/scripts/http.js:221) ~[?:?]
        at org.jaggeryjs.rhino.<<http>>.META_INF.scripts.c0.call(<<http>>/META-INF/scripts/http.js) ~[?:?]
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63) ~[js_1.7.0.R4wso2v1.jar:?]
        at org.jaggeryjs.rhino.<<http>>.META_INF.scripts.c0._c_anonymous_8(<<http>>/META-INF/scripts/http.js:232) ~[?:?]
        at org.jaggeryjs.rhino.<<http>>.META_INF.scripts.c0.call(<<http>>/META-INF/scripts/http.js) ~[?:?]
        at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63) ~[js_1.7.0.R4wso2v1.jar:?]
        at org.jaggeryjs.rhino.publisher.services.login.c2._c_script_0(/publisher/services/login/introspect.jag:36) ~[?:?]
        at org.jaggeryjs.rhino.publisher.services.login.c2.call(/publisher/services/login/introspect.jag) ~[?:?]
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) ~[js_1.7.0.R4wso2v1.jar:?]
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) ~[js_1.7.0.R4wso2v1.jar:?]
        at org.jaggeryjs.rhino.publisher.services.login.c2.call(/publisher/services/login/introspect.jag) ~[?:?]
        at org.jaggeryjs.rhino.publisher.services.login.c2.exec(/publisher/services/login/introspect.jag) ~[?:?]
        at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:583) ~[org.jaggeryjs.scriptengine_0.14.11.jar:?]

**Comment by hungtv-86** [comment] 2020-01-16 11:04
i deployed with:
- java 1.8.0
- nginx

**Comment by tmkasun** [comment] 2020-01-17 04:59
Hi @hungtv-86 ,

I have a few points to clarify,

- What is the API Manager 3.x version you are using?
- Did you change the server hostname in `deployment.toml` file.
- Have you enabled reverse proxy?

The cause of this issue is , The introspect API call gets an unexpected HTML page (most probably some error page from proxy or ngix instead of the expected JSON response).

That's why the exception says 

```
 Unexpected token: < 
```

**Comment by hungtv-86** [comment] 2020-01-17 05:12
hi @tmkasun 
- Current, i deployment with:
+ API Manager 3.0.0
+ Changed hostname

**Comment by hungtv-86** [comment] 2020-01-17 05:13
@tmkasun you have use Skype?

**Comment by tmkasun** [comment] 2020-01-17 18:23
Hi @hungtv-86 ,

Most probably the problem is , API Manager publisher node tries to make a call to 

```
https://<your-host-name>/oauth2/introspect
```
endpoint but it is not accessible from the API manager Publisher node/pod.

**Comment by hungtv-86** [comment] 2020-01-18 02:38
@tmkasun Current, i use version 3.1.0-M5, it working bro

**Comment by hungtv-86** [comment] 2020-01-18 09:07
@tmkasun I configing multi api gateway in 1 instance, you can support for me?
i did with docs: https://apim.docs.wso2.com/en/next/Learn/DesignAPI/PublishAPI/publish-through-multiple-api-gateways/
but i only want use 2 enviroment: sandbox and production
![image](https://user-images.githubusercontent.com/54196319/72661423-74b10c00-3a0c-11ea-892a-3deeb0b30d4d.png)

and here is error
![image](https://user-images.githubusercontent.com/54196319/72661437-a033f680-3a0c-11ea-8d9d-78e60361f31b.png)

**Comment by tmkasun** [comment] 2020-01-23 08:07
@hungtv-86 ,

Can you provide the full stack trace in server logs, And it seems devportal app is not loading in the browser with this error ?

can you provide the `deployment.toml` file as well?

**Comment by fernandocyder** [comment] 2020-02-28 11:12
@hungtv-86 , it happened to me. That happened to me because I have both APIM and WSO2 Identity Server installed on the same server , and I reverse-proxy them using the same NGINX instance running on the two different server configuration but listen on the same port 443.

This issue is resolved after having separate NGINX server configuration and running on different port, APIM NGINX on 443, and ID NGINX on 444.

So, this is surely due to NGINX mis-configuration

**Comment by isharac** [comment] 2020-12-17 04:29
I’m closing this issue as per the above comment. Please reopen if you still encounter this issue with the latest version.

**Closed by isharac** 2020-12-17 04:29 UTC
Labels: Affected/3.0.0, Type/Question
