### ISSUE TITLE
API Product subscriptions are not displayed under the API subscription page.

### ISSUE THREAD

**Issue by TheRasanjana** [wso2/product-apim#10457] opened 2021-03-26 08:02 UTC
### Description:

![image](https://user-images.githubusercontent.com/32265029/112598936-7cb4ca80-8dcc-11eb-9215-9e177ed18ea2.png)

visible in application's subscriptions section
![image](https://user-images.githubusercontent.com/32265029/112598984-8c341380-8dcc-11eb-9887-628a81db49a3.png)

### Steps to reproduce:

- Create an API Product 
- subscribe an application
- Go to the API product in DevPortal
- Click subscriptions

### Affected Product Version:
API-M 4.0.0 

### Environment details (with versions):
- OS: Windows 10
- DB: MSSQL 2019

#### Suggested Labels:
API-M 4.0.0, Priority/High

**Comment by rmsamitha** [comment] 2021-04-01 14:32
Closing as the issue is not reproduced in the product based on carbon-apimgt 9.0.82.SNAPSHOT and 9.0.89 component versions. Issue had been reported earlier on an older version.

**Closed by rmsamitha** 2021-04-01 14:32 UTC
Labels: API-M 4.0.0, Feature/APIProducts, Priority/High, Type/Bug
