### ISSUE TITLE
Error in Quota allocation regarding Subscription Throttling Policies

### ISSUE THREAD

**Issue by SabinaPrasadhi** [wso2/product-apim#5851] opened 2019-09-26 12:42 UTC
Use Case: Help the subscribers to evenly distribute the allocated quota among application users
Test Scenario: Edit already set subscription policy to limit the max requests per time within the allocated subscription policy plan, 
* where subscription plan has already used in subscription (subscribed to API)
* burst control limit <= allocated plan
Should not change the subscription quota for already subscribed API

Details of the Issue: Issue encountered in editing already set subscription policy to limit the max requests per time within the allocated subscription policy plan. Subscription quota changed for already subscribed API. When I changed the rate limiting of Bronze throttling tier from 5 per minute to 10 per minute, it affected to the already subscribed API.

Relevant Screenshots: 
(5 per min)
![Screenshot from 2019-09-26 18-01-36](https://user-images.githubusercontent.com/38970634/65688615-0f19c800-e089-11e9-9880-e17b4bfdabc6.png)

(10 per min)
![Screenshot from 2019-09-26 18-00-21](https://user-images.githubusercontent.com/38970634/65688627-1640d600-e089-11e9-9b53-65b3002257a2.png)

**Comment by menakaj** [comment] 2020-02-25 06:11
This is the expected behaviour. Hence Not a Bug. Closing.

**Closed by menakaj** 2020-02-25 06:11 UTC
Labels: 3.0.0, Priority/Highest, Resolution/Not a bug, Type/Bug
