### ISSUE TITLE
API Manager 3.0.0 doesn't support OpenApi specification in yaml format

### ISSUE THREAD

**Issue by igkononov** [wso2/product-apim#6819] opened 2019-11-13 11:13 UTC
To whom it may concern,

WSO2 API Manager 3.0.0 doesn’t support OpenApi specification in yaml format - only json. However, Ballerina (WSO2 language for creating microservices) generates OpenApi specification in yaml format. This case looks like bug. 
E.g. WSO2 API Manager 2.6.0 support OpenApi specification in yaml.

Can you, please, clarify this situation.
Is it a bug?

Thanks in advance.

**Comment by tmkasun** [comment] 2019-11-14 02:29
Hi @igkononov ,

We support OpenAPI definition in both yaml URL and File for creating an API.

![image](https://user-images.githubusercontent.com/3313885/68821436-5b11e200-06b4-11ea-93dd-e909628eed6d.png)

![image](https://user-images.githubusercontent.com/3313885/68821477-78df4700-06b4-11ea-8c21-a8d8d066acea.png)


I tried to re-produce this issue using OpenAPI yaml samples in [here](https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v3.0), But could not reproduce the issue.

Could you please provide more information on this, 

- Did you get any error when creating API from OpenAPI yaml file
- Can you provide browser console logs
- Can you provide carbon logs in the backend

**Comment by igkononov** [comment] 2019-11-14 07:53
Hi @tmkasun,

I have a problem in API Manager 3.0.0 without any errors. Simply, when I try to set yaml file from local File system, API Manager doesn't offer possibility to choose such file.

<img width="642" alt="Screen Shot 2019-11-14 at 9 52 50 AM" src="https://user-images.githubusercontent.com/56588985/68837136-99af9880-06c4-11ea-975e-659323172fae.png">
<img width="190" alt="Screen Shot 2019-11-14 at 9 52 13 AM" src="https://user-images.githubusercontent.com/56588985/68837140-9c11f280-06c4-11ea-993b-3c576a937446.png">

**Comment by tmkasun** [comment] 2019-11-14 17:43
Hi @igkononov ,

I was able to reproduce this issue in the latest API Manager server as well. Hence I have marked this as a Bug and made its priority high.
Thank you very much for reporting this issue.
As a workaround, You can drag and drop the OpenAPI definition in yaml format to drop zone and it will accept the yaml file.

**Comment by igkononov** [comment] 2019-11-15 07:17
@tmkasun 
Thanks for your help and answers

**Comment by tmkasun** [comment] 2019-11-27 04:08
This issue has been fixed by this commit https://github.com/wso2/carbon-apimgt/pull/7940/files#diff-d9c3f8eec7d367fbd7dee26c53a40d27R254 , hence closing the issue

**Closed** 2019-11-27 04:07 UTC
Labels: 3.0.0, 3.1.0, Priority/Highest, Type/Bug, Type/React-UI
