### ISSUE TITLE
[APIM210] Resources weren't listed under API Definition in UI when creating an API with REST services

### ISSUE THREAD

**Issue by maneeshaheshan** [wso2/product-apim#3268] opened 2018-05-10 10:06 UTC
**Description:**
When creating an API with REST services by adding both GET and POST as resources by parameterizing the values for API Name and context in jmeter, the API created but once we edit the API, it won't show any resources defined using jmeter. But when checking the sysnape of the API in [APIM_HOME]/repository/deployment/server/synapse-configs/default/api , it contains the API resources and the issue only displayed when viewing the API in UI.

**Suggested Labels:**
2.1.0, REST_API, Severity/Major, Priority/High, Type/Bug 

**Affected Product Version:**
API Manager 2.1.0

**OS, DB, other environment details and versions:**    
Ubuntu 16.04, H2 DB

**Steps to reproduce:**

- Start API Manager 2.1.0 server
- Run the jmeter script in [1] which has parameterized the API Name and context with a counter to create 3 APIs.
- Go to Publisher, list the created APIs and click edit of a recently created API.

As you can see, in 'Design' tab there's no defined resources listed under 'API Definition'. But the synapse of the API [1] (ex-WikiAPI2) contains the resource and it works fine when invoking the API.

![api creation_resources](https://user-images.githubusercontent.com/8849472/39863817-5a2007da-5465-11e8-86cc-2368ff8aa766.png)

[1] [API_Creation.zip](https://github.com/wso2/product-apim/files/1990659/API_Creation.zip)

**Comment by kasunbg** [comment] 2018-05-10 11:46
@maneeshaheshan This seems like an issue we need to fix. In the meanwhile, is there a workaround available that we can try? May be it'll work if we update the created API after re-adding API definitions?

**Comment by rmsamitha** [comment] 2022-01-28 04:14
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:14 UTC
Labels: Affected/2.1.0
