### ISSUE TITLE
APIM custom user login issues

### ISSUE THREAD

**Issue by kaushikbiswas1984** [wso2/product-apim#7542] opened 2020-02-24 11:41 UTC
I have installed WSO2 APIM 3 in windows environment. I have followed the LMS instructions to create the users but the user created doesn't work and shows the attached error.
[PracticalExercise_DefiningUsersandRoles-200213-120149.pdf](https://github.com/wso2/product-apim/files/4244342/PracticalExercise_DefiningUsersandRoles-200213-120149.pdf)

**Comment by kaushikbiswas1984** [comment] 2020-02-24 11:42
![Login](https://user-images.githubusercontent.com/44670045/75149787-cf830500-5728-11ea-82a6-bb9b4755dca4.JPG)

**Comment by CrowleyRajapakse** [comment] 2020-02-25 05:09
Hi @kaushikbiswas1984 , 
When creating the users assign following roles to users as well,
apicreator - > internal/creator role
apipublisher -> internal/publisher role
john(devportal user) - > internal/subscriber role

**Comment by CrowleyRajapakse** [comment] 2020-02-25 06:41
This is happening due to users not having proper minimum roles when accessing portals, therefor not a bug.

**Comment by kaushikbiswas1984** [comment] 2020-02-25 08:43
Thanks for quick turnaround. Really appreciate that. Your solution might work as a workaround but I would like to know why the custom role with permissions do not work. 
Which permissions are additionally required?

**Comment by pubudu538** [comment] 2020-03-02 09:02
Hi @kaushikbiswas1984,

In API Manager v3.0.0 we developed our publisher and devportal(Store) based on the REST APIs we have exposed from the product. A resource is secured from the scope which is mapped with the role. When you create a new role, you need to add that role to the scope mapping. You can find that information in [1]. Although you have the relevant permission to the role, this does not work. 

As this is not an issue, I will be closing this issue. If you further need any help on this, please do reopen this issue.

[1] - https://apim.docs.wso2.com/en/latest/administer/product-administration/managing-users-and-roles/managing-user-roles/#managing-user-roles

Thank you!
Pubudu.

**Closed by pubudu538** 2020-03-02 09:02 UTC
Labels: Priority/Normal, Type/Question
