### ISSUE TITLE
[APIM-2.6.0]-Document type Microsoft Excel(XLSX) upload Issue

### ISSUE THREAD

**Issue by saranki** [wso2/product-apim#11496] opened 2021-07-29 10:36 UTC
### Description:
Trying to upload a spreadsheet with the extension of .xlsx through wso2 rest API and throws below 400 error.

```
{
  "code": 400,
  "message": "Bad Request",
  "description": "Unsupported extension type of document file: UAT-GEN3-OS-Hardware-Spec.xlsx",
  "moreInfo": "",
  "error": []
}
```

### Steps to reproduce:

1. Generate Token

```
curl -X POST 'https://vlcapepoapigw04.fisdev.local:8243/token' -H 'Authorization: Basic dXRXZjN4NWVVNmUyVjNDZHg0WENBWnpaMWNVYTpkbDRWckpVN3d4SnpWMnNUZE5BYjBvNUVWUzhh' -H 'content-type: application/x-www-form-urlencoded' --data-urlencode 'grant_type=password' --data-urlencode 'username=ecode' --data-urlencode 'password=xxxxxxxxx' --data-urlencode 'scope=apim:api_view apim:api_create apim:api_publish apim:mediation_policy_view apim:mediation_policy_create'
```

2. Get API details list

```
curl --location --request GET 'https://vlcapepoapigw04.fisdev.local:9443/api/am/publisher/v0.14/apis' --header 'Authorization: Bearer 64242e96-070f-3161-a4d2-e4e4e42c48ee'
```

3. Get document ID from specific API

```
curl -X GET 'https://vlcapepoapigw04.fisdev.local:9443/api/am/publisher/v0.14/apis/29450018-e13c-41a6-b0f2-dad7d56426f4/documents' -H 'Authorization: Bearer 64242e96-070f-3161-a4d2-e4e4e42c48ee'
```

4. Add document

```
curl -k -H "Authorization: Bearer 64242e96-070f-3161-a4d2-e4e4e42c48ee" -H "Content-Type: application/json" -X POST -d @dataFileXls.json "https://vlcapepoapigw04.fisdev.local:9443/api/am/publisher/v0.14/apis/29450018-e13c-41a6-b0f2-dad7d56426f4/documents" -vk
```

where the dataFileXls.json contains,
```
{ "visibility": "API_LEVEL", "sourceType": "FILE", "sourceUrl": null, "otherTypeName": null, "summary": "This is a sample documentation", "name": "Introduction to PizzaFile API XLS", "type": "HOWTO" }
```

5. Get the new Document id

```
curl -k -H "Authorization:Bearer 64242e96-070f-3161-a4d2-e4e4e42c48ee" -F file=@"UAT-GEN3-OS-Hardware-Spec.xlsx" -X POST "https://vlcapepoapigw04.fisdev.local:9443/api/am/publisher/v0.14/apis/29450018-e13c-41a6-b0f2-dad7d56426f4/documents/18ceadb6-2183-406c-8502-d339e8d5b2b6/content" -kv
```

6. So, the above the last curl is trying to upload UAT-GEN3-OS-Hardware-Spec.xlsx in this example and failed.
Response

```
< HTTP/1.1 400 Bad Request
< Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' data: *.fnis.com *.fisglobal.com *.prod.local *.fisdev.local *.swagger.io *.googletagmanager.com *.google-analytics.com
< Date: Tue, 27 Jul 2021 21:02:04 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: close
< Server: WSO2 Carbon Server
<
{ [158 bytes data]
100 15688    0   152  100 15536    183  18763 --:--:-- --:--:-- --:--:-- 18946{"code":400,"message":"Bad Request","description":"Unsupported extension type of document file: UAT-GEN3-OS-Hardware-Spec.xls","moreInfo":"","error":[]}
Closing connection 0
```

### Affected Product Version:
wso2am-2.6.0

#### Related Issues:
https://github.com/wso2-support/carbon-apimgt/pull/3428

**Comment by HeshanSudarshana** [comment] 2024-03-12 05:08
Closing the issue since this is not reproduced in the latest APIM 4.3.0-alpha pack.

**Closed by HeshanSudarshana** 2024-03-12 05:08 UTC
Labels: Type/Bug, Priority/Normal
