### ISSUE TITLE
APIM 4.0.0 - High constant CPU usage

### ISSUE THREAD

**Issue by juanledesma84** [wso2/product-apim#12028] opened 2021-11-17 18:31 UTC
### Description:
I did the migration from APIM 2.1.0 to APIM 4.0.0. The deployment was initially done to AWS Fargate using 1 single instance (4vCPU and 8GB memory). When the product was not live, and I was testing it, it was running smoothly. When we went live, after a while of use, the CPU usage was 99%. We increased the resources to 4vCpu and 16GB of memory, but the problem persisted.

Then, I decided to deploy the product in 2 EC2 instances, with 8vCPUs and 16GB of memory (c5.2xlarge), with an active-active all-in-one configuration, but the CPU problem also showed up in the 2 EC2 instances.

I followed the recommended troubleshooting tips, but I don't know what to do with that information. How can I fix the incident

**Thread dump** (file attached)

%CPU CPU  NI S     TIME     PID     TID
60.7   -   0 R 13:07:51   44806   45103
47.0   -   0 R 10:09:40   44806   45104
47.0   -   0 R 10:09:28   44806   45105
50.4   -   0 R 10:54:05   44806   45106
22.9   -   0 R 04:57:57   44806   45107
59.6   -   0 R 12:52:57   44806   45108
34.3   -   0 R 07:25:38   44806   45109
57.3   -   0 R 12:23:30   44806   45110

**Thread usage** (file attached)

**TID: 45103**
"HTTPS-Listener I/O dispatcher-9" #233 prio=5 os_prio=0 cpu=47258272.35ms elapsed=77740.42s tid=0x000056549f7a0800 nid=0xb02f runnable  [0x00007f0eea2e2000]
   java.lang.Thread.State: RUNNABLE
	at org.apache.http.nio.reactor.ssl.SSLIOSession.inboundTransport(SSLIOSession.java:572)
	- locked <0x0000000585808840> (a org.apache.http.nio.reactor.ssl.SSLIOSession)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:123)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:224)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)

**TID: 45104**
"HTTPS-Listener I/O dispatcher-10" #234 prio=5 os_prio=0 cpu=36567499.22ms elapsed=77740.42s tid=0x000056549f757000 nid=0xb030 runnable  [0x00007f0eea1e1000]
   java.lang.Thread.State: RUNNABLE
	at sun.security.ssl.SSLEngineImpl.checkParams(java.base@11.0.11/SSLEngineImpl.java:408)
	at sun.security.ssl.SSLEngineImpl.wrap(java.base@11.0.11/SSLEngineImpl.java:133)
	- locked <0x000000059a4ad148> (a sun.security.ssl.SSLEngineImpl)
	at sun.security.ssl.SSLEngineImpl.wrap(java.base@11.0.11/SSLEngineImpl.java:116)
	- locked <0x000000059a4ad148> (a sun.security.ssl.SSLEngineImpl)
	at javax.net.ssl.SSLEngine.wrap(java.base@11.0.11/SSLEngine.java:482)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doWrap(SSLIOSession.java:270)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:316)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:541)
	- locked <0x000000059a481800> (a org.apache.http.nio.reactor.ssl.SSLIOSession)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)

**TID: 45105**
"HTTPS-Listener I/O dispatcher-11" #235 prio=5 os_prio=0 cpu=36555310.63ms elapsed=77740.42s tid=0x000056549f772800 nid=0xb031 runnable  [0x00007f0eea0e0000]
   java.lang.Thread.State: RUNNABLE
	at org.apache.http.nio.reactor.ssl.SSLIOSession.inboundTransport(SSLIOSession.java:572)
	- locked <0x000000054fdf0040> (a org.apache.http.nio.reactor.ssl.SSLIOSession)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:123)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)

**TID: 45106**
"HTTPS-Listener I/O dispatcher-12" #236 prio=5 os_prio=0 cpu=39232103.44ms elapsed=77740.42s tid=0x000056549f793000 nid=0xb032 runnable  [0x00007f0ee9fdf000]
   java.lang.Thread.State: RUNNABLE
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:163)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)

**TID: 45107**
"HTTPS-Listener I/O dispatcher-13" #237 prio=5 os_prio=0 cpu=17864317.75ms elapsed=77740.42s tid=0x000056549f7a4000 nid=0xb033 runnable  [0x00007f0ee9ede000]
   java.lang.Thread.State: RUNNABLE
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:283)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)

**TID: 45108**
"HTTPS-Listener I/O dispatcher-14" #238 prio=5 os_prio=0 cpu=46364295.55ms elapsed=77740.42s tid=0x000056549f7a6800 nid=0xb034 runnable  [0x00007f0ee9ddd000]
   java.lang.Thread.State: RUNNABLE
	at java.util.HashMap.hash(java.base@11.0.11/HashMap.java:339)
	at java.util.HashMap.get(java.base@11.0.11/HashMap.java:552)
	at java.util.Collections$SynchronizedMap.get(java.base@11.0.11/Collections.java:2594)
	- locked <0x000000053d917cc0> (a java.util.Collections$SynchronizedMap)
	at org.apache.http.impl.nio.reactor.IOSessionImpl.getAttribute(IOSessionImpl.java:271)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:108)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:224)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)

**TID: 45109**
"HTTPS-Listener I/O dispatcher-15" #239 prio=5 os_prio=0 cpu=26724856.08ms elapsed=77740.42s tid=0x000056549f750000 nid=0xb035 runnable  [0x00007f0ee9cdc000]
   java.lang.Thread.State: RUNNABLE
	at org.apache.http.nio.reactor.ssl.SSLIOSession.inboundTransport(SSLIOSession.java:572)
	- locked <0x000000055db57600> (a org.apache.http.nio.reactor.ssl.SSLIOSession)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:123)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)

**TID: 45110**
"HTTPS-Listener I/O dispatcher-16" #240 prio=5 os_prio=0 cpu=44596801.67ms elapsed=77740.42s tid=0x000056549f83f800 nid=0xb036 runnable  [0x00007f0ee9bdb000]
   java.lang.Thread.State: RUNNABLE
	at sun.security.ssl.SSLEngineImpl.checkParams(java.base@11.0.11/SSLEngineImpl.java:408)
	at sun.security.ssl.SSLEngineImpl.wrap(java.base@11.0.11/SSLEngineImpl.java:133)
	- locked <0x0000000599a389f8> (a sun.security.ssl.SSLEngineImpl)
	at sun.security.ssl.SSLEngineImpl.wrap(java.base@11.0.11/SSLEngineImpl.java:116)
	- locked <0x0000000599a389f8> (a sun.security.ssl.SSLEngineImpl)
	at javax.net.ssl.SSLEngine.wrap(java.base@11.0.11/SSLEngine.java:482)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doWrap(SSLIOSession.java:270)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:316)
	at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:541)
	- locked <0x0000000599a389b8> (a org.apache.http.nio.reactor.ssl.SSLIOSession)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
	at java.lang.Thread.run(java.base@11.0.11/Thread.java:829)

I attach the files generated by the troubleshooting process in one of the instances.

### Steps to reproduce:
Constant traffic

### Affected Product Version:
Affected/4.0.0

### Environment details (with versions):
- OS: Ubuntu 20.04
- Client: APIM 4.0.0
- Env (Docker/K8s): 2 AWS EC2 instances (c5.2xlarge) All-in-one active-active configuration
- Java: OpenJDK 11.0.11 (11.0.11+9)
- JVM_MEM_OPTS="-Xms2048m -Xmx12288m"

--
[thread-dump.txt](https://github.com/wso2/product-apim/files/7556969/thread-dump.txt)
[thread-usage.txt](https://github.com/wso2/product-apim/files/7556971/thread-usage.txt)
-

**Comment by arunans23** [comment] 2021-11-19 09:25
@juanledesma84 Can you try adding the following system properties in the startup script (api-manager.sh)? 

```
-Djdk.tls.acknowledgeCloseNotify=true
-Djdk.tls.client.protocols=TLSv1,TLSv1.1,TLSv1.2
```

**Comment by juanledesma84** [comment] 2021-11-22 17:07
@arunans23 I just added them. I will monitor the behavior of the CPU with the change.

By the way, look at this incident: https://github.com/wso2/product-apim/issues/8908 and change the java version to OpenJDK 11.0.1. Which version should I use? Because with the version change of of Java the problem persists.

**Comment by arunans23** [comment] 2021-11-22 17:19
@juanledesma84 The incident you mentioned is for APIM 3.2.0 and below versions. APIM 4.0.0 is compatible with all the minor versions of JDK 11. If you still run into issues, please let us know.

**Comment by SlobodanRasetic** [comment] 2021-11-22 18:51
HI @arunans23. I work with @juanledesma84 and he has just put your fix in place. What we see is that under some steady but pretty light weight load the CPU gradually increases to 100%. It can take a couple of days to get there. This is the behavior right now. You can see the CPU dropping after a restart this morning but I can already that one if the servers has climbed to 13% already and it is staying there instead of fluctuating.

![image](https://user-images.githubusercontent.com/50634578/142917743-71ab0d46-b87a-481c-8cf0-2798c41cf9b2.png)

**Comment by SlobodanRasetic** [comment] 2021-11-22 20:14
Hi @arunans23 and @juanledesma84. That change did not fix the problem. We are starting to see our CPU continuously climb again.

![image](https://user-images.githubusercontent.com/50634578/142928728-40fecf55-1eaa-4ad5-88e0-a553913745e9.png)

**Comment by SlobodanRasetic** [comment] 2021-11-23 17:36
Hi @arunans23. After running our APIM with your fix in place, CPU is trending upwards even in our staging environment that is running a very light load.  We had no problems with the previous version 2.6 of APIM that we have been using for years with the same load and the same APIs.

![image](https://user-images.githubusercontent.com/50634578/143074776-171a8418-e497-41a4-96cb-9e83aaaec9b6.png)

Can you please try to replicate the problem on your side? You cold use JMeter to simulate the steady load over a longer period of time, like 24 hours. It would also be good if you hit multiple sample APIS in your test to be closer to reality.

**Comment by SlobodanRasetic** [comment] 2021-11-24 16:04
This morning after running the APIM in our staging environment for less than 2h hours after a restart the CPU on both nodes is basically at 100% at stays there forever.

![image](https://user-images.githubusercontent.com/50634578/143273317-15869918-d191-4b4f-9687-bd091e92644f.png)

**Comment by arunans23** [comment] 2021-11-30 06:07
Hey @juanledesma84. I tried to reproduce the issue, but couldn't. It would be much better if we can get a reproducible scenario so that we can try it out at our end. An exported sample API and the instructions to try it out would be nice. 

Also some questions:
1. Is it only reproducible in AWS Fargate? 
2. Are you using any load balancers in front?
3. Did you try downgrading the JDK version to 8? (To find it out whether JDK level has an impact)

**Comment by SlobodanRasetic** [comment] 2021-11-30 16:09
Hi @arunans23. Including @juanledesma84.

Unfortunately, we don't have a specific scenario that reproduces the problem. It materializes itself after we run our APIM manger instances in either our AWS staging or production environments even after a very light load but it takes several hours to get to 100%. We have many APIs so we don't know whether some specific ones are causing this issue or all of them. It happens both in AWS Fargate and EC2 Linux instances.

The following issue that was already opened by someone else describes our problem:

https://issues.apache.org/jira/browse/HTTPCORE-687?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

We are trying to apply this fix ourselves but we cannot find the source code for: httpcore-nio_4.4.14.wso2v1.jar

Here are the answers to your question:

1. Is it only reproducible in AWS Fargate?
  No, the issue exists when we deploy it to EC2 Linux instance as well
2. Are you using any load balancers in front?
  Yes.
3. Did you try downgrading the JDK version to 8? (To find it out whether JDK level has an impact)
 Yes, we tried mutiple versions of both JDK 8 and  JDK 11 and the issue is exactly the same.

**Comment by SlobodanRasetic** [comment] 2021-11-30 19:01
HI @arunans23, we have put the recommended fix in place based on: https://issues.apache.org/jira/browse/HTTPCORE-687?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel.

It looks promising so far but we will keep monitoring for a few days to make sure.

**Comment by walirazz** [comment] 2022-06-03 18:02
Where Can I find the patched wso2 Jar file @SlobodanRasetic? I am facing similar issue.

**Comment by prabhuteja5** [comment] 2023-05-19 06:44
I/O error: General SSLEngine problem
getting this problem with wso2 apim 4.1.0 any solutions?

**Comment by nandika** [comment] 2024-11-28 12:33
This is fixed with the new version of product.

**Closed by nandika** 2024-11-28 12:33 UTC
Labels: Type/Bug, Priority/Normal
