### ISSUE TITLE
[APIM 3.0.0] issue in exposing SOAP endpoint as REST API

### ISSUE THREAD

**Issue by ujitha** [wso2/product-apim#7599] opened 2020-02-28 10:14 UTC
### Description:

I'm using APIM 3.0.0 to expose a SOAP backend as REST API but when invoking the api it doesn't give any error but does not return the required output,  Apparently it doesn't create a required synapse artifact to call the SOAP back end. This worked fine in APIM 2.6

used SOAP back end
WDSL location  :  http://192.168.104.41:8280/services/HMS?wsdl
Service url :  https://192.168.104.41:8243/services/HMS

Following is the wirelog of the API request 

[2020-02-26 22:20:24,163] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "GET /hospital/2.0/getPatient?id=100 HTTP/1.1[\r][\n]"
[2020-02-26 22:20:24,165] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlpqUm1ZVE13TlRKak9XVTVNbUl6TWpnek5ESTNZMkl5TW1JeVkyRXpNamRoWmpWaU1qYzBaZz09In0.eyJzdWIiOiJhZG1pbkBjYXJib24uc3VwZXIiLCJiYWNrZW5kSnd0IjoiZXlKMGVYQWlPaUpLVjFRaUxDSmhiR2NpT2lKU1V6STFOaUlzSW5nMWRDSTZJbHBxVW0xWlZFMTNUbFJLYWs5WFZUVk5iVWw2VFdwbmVrNUVTVE5aTWtsNVRXMUplVmt5UlhwTmFtUm9XbXBXYVUxcVl6QmFaejA5SW4wPS5leUpvZEhSd09sd3ZYQzkzYzI4eUxtOXlaMXd2WTJ4aGFXMXpYQzkxYzJWeWJtRnRaU0k2SW1Ga2JXbHVJaXdpYUhSMGNEcGNMMXd2ZDNOdk1pNXZjbWRjTDJOc1lXbHRjMXd2Y205c1pTSTZXeUpKYm5SbGNtNWhiRnd2YzNWaWMyTnlhV0psY2lJc0lrRndjR3hwWTJGMGFXOXVYQzloWkcxcGJsOWhaRzFwYmw5d2RXSnNhWE5vWlhJaUxDSkpiblJsY201aGJGd3ZZM0psWVhSdmNpSXNJa0Z3Y0d4cFkyRjBhVzl1WEM5aFpHMXBibDlFWldaaGRXeDBRWEJ3YkdsallYUnBiMjVmVUZKUFJGVkRWRWxQVGlJc0lrRndjR3hwWTJGMGFXOXVYQzloWkcxcGJsOWhaRzFwYmw5emRHOXlaU0lzSWtsdWRHVnlibUZzWEM5d2RXSnNhWE5vWlhJaUxDSkpiblJsY201aGJGd3ZaWFpsY25sdmJtVWlMQ0poWkcxcGJpSXNJa2x1ZEdWeWJtRnNYQzloYm1Gc2VYUnBZM01pTENKQmNIQnNhV05oZEdsdmJsd3ZZV1J0YVc1ZmVIbDZTRzl6Y0dsMFlXeFhaV0pCY0hCZlVGSlBSRlZEVkVsUFRpSmRMQ0pvZEhSd09sd3ZYQzkzYzI4eUxtOXlaMXd2WTJ4aGFXMXpYQzloY0hCc2FXTmhkR2x2Ym5ScFpYSWlPaUpWYm14cGJXbDBaV1FpTENKb2RIUndPbHd2WEM5M2MyOHlMbTl5WjF3dlkyeGhhVzF6WEM5emRXSnpZM0pwWW1WeUlqb2lZV1J0YVc0aUxDSm9kSFJ3T2x3dlhDOTNjMjh5TG05eVoxd3ZZMnhoYVcxelhDOXJaWGwwZVhCbElqb2lVRkpQUkZWRFZFbFBUaUlzSW1semN5STZJbmR6YnpJdWIzSm5YQzl3Y205a2RXTjBjMXd2WVcwaUxDSm9kSFJ3T2x3dlhDOTNjMjh5TG05eVoxd3ZZMnhoYVcxelhDOWhjSEJzYVdOaGRHbHZibTVoYldVaU9pSjRlWHBJYjNOd2FYUmhiRmRsWWtGd2NDSXNJbWgwZEhBNlhDOWNMM2R6YnpJdWIzSm5YQzlqYkdGcGJYTmNMMlZ1WkhWelpYSWlPaUpoWkcxcGJrQmpZWEppYjI0dWMzVndaWElpTENKb2RIUndPbHd2WEM5M2MyOHlMbTl5WjF3dlkyeGhhVzF6WEM5bGJtUjFjMlZ5VkdWdVlXNTBTV1FpT2lJdE1USXpOQ0lzSW1WNGNDSTZNVFU0TWpjek5qWTNPU3dpYUhSMGNEcGNMMXd2ZDNOdk1pNXZjbWRjTDJOc1lXbHRjMXd2WVhCd2JHbGpZWFJwYjI1cFpDSTZJak16SWl3aWFIUjBjRHBjTDF3dmQzTnZNaTV2Y21kY0wyTnNZV2x0YzF3dllYQndiR2xqWVhScGIyNVZWVWxrSWpvaVpHTTFOVFEyWldVdE5tVmtNeTAwT1dKa0xXRTFPRGt0TldFMk9EQXpZVFk0WkdGbUluMD0uUHY2WVVuVHh3NHpkN2d5WUJTcG5XVE5MQTFKY1hNS2dEWnl0QXlmVUljRDNCc25VT1d3R0o1eHpSbVVuX1FnX2hRQUc1Y2pMZklxUUFkdXc0bFF1R0NJX3JXR21xZGtYZXJYcGVvbEVaZnJiUWt4ZkhkTmdsU1Bpb0ZIWXNIdExwUURqQWdTUVd6N1FqcEpiQkV6cHBhWEpmZWNVazZHUVgxOHMwTFlNdmtycXcwZDZUMFZ6WGtXVFIzT0hkQk1vLUZvSUM1SXJpREZjckc1Nll2ZS1jRWRuS0NhT3V0MEE0SlphRmdSaUVOVGplTlN4WGR6UkpnRHk1YXZoTmJTaTNBeEZ3M0pBT0tSUVpRdzRUd09vU2E1Xy1DVEhmZjlFcVRzYV9ORUF1QmJrMEhjaWw2NktzUk1uaW1nX2N3bFhONThpSWo1dlQ3WThMWWdDWjR1Y1ZnPT0iLCJpc3MiOiJodHRwczpcL1wvbG9jYWxob3N0Ojk0NDNcL29hdXRoMlwvdG9rZW4iLCJ0aWVySW5mbyI6eyJVbmxpbWl0ZWQiOnsic3RvcE9uUXVvdGFSZWFjaCI6dHJ1ZSwic3Bpa2VBcnJlc3RMaW1pdCI6MCwic3Bpa2VBcnJlc3RVbml0IjpudWxsfX0sImtleXR5cGUiOiJQUk9EVUNUSU9OIiwic3Vic2NyaWJlZEFQSXMiOlt7InN1YnNjcmliZXJUZW5hbnREb21haW4iOiJjYXJib24uc3VwZXIiLCJuYW1lIjoiaG9zcGl0YWwiLCJjb250ZXh0IjoiXC9ob3NwaXRhbFwvMi4wIiwicHVibGlzaGVyIjoiYWRtaW4iLCJ2ZXJzaW9uIjoiMi4wIiwic3Vic2NyaXB0aW9uVGllciI6IlVubGltaXRlZCJ9XSwiYXVkIjoiaHR0cDpcL1wvb3JnLndzbzIuYXBpbWd0XC9nYXRld2F5IiwiYXBwbGljYXRpb24iOnsib3duZXIiOiJhZG1pbiIsInRpZXIiOiJVbmxpbWl0ZWQiLCJuYW1lIjoieHl6SG9zcGl0YWxXZWJBcHAiLCJpZCI6MzMsInV1aWQiOm51bGx9LCJzY29wZSI6ImFtX2FwcGxpY2F0aW9uX3Njb3BlIGRlZmF1bHQiLCJjb25zdW1lcktleSI6ImpKamNZazAxUnRlNk53bU0zb3V4WUc3YThCb2EiLCJleHAiOjE1ODI3MzkzNzksImlhdCI6MTU4MjczNTc3OSwianRpIjoiODczZTg3NGYtY2M4OS00NTAwLTg0OTQtOGE0NmRhNGJjOWE2In0.RRYZ2NSchm4NA1Dr3zb9S3KyHUFHuk0Qnzc_n9JENQu_7Zr1xunIP5vFlfCVcdxK5uJPrwLXx5-CtSssGlqK7isiC_RxLBDz6_V2LhpjTg-I5jdK-046Q2uxzGXjjD2yvF5RYoVoQ1pU_BCBCtR123jPERmIGBX4noYMnm-Y54nY5lnvo7JoyFfbYCet9_gpplgYJMcWGSfgeHjOZNYHfn3C8MeUz_gZRbwY-qUDSFN1DZHy_wnfa1CKjl9lHJ24iiRISJaS6uJPTTtDYb8V__C4N-1KfNDKSja_SQ4anxNKr75oHmFmtjPxpUZ5qQWuIyn3MXDbcPuLQDvj0I19Hg[\r][\n]"
[2020-02-26 22:20:24,165] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "Accept: application/json[\r][\n]"
[2020-02-26 22:20:24,166] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "User-Agent: PostmanRuntime/7.22.0[\r][\n]"
[2020-02-26 22:20:24,166] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "Cache-Control: no-cache[\r][\n]"
[2020-02-26 22:20:24,166] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "Postman-Token: 0c1272b4-3a0e-4900-9c9b-a8fe44baf56c[\r][\n]"
[2020-02-26 22:20:24,166] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "Host: localhost:8243[\r][\n]"
[2020-02-26 22:20:24,167] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "Accept-Encoding: gzip, deflate, br[\r][\n]"
[2020-02-26 22:20:24,167] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "Connection: keep-alive[\r][\n]"
[2020-02-26 22:20:24,167] DEBUG - wire HTTPS-Listener I/O dispatcher-2 >> "[\r][\n]"
[2020-02-26 22:20:24,287]  INFO - DependencyTracker Local entry : gov:/apimgt/statistics/ga-config.xml was added to the Synapse configuration successfully
[2020-02-26 22:20:24,403] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "GET /services/HMS.HMSHttpSoap11Endpoint/getPatient?id=100 HTTP/1.1[\r][\n]"
[2020-02-26 22:20:24,404] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "Authorization: Basic dXNlcjE6dXNlcjEyMw==[\r][\n]"
[2020-02-26 22:20:24,405] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "X-JWT-Assertion: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlpqUm1ZVE13TlRKak9XVTVNbUl6TWpnek5ESTNZMkl5TW1JeVkyRXpNamRoWmpWaU1qYzBaZz09In0=.eyJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC91c2VybmFtZSI6ImFkbWluIiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvcm9sZSI6WyJJbnRlcm5hbFwvc3Vic2NyaWJlciIsIkFwcGxpY2F0aW9uXC9hZG1pbl9hZG1pbl9wdWJsaXNoZXIiLCJJbnRlcm5hbFwvY3JlYXRvciIsIkFwcGxpY2F0aW9uXC9hZG1pbl9EZWZhdWx0QXBwbGljYXRpb25fUFJPRFVDVElPTiIsIkFwcGxpY2F0aW9uXC9hZG1pbl9hZG1pbl9zdG9yZSIsIkludGVybmFsXC9wdWJsaXNoZXIiLCJJbnRlcm5hbFwvZXZlcnlvbmUiLCJhZG1pbiIsIkludGVybmFsXC9hbmFseXRpY3MiLCJBcHBsaWNhdGlvblwvYWRtaW5feHl6SG9zcGl0YWxXZWJBcHBfUFJPRFVDVElPTiJdLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9hcHBsaWNhdGlvbnRpZXIiOiJVbmxpbWl0ZWQiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9zdWJzY3JpYmVyIjoiYWRtaW4iLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9rZXl0eXBlIjoiUFJPRFVDVElPTiIsImlzcyI6IndzbzIub3JnXC9wcm9kdWN0c1wvYW0iLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9hcHBsaWNhdGlvbm5hbWUiOiJ4eXpIb3NwaXRhbFdlYkFwcCIsImh0dHA6XC9cL3dzbzIub3JnXC9jbGFpbXNcL2VuZHVzZXIiOiJhZG1pbkBjYXJib24uc3VwZXIiLCJodHRwOlwvXC93c28yLm9yZ1wvY2xhaW1zXC9lbmR1c2VyVGVuYW50SWQiOiItMTIzNCIsImV4cCI6MTU4MjczNjY3OSwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvYXBwbGljYXRpb25pZCI6IjMzIiwiaHR0cDpcL1wvd3NvMi5vcmdcL2NsYWltc1wvYXBwbGljYXRpb25VVUlkIjoiZGM1NTQ2ZWUtNmVkMy00OWJkLWE1ODktNWE2ODAzYTY4ZGFmIn0=.Pv6YUnTxw4zd7gyYBSpnWTNLA1JcXMKgDZytAyfUIcD3BsnUOWwGJ5xzRmUn_Qg_hQAG5cjLfIqQAduw4lQuGCI_rWGmqdkXerXpeolEZfrbQkxfHdNglSPioFHYsHtLpQDjAgSQWz7QjpJbBEzppaXJfecUk6GQX18s0LYMvkrqw0d6T0VzXkWTR3OHdBMo-FoIC5IriDFcrG56Yve-cEdnKCaOut0A4JZaFgRiENTjeNSxXdzRJgDy5avhNbSi3AxFw3JAOKRQZQw4TwOoSa5_-CTHff9EqTsa_NEAuBbk0Hcil66KsRMnimg_cwlXN58iIj5vT7Y8LYgCZ4ucVg==[\r][\n]"
[2020-02-26 22:20:24,405] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "Accept: application/json[\r][\n]"
[2020-02-26 22:20:24,405] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "Cache-Control: no-cache[\r][\n]"
[2020-02-26 22:20:24,405] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "Postman-Token: 0c1272b4-3a0e-4900-9c9b-a8fe44baf56c[\r][\n]"
[2020-02-26 22:20:24,406] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "Accept-Encoding: gzip, deflate, br[\r][\n]"
[2020-02-26 22:20:24,406] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "Host: 192.168.104.41:8243[\r][\n]"
[2020-02-26 22:20:24,406] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "Connection: Keep-Alive[\r][\n]"
[2020-02-26 22:20:24,406] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "User-Agent: Synapse-PT-HttpComponents-NIO[\r][\n]"
[2020-02-26 22:20:24,406] DEBUG - wire HTTPS-Sender I/O dispatcher-2 << "[\r][\n]"
[2020-02-26 22:20:24,446] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "HTTP/1.1 202 Accepted[\r][\n]"
[2020-02-26 22:20:24,446] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "Date: Wed, 26 Feb 2020 16:50:24 GMT[\r][\n]"
[2020-02-26 22:20:24,446] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "Transfer-Encoding: chunked[\r][\n]"
[2020-02-26 22:20:24,476] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "Connection: Keep-Alive[\r][\n]"
[2020-02-26 22:20:24,477] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "[\r][\n]"
[2020-02-26 22:20:24,477] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "0[\r][\n]"
[2020-02-26 22:20:24,477] DEBUG - wire HTTPS-Sender I/O dispatcher-2 >> "[\r][\n]"
[2020-02-26 22:20:24,489] DEBUG - wire HTTPS-Listener I/O dispatcher-2 << "HTTP/1.1 202 Accepted[\r][\n]"
[2020-02-26 22:20:24,489] DEBUG - wire HTTPS-Listener I/O dispatcher-2 << "Access-Control-Expose-Headers: [\r][\n]"
[2020-02-26 22:20:24,490] DEBUG - wire HTTPS-Listener I/O dispatcher-2 << "Access-Control-Allow-Origin: *[\r][\n]"
[2020-02-26 22:20:24,490] DEBUG - wire HTTPS-Listener I/O dispatcher-2 << "Access-Control-Allow-Methods: GET[\r][\n]"
[2020-02-26 22:20:24,490] DEBUG - wire HTTPS-Listener I/O dispatcher-2 << "Access-Control-Allow-Headers: authorization,Access-Control-Allow-Origin,Content-Type,SOAPAction,Authorization[\r][\n]"
[2020-02-26 22:20:24,490] DEBUG - wire HTTPS-Listener I/O dispatcher-2 << "Content-Type: application/octet-stream[\r][\n]"
[2020-02-26 22:20:24,490] DEBUG - wire HTTPS-Listener I/O dispatcher-2 << "Date: Wed, 26 Feb 2020 16:50:24 GMT[\r][\n]"
[2020-02-26 22:20:24,490] DEBUG - wire HTTPS-Listener I/O dispatcher-2 << "Transfer-Encoding: chunked[\r][\n]"
[2020-02-26 22:20:24,490] DEBUG - wire HTTPS-Listener I/O dispatcher-2 << "Connection: keep-alive[\r][\n]"
[2020-02-26 22:20:24,491] DEBUG - wire HTTPS-Listener I/O dispatcher-2 << "[\r][\n]"
[2020-02-26 22:20:24,491] DEBUG - wire HTTPS-Listener I/O dispatcher-2 << "0[\r][\n]"
[2020-02-26 22:20:24,491] DEBUG - wire HTTPS-Listener I/O dispatcher-2 << "[\r][\n]"
### Affected Product Version:

APIM 3.0.0
### Environment details (with versions):
- OS: Mac OS 10.14.6 

---

**Comment by malinthaprasan** [comment] 2020-03-02 05:06
Could not reproduce the issue when using WSDL URL mode but issue is reproducible when doing a WSDL/ZIP file upload. The issue is fixed in https://github.com/wso2/carbon-apimgt/pull/8277

**Closed** 2020-03-02 05:08 UTC
Labels: 3.1.0, Priority/Highest, Severity/Critical, Type/Bug
