### ISSUE TITLE
Need to show an warning when deleting an API with active subscriptions

### ISSUE THREAD

**Issue by vithu30** [wso2/product-apim#5567] opened 2019-09-16 05:08 UTC
When deleting an API with active subscriptions, no warning message is thrown.
Need to have an warning alert similar to this:
![active](https://user-images.githubusercontent.com/19728269/64935287-05fd4f80-d86e-11e9-8da4-07c535ff6ae9.png)

**Comment by chamilaadhi** [comment] 2019-09-25 17:45
duplicate of https://github.com/wso2/product-apim/issues/5609

**Closed** 2019-09-25 17:57 UTC
Labels: 3.0.0, Priority/High, Publisher, Resolution/Duplicate
