### ISSUE TITLE
[Improvement] Faulty Invocations per Application on API Store should be improved to show some message if no data exist 

### ISSUE THREAD

**Issue by shavantha** [wso2/product-apim#2802] opened 2018-02-26 08:20 UTC
**Description:**
Faulty Invocations per Application on API Store should be improved to show some message if no data exist. As shown on the image only a table header is shown to the use

**Affected Product Version:**
APIM-2.1.0
**OS, DB, other environment details and versions:**    
Fresh-pack

**Steps to reproduce:**
1. on API store load the faulty invocations to view the analytics. When no data exist the system does not show any massage and this gives an idea as if the report is not working

**Comment by rmsamitha** [comment] 2022-01-28 04:51
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:51 UTC
Labels: Affected/2.1.0
