### ISSUE TITLE
An application cannot be created through REST call once the desired users are created through admin services

### ISSUE THREAD

**Issue by isuruuy429** [wso2/product-apim#2659] opened 2018-02-01 16:11 UTC
**Description:**
An application in the API Store cannot be created through REST call once the desired users are created through admin services. 
Getting the below error as the response in the backend and as the response of cURL respectively. 
`ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed`
`{"code":401,"message":"","description":"Unauthenticated request","moreInfo":"","error":[]}`

**Suggested Labels:**
Type/Bug
Severity/Blocker
Priority/Highest

**Suggested Assignees:**
N/A

**Affected Product Version:**
apim-2.1.0-update 8

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create a user through admin services. 
`https://localhost:9443/services/UserAdmin.UserAdminHttpsSoap12Endpoint`
```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://org.apache.axis2/xsd" xmlns:xsd1="http://common.mgt.user.carbon.wso2.org/xsd">
   <soap:Header/>
   <soap:Body>
      <xsd:addUser>
         <!--Optional:-->
         <xsd:userName>user1</xsd:userName>
         <!--Optional:-->
         <xsd:password>user1</xsd:password>
         <!--Zero or more repetitions:-->
         <!--Optional:-->
         <xsd:profileName>Default</xsd:profileName>
      </xsd:addUser>
   </soap:Body>
</soap:Envelope>
```
2. Create user role through the admin service. 
`https://10.100.5.136:9443/services/UserAdmin.UserAdminHttpsSoap11Endpoint`

```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://org.apache.axis2/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <xsd:addRole>
         <!--Optional:-->
         <xsd:roleName>Subs</xsd:roleName>
         <!--Zero or more repetitions:-->
         <xsd:userList>user1</xsd:userList>
         <!--Zero or more repetitions:-->
         <xsd:permissions>/permission/admin/manage/api/subscribe</xsd:permissions>
          <xsd:permissions>/permission/admin/login</xsd:permissions>
         <!--Optional:-->
         <xsd:isSharedRole>false</xsd:isSharedRole>
      </xsd:addRole>
   </soapenv:Body>
</soapenv:Envelope>
```

3. Create auth app by using user1 credentials. 
`curl -X POST -H "Authorization: Basic <base64(user1:user1)>" -H "Content-Type: application/json" -d @/location/to/payload.json https://localhost:9443/client-registration/v0.11/register -k `

payload.json
```
{
    "callbackUrl": "localhost",
    "clientName": "storeuser2",
    "tokenScope": "Production",
    "owner": "user1",
    "grantType": "password refresh_token",
    "saasApp": true
}
```

4. Get the base64(<clientId:clientSecret>) 
5. Send the following cURL command. 
`curl -k -d "grant_type=password&username=user1&password=user1&scope=apim:subscribe" -H "Authorization: Basic base64(<clientId:clientSecret>) " https://localhost:8243/token`

An access token will be generated. 

6. Using the above generated access token, try to create an application in the API Store. 
`curl -k -H "Authorization: Bearer <access-token>" -H "Content-Type: application/json" -X POST -d @/path/to/payload2.json "https://localhost:9443/api/am/store/v0.11/applications"`

payload2.json
```
{
    "throttlingTier": "Unlimited",
    "description": "sample app description",
    "name": "app1user1",
    "callbackUrl": "localhost"
}

```

**Expected:** An application should be generated. 
**Actual:** No application is created. Following error message is displayed. 
`ERROR - WebAppAuthenticatorImpl You cannot access API as scope validation failed`
`{"code":401,"message":"","description":"Unauthenticated request","moreInfo":"","error":[]}`

**Comment by msm1992** [comment] 2018-02-07 07:16
Roles that are eligible to get access tokens for the REST api scopes secured with Oauth are defined /_system/config/apimgt/applicationdata/tenant-conf.json as shown in [1]. So in this particular scenario I guess the newly created Role 'Subs' was not listed under eligible roles for apim:subscribe scope before generating the access token. Therefore the access token issued cannot be used to invoke POST /applications resource and the error message you get is correct. I tried the same scenario after modifying the tenant-conf.json to include Subs role as well under apim:subscriber scope as below and then this worked without giving any errors.

Ex: {
        "Name": "apim:subscribe",
        "Roles": "admin,Internal/subscriber,Subs"
      }

This is not a bug.

[1]. https://docs.wso2.com/display/AM210/apidocs/store/#configuring-rest-api

**Comment by malinthaprasan** [comment] 2018-02-07 08:04
Closing as per the previous comment.

**Closed by malinthaprasan** 2018-02-07 08:04 UTC
Labels: 2.2.0, Priority/Highest, Severity/Blocker, Type/Bug
