### ISSUE TITLE
Upload button not working properly for creator

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [wso2/product-apim#5818] opened 2019-09-26 06:49 UTC
**Description**

- I tried to upload an image using the creator role. But it fails and returned the following page.

![Screenshot from 2019-09-26 12-17-15](https://user-images.githubusercontent.com/44407066/65664804-c269c900-e057-11e9-91b8-ec252eee638f.png)

**Comment by TanyaM** [comment] 2019-09-27 05:23
Duplicate of #https://github.com/wso2/product-apim/issues/5734

**Closed by TanyaM** 2019-09-27 05:23 UTC
