### ISSUE TITLE
"Visible to tenants" field does not appear upon selecting subscription option "Available to specific tenants"

### ISSUE THREAD

**Issue by dinusha-dilrukshi** [wso2/product-apim#3120] opened 2018-03-23 00:24 UTC
**Description:**
When we select Subscriptions = "Available to specific tenants", we cannot see "Visible to tenants" field where you enter tenant names.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
- Create some tenant
- Login to the publisher as super tenant and create some API. In the "Manage" step, we can see "Subcriptions" drop down. But once we select the "Available to specific tenants" option from the drop down, it doesn't appear "Visible to tenants" field where you enter tenant names.

**Related Issues:**

**Comment by chamilaadhi** [comment] 2018-03-23 08:42
duplicate of https://github.com/wso2/product-apim/issues/2184 . This is fixed in AM 2.2.0

**Closed by chamilaadhi** 2018-03-23 08:42 UTC
