### ISSUE TITLE
[UX] User is not guided to generate keys after subscribing to an application

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#2910] opened 2018-03-07 10:59 UTC
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Clear call for action - Was user able to clearly define the next action to perform
Flexibility and efficiency of use -Does the task cater to both experienced and inexperienced users
User guidance -Is user guided throughout the process?

***Related task:***
Subscribe to an application

***Issue:***
User is not guided through the UI to generate keys before invoking an API

***Proposed Solution:***
Mail thread: API Manager Store Subscription flow usability issues
	
**Suggested Labels:**
UX, Improvement, 2.1.0

**Affected Product Version:**
2.1.0

**Comment by rmsamitha** [comment] 2022-01-28 04:35
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:35 UTC
Labels: Priority/Low, Affected/2.1.0
