### ISSUE TITLE
[UX][Store] Structure forget password element in login screen

### ISSUE THREAD

**Issue by Minoli** [wso2/product-apim#3058] opened 2018-03-15 06:29 UTC
**Description:**

***Not fulfilling [checklist items](https://docs.google.com/spreadsheets/d/1l6YKXSbmtykvvn_NvX6uJbXSsZvpT8jn72Qoi_FoJq8/edit#gid=1221574205):***
Consistency and Standards - Is flow maintain the same patterns and consistency? 

***Related task:***
Login to store

***Issue:***
Forget password element should come before sign in button

***Proposed Solution:***
![screenshot-fgt-pwd](https://user-images.githubusercontent.com/9837443/37454959-f042f11c-2861-11e8-8ace-02b8a3d0ffe9.png)

**Suggested Labels:**
UX, Improvement

**Affected Product Version:**
2.1.0 update 14

**Comment by rmsamitha** [comment] 2022-01-28 04:26
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:26 UTC
Labels: Affected/2.1.0
