### ISSUE TITLE
Unable to download a created REST API with an existing SOAP service

### ISSUE THREAD

**Issue by Lasith650** [wso2/product-apim#10582] opened 2021-03-30 06:54 UTC
### Description:
Created a REST API with an existing SOAP service by importing the WSDL of the SOAP service. Once the API is successfully created in the API-M Publisher I tried to download it with the given "Download API" button. But it gave an error saying "Error while exporting API"

![Screenshot from 2021-03-30 12-01-51](https://user-images.githubusercontent.com/23395897/112945542-132d1700-9152-11eb-962b-50e403a5fb89.png)

### Steps to reproduce:

1. Create a user with Creator permissions.
2. Log in to the publisher portal.
3. Create a REST API with an existing SOAP service by importing the WSDL of the SOAP service.
4. After successfully creating the API click on the "Download API" button which is located at upper right hand corner next to bin icon.

### Affected Product Version:
4.0.0

### Environment details (with versions):
- OS: Linux

---
#### Suggested Labels:

API-M 4.0.0

**Comment by rmsamitha** [comment] 2021-04-09 12:52
Cannot reproduce the issue. Hence closing.

**Closed by rmsamitha** 2021-04-09 12:52 UTC
Labels: API-M 4.0.0, Feature/ImportExport, Priority/Normal, Type/Bug
