### ISSUE TITLE
Application details page, sandbox and subscription tabs not show correct content

### ISSUE THREAD

**Issue by ruks** [wso2/product-apim#1961] opened 2017-12-08 02:41 UTC
**Description:**
Application details page, sandbox and subscription tabs not show correct content
And also don't provide expected functions like subscription delete etc.

**Comment by tmkasun** [comment] 2017-12-08 15:19
Seems like a duplicate of https://github.com/wso2/product-apim/issues/1956 , shall we keep continue the discussion there ?

**Comment by ruks** [comment] 2017-12-08 15:31
subscription tabs information is also not rendering correctly. Subscriptions view and remove is not possible with current UI.

**Comment by tmkasun** [comment] 2020-10-06 10:48
This is already fixed in APIM 3.2.0 hence closing the issue

**Closed by tmkasun** 2020-10-06 10:48 UTC
Labels: Affected/3.0.0, Type/Bug, duplicate
