### ISSUE TITLE
[UX][Publisher] API Walkthrough Guide Improvements

### ISSUE THREAD

**Issue by jeradrutnam** [wso2/product-apim#3317] opened 2018-06-01 06:53 UTC
**Description:**
> 1. After clicking the last action button "Go to store" in the walkthrough, on next step arrow points to no where and says "Go to API Store". And since this is the last step, there should be a primary "Finish" action button within the tour for users to close it.

![image](https://user-images.githubusercontent.com/7569427/40825104-37a39b78-6594-11e8-912b-37381fb521f9.png)

> 2. If user restarts the the walkthrough guide again by clicking the link on top header bar. It starts as below. Where it asks to click on a white space. Where I found it is not intuitive. I think better we remove this step and merge this content to the next step just after where it points to the "Add New API" button. 

![image](https://user-images.githubusercontent.com/7569427/40825564-886ee20a-6595-11e8-81d8-a9f1d3fe1f76.png)

**Suggested Labels:**
> [Type/UX]

**Affected Product Version:**
> 2.2.0

**OS, DB, other environment details and versions:**
All

**Steps to reproduce:**
1. Start APIM Publisher freshly and follow the quick start guide tour
2. For the issue see the description

**Comment by rmsamitha** [comment] 2022-01-28 04:13
Closing the issue as this is older than 3 years. Please reopen if the issue is valid still.

**Closed by rmsamitha** 2022-01-28 04:13 UTC
Labels: 3.x.x
